---
title: "Working with files in the shell - part II"
subtitle: "Week 3 - Part II"
pagetitle: "PRACS25: Files in the shell"
author: Jelmer Poelstra
date: 2025-09-11
editor_options: 
  chunk_output_type: console
---

---------

<br>

## Goals & setting up

In this session, you will learn additional Unix shell skills,
focusing on commands to manage files with an eye on organizing your research projects.

Specifically, you will learn about:

- **Wildcard expansion** to select and operate on multiple files at once
- **Command substitution** to save the output of commands
- **For loops** to repeat operations, e.g. across files
- **Renaming multiple files** using for loops

<hr style="height:1pt; visibility:hidden;" />

### VS Code setup

::: {.callout-note collapse="true"}
## Starting VS Code at OSC - with a Terminal *(Click to expand)*

1.  Log in to OSC's OnDemand portal at <https://ondemand.osc.edu>.
2.  In the blue top bar, select `Interactive Apps` and then near the bottom of the dropdown menu, click `Code Server`.
3.  In the form that appears on a new page:
    -   Select OSC project `PAS2880`
    -   The starting directory: `/fs/ess/PAS2880/users/<user>` (replace `<user>` with your OSC username)
    -   `Number of hours`: `2`
    -   Click `Launch`.
4.  On the next page, once the top bar of the box has turned green and says `Runnning`, click `Connect to VS Code`.
5.  Open a Terminal by clicking   {{< fa bars >}}   =\> `Terminal` =\> `New Terminal`.
6.  Type `pwd` to check where you are.
    
    If you are not in `/fs/ess/PAS2880/users/<user>`
    click    {{< fa bars >}}   =\>   `File`   =\>   `Open Folder`,
    then type/select `/fs/ess/PAS2880/users/<user>` and press OK.
:::

<hr style="height:1pt; visibility:hidden;" />

### Create a dummy project folder structure

Go into the dir for this week that you created earlier:

```sh
# You should be in /fs/ess/PAS2880/users/$USER/
cd week03
```
  
First, we'll create a set of directories representing a dummy research project:

```sh
mkdir dummy-project
cd dummy-project
```

```sh
# The -p option for mkdir will allow for 'recursive' (nested) dir creation
mkdir -p data/fastq scripts results/figures results/alignments
```

We will use the  `touch` command to create empty files that are mock representations
of FASTQ sequence files with forward ("R1") and reverse ("R2") DNA sequence reads
for 3 samples:
  
```sh
# (Copy-and-paste this rather than typing it out) 
touch data/fastq/sample1_R1.fastq data/fastq/sample1_R2.fastq
touch data/fastq/sample2_R1.fastq data/fastq/sample2_R2.fastq
touch data/fastq/sample3_R1.fastq data/fastq/sample3_R2.fastq
```

For a nice recursive overview of the project directory structure you just created,
use the **`tree` command** (with option `-C` to show colors):

```bash
# (Output colors are not shown on this webpage)
tree -C
```
```bash-out
../..
├── data
│   └── fastq
│       ├── sample1_R1.fastq
│       ├── sample1_R2.fastq
│       ├── sample2_R1.fastq
│       ├── sample2_R2.fastq
│       ├── sample3_R1.fastq
│       └── sample3_R2.fastq
├── results
│   └── figures
└── scripts

5 directories, 6 files
```

<br>

## Wildcard expansion

Shell wildcard expansion is a very useful technique to select files,
where **wildcards** are _characters that have a special meaning_.
With the following files in our directory...

```sh
cd data/fastq
ls
```
```bash-out
sample1_R1.fastq  sample1_R2.fastq  sample2_R1.fastq
sample2_R2.fastq  sample3_R1.fastq  sample3_R2.fastq
```

...let's say we wanted to operate only on a subset of these files.
The first examples will continue to use `ls`,
but we can use this technique with any command that operates on files.

### The `*` wildcard

By far the most commonly used wildcard is `*`,
which matches **any number of any combination of characters**
(including "nothing" -- the absence of any characters).
For example, we can match only the two `sample1` files with a `*` using:

```bash
# This matches files that start with "sample1"
ls sample1*
```
```bash-out
sample1_R1.fastq  sample1_R2.fastq
```

<hr style="height:1pt; visibility:hidden;" />

If the pattern we use for matching is in the middle of the filename,
we need a `*` on both sides of it --- for example:

```bash
# This matches files that contain, anywhere in their names, "R1":
ls *R1*
```
```bash-out
sample1_R1.fastq  sample2_R1.fastq  sample3_R1.fastq
```

<hr style="height:1pt; visibility:hidden;" />

Selecting files with wildcard expansion is called **globbing**.
When globbing, the pattern has to match the entire file name
(i.e. no partial matches like with `grep`),
so the following doesn't match anything, in this scenario:

```bash
# This matches files that _end in_ R1, but there are no such files:
ls *R1
```
```bash-out
ls: cannot access *R1: No such file or directory
```

<hr style="height:1pt; visibility:hidden;" />

In summary:

| Pattern        | Matches files whose names... 
|----------------|---------------------------|
| `sample1*`     | **Start with** "sample1"
| `*fastq`    | **End with** ".fastq"
| `*_R1*`        | **Contain** "\_R1"
| `*`            | _(matches all files in the working dir)_^[Except so-called hidden files.]

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} **Exercise**: File matching

**A)** List only the FASTQ files for sample 3.

<details><summary>Click for the solution</summary>

```bash
ls sample3*
```
```bash-out
sample3_R1.fastq  sample3_R2.fastq
```
</details>

**B)** Which files does `ls *samp*le*` match? Make a prediction before you test it.

<details><summary>Click for the solution</summary>
All of them, since all file names start with `sample`,
and because `*` also matches "zero characters",
there is no requirement for there to be characters at the locations of the
"unnecessary" `*`s.
</details>

**C)** Create 2 new files called `sample1.txt` and `sample2.txt` in the current working dir.
Then, only match the 2 FASTQ files for sample1.

<details><summary>Click for the solution</summary>
```bash
touch sample1.txt sample2.txt

# This means: any file that starts with "sample1" and end with "fastq"
ls sample1*fastq
```
```bash-out
sample1_R1.fastq  sample1_R2.fastq
```
</details>

:::
<hr style="height:1pt; visibility:hidden;" />

There are a couple more shell wildcards, but these are much more rarely used:
check the bonus reading at the bottom of the page if you're curious.

<hr style="height:1pt; visibility:hidden;" />

#### Expansion is done by the shell itself

It is important to realize that the "expansion" --of a wildcard to matching file
names-- is done *by the shell*
and _not_ by `ls` or another command you might be using wildcards with.
**This means that a command like `ls` will "see"/"receive" the list of files _after_**
**the expansion has already happened.**

So, when you type...

```bash
ls sample1*fastq
```

...the shell will _first_ do wildcard expansion and will therefore end up running,
in this particular case:

```bash
ls sample1_R1.fastq sample1_R1.fastq
```

This also means that wildcard expansion works with any command that accepts multiple
paths as arguments, such as _copy_ (`cp` command), *move* (`mv`) or *delete* (`rm`).
For example,
we can remove any stray `.txt` files in our dir for FASTQ files using:

```bash
# (The -v option will make rm report what it's removing)
rm -v *txt
```
```bash-out
removed ‘sample1.txt’
removed ‘sample2.txt’
```

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-warning collapse="true"}
#### In case you have heard of "regular expressions": these are not the same as wildcards _(Click to expand)_
Don't confuse wildcards with **regular expressions**!
You may have used regular expressions before, for example with R or a text editor.
They are similar to but not the same as shell wildcards.
:::

<br>

## Variables and command substitution

Now, we'll cover a few topics that do not directly relate to files,
but that you need to know about before the application at the end of this
session: renaming files with a loop.
Additionally, you will keep using these constructs throughout the course. 

### Variables

Variables are truly ubiquitous in programming.
We typically use them for items that:

- We refer to repeatedly and/or
- Are subject to change.

These tend to be _settings_ like the paths to input and output files,
and parameter values for programs.
**Using variables makes it easier to change such settings and makes it possible**
**to write scripts and programs that are flexible depending on user input.**
Earlier, we already saw a couple of handy applications of variables:
for example, the environment variable `$USER` contains our user name.

#### Assigning and referencing variables

To **assign** a value to a variable in the shell, use the syntax `variable_name=value`:

```bash
# Assign the value "beach" to a variable with the name "location":
location=beach

# Assign the value "200" to a variable with the name "nr_samples":
nr_samples=200
```

:::{.callout-warning}
##### Recall that there can't be spaces around the equals sign (`=`)!
:::

To **reference** a variable (i.e., to access its value):

- You need to put a dollar sign `$` in front of its name.
- It is good practice to double-quote (`"..."`) variable names^[We'll talk more about quoting later.].

As before with the environment variables `$USER` and `$HOME`,
we'll use the `echo` command to see what values our variables contain:

```bash
echo "$location"
```
```{.bash-out}
beach
```

```bash
echo "$nr_samples"
```
```{.bash-out}
200
```

Conveniently, we can use variables in lots of contexts,
_as if we had directly typed their values_:

```bash
input_file=data/fastq/sample1_R1.fastq

ls -lh "$input_file"
```
```{.bash-out}
-rw-rw----+ 1 jelmer PAS0471 0 Mar  7 13:17 data/fastq/sample1_R1.fastq
```

You will learn more about variables and their usage when we cover shell scripts
in a few weeks.

<hr style="height:1pt; visibility:hidden;" />

### Environment variables

You may be familiar with the concept of **variables** from previous experience with perhaps R or another language.
Variables can hold values and other pieces of data and are essential in programming.

- Assigning and printing the value of a variable **in R**:

  ```{r, eval=TRUE}
  #| class-output: styled-output
  # (Don't run this)
  x <- 5
  x
  ```

- Assigning and printing the value of a variable **in the Unix shell**:

  ``` bash
  x=5
  echo $x
  ```
  ``` bash-out
  5
  ```

::: callout-tip
#### In the Unix shell code above, note that:

-   There cannot be any **spaces** around the **`=`** in `x=5`.
-   You need a **`$` prefix** to *reference* (but not to *assign*) variables in the shell[^4].
-   You need the **`echo`** command, a general command to print text, to print the value of `$x` (cf. in R).

By the way, `echo` can also print literal text (as shown below) or combinations
of literals and variables (next exercise):
    
```bash
echo "Welcome to PLNTPTH 5004"
```
```bash-out
Welcome to PLNTPTH 5004
```

<hr style="height:1pt; visibility:hidden;" />

:::

[^4]: Because of this, anytime you see a word/string that starts with a `$` in the shell,
you can safely assume that it is a variable.

**Environment variables** are pre-existing variables that have been automatically assigned values. Two examples:

``` bash
# $HOME contains the path to your Home dir:
echo $HOME
```

``` bash-out
/users/PAS0471/jelmer
```

``` bash
# $USER contains your user name:
echo $USER
```

``` bash-out
jelmer
```

::: exercise
#### {{< fa user-edit >}} Exercise: environment variables

Using an environment variable, print "_Hello, my name is \<your username\>_" (e.g. "Hello, my name is natalie").

<details><summary>*Click for the solution*</summary>

``` bash
# (This would also work without the " " quotes)
echo "Hello, my name is $USER"
```

``` bash-out
Hello, my name is jelmer
```

</details>
:::

### Command substitution

Command substitution allows you to **store the output of a command in a variable**.

Let's see an example.
As you know, the `date` command will print the current date and time:

```bash
date
```
```bash-out
Thu Sep 11 14:52:22 EDT 2025
```

If we try to _store the date in a variable_ directly, it doesn't work:
the literal string "date" is stored instead:

```bash
today=date
echo "$today"
```
```bash-out
date
```

That's why we need command substitution, which we can use by wrapping the command 
inside **`$()`**:

```bash
today=$(date)
echo "$today"
```
```bash-out
Thu Sep 11 14:54:11 EDT 2025
```

<hr style="height:1pt; visibility:hidden;" />

One practical example of using command substitution is when you want to
**automatically include the current date in a file name**
(with "automatic" meaning that you can use the same command regardless of the date,
and that you could use it in a script that you could run at any point).
First, note that we can use `date +%F` to print the date in `YYYY-MM-DD` format,
and omit the time:

```bash
date +%F
```
```bash-out
2025-09-07
```

Let's use that in a command substitution:

```bash
today=$(date +%F)
touch README_"$today".txt

ls
```
```{.bash-out}
README_2025-09-07.txt
```

::: callout-note
#### Or insert the command substitution on the fly
It is even possible to do this all in one go,
by using the command substitution `$(date +%F)` _directly_ in our
`touch` command, rather than first assigning it to a variable:

```bash
touch README_"$(date +%F)".txt
```
:::

<hr style="height:1pt; visibility:hidden;" />

:::{.exercise}
#### {{< fa user-edit >}} Exercise: Command substitution {-}

Say we wanted to count and report the number of FASTQ files in a directory
in a generalized, programmatic way. To do the counting, we can run:

```bash
ls *fastq | wc -l
```
```{.bash-out}
6
```

Now, use command substitution to store the output of the last command in a variable,
and then use an `echo` command to print the following:

```bash-out-solo
The dir has 6 files
```

_To be clear, `6` (or whatever the number of files ends up being) should be contained_
_in a variable and you should not be typing that character yourself!_

<details><summary>Click for a hint</summary>

Your final `echo` command should look something like this:

```bash
echo "The dir has $n_files files"
```

Now, you try to store the number of files in the variable `$n_files`.
</details>

<details><summary>Click for the solution</summary>

```bash
n_files=$(ls *fastq | wc -l)

echo "The dir has $n_files files"
```
```{.bash-out}
The dir has 6 files
```

**Note:**
You don't have to quote variables _inside_ a quoted `echo` call,
since it's, well, already quoted.
If you _also_ quote the variables, you will in fact _unquote_ it,
although that shouldn't pose a problem inside `echo` statements.

</details>
:::

<br>

## For loops

Loops are another universal element of programming languages,
and are used to **repeat operations**.
Here, we'll only cover the most common type of loop: the `for` loop.

A `for` loop _iterates_ over a collection, such as a list of files,
and allows you to perform one or more actions for each element in the collection.
In the example below,
our "collection" is just a short list of numbers (`1`, `2`, and `3`):

```bash
for a_number in 1 2 3; do
    echo "In this iteration of the loop, the number is $a_number"
    echo "--------"
done
```
```bash-out
In this iteration of the loop, the number is 1
--------
In this iteration of the loop, the number is 2
--------
In this iteration of the loop, the number is 3
--------
```

The **indented lines** between `do` and `done` contain the code that is being executed
_as many times as there are items in the collection_:
in this case 3 times, as you can tell from the output above.

What was actually run under the hood is the following:

```bash
# (Don't run this)
a_number=1
echo "In this iteration of the loop, the number is $a_number"
echo "--------"

a_number=2
echo "In this iteration of the loop, the number is $a_number"
echo "--------"

a_number=3
echo "In this iteration of the loop, the number is $a_number"
echo "--------"
```

Here are **two key things to understand about `for` loops**:

- In each iteration of the loop, one element in the collection
  **is being assigned to the variable** specified after `for`.
  In the example above, we used `a_number` as the variable name,
  so that variable contained `1` when the loop ran for the first time,
  `2` when it ran for the second time,
  and `3` when it ran for the third and last time.

- The loop runs sequentially for each item in the collection,
  and will run exactly as many times as there are items in the collection.

::: {.callout-note}
#### A further explanation of `for` loop syntax

On the first and last, unindented lines,
`for` loops contain the following mandatory keywords:

| Keyword | Purpose	                            |
|---------|-------------------------------------|
| `for`	  | After `for`, we set the **variable name** (an arbitrary name; above we used `a_number`)
| `in`	  | After `in`, we specify the **collection** (list of items) we are looping over	
| `do`	  | After `do`, we have one ore more lines specifying what to do with each item	
| `done`  | Tells the shell we are done with the loop 

:::

<hr style="height:1pt; visibility:hidden;" />

#### Combining loops and globbing

A very useful strategy is to loop over files with globbing, for example:

```bash
for fastq_file in *fastq; do
    echo "Running an analysis for file $fastq_file"...
    # [This is where you would put additional commands to process each FASTQ file]
done
```
```bash-out
Running an analysis for file sample1_R1.fastq...
Running an analysis for file sample1_R2.fastq...
Running an analysis for file sample2_R1.fastq...
Running an analysis for file sample2_R2.fastq...
Running an analysis for file sample3_R1.fastq...
Running an analysis for file sample3_R2.fastq...
```

:::{.exercise}
#### {{< fa user-edit >}} **Exercise**: A simple loop {-}

Modify the loop in our previous example to count and then print the number of
lines that each FASTQ file contains:

```bash-out
sample1_R1.fastq contains 0 lines
sample1_R2.fastq contains 0 lines
# etc.
```

_To be clear, the number of lines that the loop reports should result from_
_an actual count with `wc -l` and you should not just type `0`._

<details><summary>Click for the solution</summary>

```bash
for fastq_file in *fastq; do
    n_lines=$(wc -l fastq)
    echo "$fastq_file contains $n_lines lines"
done
```
```bash-out
sample1_R1.fastq contains 0 lines
sample1_R2.fastq contains 0 lines
sample2_R1.fastq contains 0 lines
sample2_R2.fastq contains 0 lines
sample3_R1.fastq contains 0 lines
sample3_R2.fastq contains 0 lines
```
</details>

<hr style="height:1pt; visibility:hidden;" />

**Bonus:** Create a loop that will print:

```{.bash-out}
morel is an Ohio mushroom  
destroying_angel is an Ohio mushroom  
eyelash_cup is an Ohio mushroom
```

<details><summary>Click for the solution</summary>

```bash
for mushroom in morel destroying_angel eyelash_cup; do
    echo "$mushroom is an Ohio mushroom"
done
```
```bash-out
morel is an Ohio mushroom  
destroying_angel is an Ohio mushroom  
eyelash_cup is an Ohio mushroom
```
</details>
:::

<br>

## The `basename` command

In loops and other contexts where you are working with file names programmatically,
you often have a path to a file and need to extract just the file name part from it.

For example, we can think of the path `data/fastq/sample1_R1.fastq` as consisting
of a directory part (`data/fastq/`) and a filename part (`sample1_R1.fastq`).

The **`basename` command** will extract just the filename part:

```sh
basename data/fastq/sample1_R1.fastq
```
```bash-out
sample1_R1.fastq
```

Optionally, it can remove a suffix too, most typically the file extension:

```bash
basename data/fastq/sample1_R1.fastq .fastq
```
```bash-out
sample1_R1
```

<br>

## Renaming files with loops

Sometimes, you need to rename many files in a systematic/repetitive way.
This is relatively common with omics data files,
as you will often have separate files for each sample,
and you may have many dozens of samples.

Manually renaming these one-by-one is tedious as well as extremely error-prone
and not-reproducible,
while doing this with code is a good example of a general task that you
can apply your coding skills to.
For example, maybe you have a few thousand photos that you want to rename in
a systematic way?

There are many different ways to rename many files in a programmatic way in the shell &ndash;
admittedly none as easy as one might have hoped.
Here, we'll use the `basename` command and a `for` loop.
`for` loops are a verbose method for tasks like renaming,
but are relatively intuitive and good to get practice with because you will use
them in other contexts throughout the course.

#### Creating a set of dummy files to work with

We will start with creating some dummy files that represent alignments
(the results of aligning reads in FASTQ files to a reference genome).
These are stored in `.sam` or `.bam` files.

To create many files at once, we will use a trick called "brace expansion"
(because this is not a commonly used technique, I will only explain it in the
optional bonus reading at the bottom of the page):

```bash
cd /fs/ess/PAS2880/users/$USER/week03
```

```bash
touch results/alignments/sample{01..50}.sam
```

Let's check the names of the files we created and how many there are:

```bash
ls results/alignments
```
```bash-out
results/alignments/sample01.sam
results/alignments/sample02.sam
results/alignments/sample03.sam
results/alignments/sample04.sam
results/alignments/sample05.sam
results/alignments/sample06.sam
# [...output truncated...]
```
```bash
ls results/alignments/ | wc -l
```
```bash-out
50
```

Now, let's say that we noticed these files somehow have the wrong extension:
they are saved as `.sam` (SAM files) but are really `.bam` (BAM files).
We'll have to rename them before moving on the next step in our analysis,
but it would be tedious (and error-prone! and not-reproducible!) to do this by hand.
We will therefore use a loop.

<hr style="height:1pt; visibility:hidden;" />

#### Renaming a single file using variables

To go step-by-step, I will start by showing how we could rename a single
file in the way that we would have to do this in a loop --- using variables.

We will actually make a _separate copy_ of the files in a separate directory,
just to be safe.

To start with, the original file name will be contained in a variable...

```bash
oldname=results/alignments/sample01.sam
```

...and we can also save the new name in a variable:

```bash
newname=results/alignments_bam/$(basename "$oldname" .sam).bam
```
  
Before actually renaming,
note the following trick with `echo` to just print the command instead of executing it ---
that can be a really useful way to check what you're doing is correct when you're
about to run a command you may be nervous about with variables:

```bash
echo mv -v "$oldname" "$newname"
```
```bash-out
mv -v results/alignments/sample01.sam results/alignments_bam/sample01.bam
```

Looks good? Then we remove `echo` and rename the file
(we're using the `-v` to make `mv` report what it's doing):

```bash
mv -v "$oldname" "$newname"
```
```bash-out
results/alignments/sample01.sam -> results/alignments_bam/sample01.bam
```

<hr style="height:1pt; visibility:hidden;" />

#### Looping over all files

Here's how we can loop over these files, saving each file name (one at a time)
in the variable `$oldname`:

```bash
for oldname in results/alignments/*.sam; do
    # ...
done
```

Next, we assign a new name for each file:
  
```sh
for oldname in results/alignments/*.sam; do
    newname=results/alignments_bam/$(basename "$oldname" .sam).bam
done
```

We build and check the renaming command:

```sh
for oldname in *.fastq; do
    newname=results/alignments_bam/$(basename "$oldname" .sam).bam
    echo cp -v "$oldname" "$newname"
done
```
```bash-out
cp -v results/alignments/sample01.sam results/alignments_bam/sample01.bam
cp -v results/alignments/sample02.sam results/alignments_bam/sample02.bam
cp -v results/alignments/sample03.sam results/alignments_bam/sample03.bam
cp -v results/alignments/sample04.sam results/alignments_bam/sample04.bam
# [...output truncated...]
```

Finally, we actually copy and rename by removing `echo`:

```bash
for oldname in *.fastq; do
    newname=results/alignments_bam/$(basename "$oldname" .sam).bam
    cp -v "$oldname" "$newname"
done
```
```bash-out
‘results/alignments/sample01.sam’ -> ‘results/alignments_bam/sample01.bam’
‘results/alignments/sample02.sam’ -> ‘results/alignments_bam/sample02.bam’
‘results/alignments/sample03.sam’ -> ‘results/alignments_bam/sample03.bam’
‘results/alignments/sample04.sam’ -> ‘results/alignments_bam/sample04.bam’
# [...output truncated...]
```

<br>

------

## Optional bonus reading

### Other shell wildcards

There are two more shell wildcards --- here is a complete overview of shell wildcards:

| Wildcard   | Matches |
|------------|---------------------------|
| *          | Any number of any character, including nothing |
| ?          | Any single character 
| [] and [^] | One or none (`^`) of the "character set" within the brackets   

<hr style="height:1pt; visibility:hidden;" />

Using the more restrictive wildcard **`?`** can be useful to prevent accidental
matches.
Here is an example of using the **`?`** wildcard to match both R1 and R2:

```bash
ls sample1_R?.fastq
```
```bash-out
sample1_R1.fastq  sample1_R2.fastq
```

<hr style="height:1pt; visibility:hidden;" />

The character class wildcard **`[]`** can be useful when wanting to include or
exclude multiple files among files with rather similar names.
For example, 
to match files for sample1 and sample2 using only a character class with **`[]`**:

- Method 1 --- List all possible characters (`1` and `2` in this case):

  ```sh
  ls sample[12]*
  ```
  ```bash-out
  sample1_R1.fastq  sample1_R2.fastq  sample2_R1.fastq  sample2_R2.fastq
  ```

- Method 2 -- Use a range like `[0-9]`, `[A-Z]`, `[a-z]`:

  ```bash
  ls sample[1-2]*
  ```
  ```bash-out
  sample1_R1.fastq  sample1_R2.fastq  sample2_R1.fastq  sample2_R2.fastq
  ```

- Method 3 -- Exclude the unwanted sample ID:

  ```bash
  ls sample[^3]*
  ```
  ```bash-out
  sample1_R1.fastq  sample1_R2.fastq  sample2_R1.fastq  sample2_R2.fastq
  ```

::: callout-warning
### Note: `[]` works on single character ranges only: 0-9 works but 10-13 does not.
:::

The examples so far may seem trivial, but you can use these techniques to easily
operate on selections among 100s or 1000s of files.

<hr style="height:1pt; visibility:hidden;" />

### Brace expansion

Whereas *wildcard expansion* looks for corresponding files and expands to whichever
files are present, **_brace expansion_** with `{}`, is another type of shell expansion
that expands to whatever you tell it to.

```bash
# First move up to zmays-snps
cd ../..
```

Use `..` within `{}` to indicate ranges of numbers or letters:

```bash
# Here we'll create 31 _dirs_ for different dates
mkdir -p data/obs/2025-09-{01..31}

ls data/obs
```
```bash-out
2025-09-01  2025-09-04  2025-09-07  2025-09-10  2025-09-13  2025-09-16  2025-09-19  2025-09-22  2025-09-25  2025-09-28  2025-09-31
2025-09-02  2025-09-05  2025-09-08  2025-09-11  2025-09-14  2025-09-17  2025-09-20  2025-09-23  2025-09-26  2025-09-29
2025-09-03  2025-09-06  2025-09-09  2025-09-12  2025-09-15  2025-09-18  2025-09-21  2025-09-24  2025-09-27  2025-09-30
```

```bash
# Here we'll create 6 empty _files_
touch results/figures/fig-1{A..F}.png

ls results/figures
```
```bash-out
fig-1A.png  fig-1B.png  fig-1C.png  fig-1D.png  fig-1E.png  fig-1F.png
```

<hr style="height:1pt; visibility:hidden;" />

Finally, you can also use a comma-separated list, and multiple brace expansions ---
with the latter, you will get _all combinations_ among values in the expansions:

```sh
mkdir -p data/obs2/treatment-{Kr,Df,Tr}_temp-{lo,med,hi}

ls data/obs2
```
```bash-out
treatment-Df_temp-hi   treatment-Kr_temp-hi   treatment-Tr_temp-hi
treatment-Df_temp-lo   treatment-Kr_temp-lo   treatment-Tr_temp-lo
treatment-Df_temp-med  treatment-Kr_temp-med  treatment-Tr_temp-med
```

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Bonus exercise: More file matching

1. Move back into `data/fastq/` and remove all (remaining) files in there in one go.

<details><summary>Click for the solution</summary>

```sh
cd data/fastq/   # Assuming you were still in /fs/ess/PAS2880/users/$USER/week03/zmays-snps

# (You don't have to use the -v flag)
rm -v *fastq
```
```bash-out
removed ‘sample3_R1.fastq’
removed ‘sample3_R2.fastq’
```

</details>

2. Using *brace expansion* and the **`touch`** command,
  create empty `R1` and `R2` FASTQ files for 100 samples with IDs from `001` to `100`:
  `sample<ID>_R1.fastq` and `sample<ID>_R2.fastq`.

<details><summary>Click for the solution</summary>

```bash
touch sample{001..100}_R{1,2}.fastq

ls
```
```bash-out
sample001_R1.fastq  sample026_R1.fastq  sample051_R1.fastq  sample076_R1.fastq
sample001_R2.fastq  sample026_R2.fastq  sample051_R2.fastq  sample076_R2.fastq
sample002_R1.fastq  sample027_R1.fastq  sample052_R1.fastq  sample077_R1.fastq
sample002_R2.fastq  sample027_R2.fastq  sample052_R2.fastq  sample077_R2.fastq
sample003_R1.fastq  sample028_R1.fastq  sample053_R1.fastq  sample078_R1.fastq
sample003_R2.fastq  sample028_R2.fastq  sample053_R2.fastq  sample078_R2.fastq
sample004_R1.fastq  sample029_R1.fastq  sample054_R1.fastq  sample079_R1.fastq
sample004_R2.fastq  sample029_R2.fastq  sample054_R2.fastq  sample079_R2.fastq
sample005_R1.fastq  sample030_R1.fastq  sample055_R1.fastq  sample080_R1.fastq
sample005_R2.fastq  sample030_R2.fastq  sample055_R2.fastq  sample080_R2.fastq
sample006_R1.fastq  sample031_R1.fastq  sample056_R1.fastq  sample081_R1.fastq
sample006_R2.fastq  sample031_R2.fastq  sample056_R2.fastq  sample081_R2.fastq
sample007_R1.fastq  sample032_R1.fastq  sample057_R1.fastq  sample082_R1.fastq
sample007_R2.fastq  sample032_R2.fastq  sample057_R2.fastq  sample082_R2.fastq
sample008_R1.fastq  sample033_R1.fastq  sample058_R1.fastq  sample083_R1.fastq
sample008_R2.fastq  sample033_R2.fastq  sample058_R2.fastq  sample083_R2.fastq
sample009_R1.fastq  sample034_R1.fastq  sample059_R1.fastq  sample084_R1.fastq
sample009_R2.fastq  sample034_R2.fastq  sample059_R2.fastq  sample084_R2.fastq
sample010_R1.fastq  sample035_R1.fastq  sample060_R1.fastq  sample085_R1.fastq
sample010_R2.fastq  sample035_R2.fastq  sample060_R2.fastq  sample085_R2.fastq
sample011_R1.fastq  sample036_R1.fastq  sample061_R1.fastq  sample086_R1.fastq
sample011_R2.fastq  sample036_R2.fastq  sample061_R2.fastq  sample086_R2.fastq
sample012_R1.fastq  sample037_R1.fastq  sample062_R1.fastq  sample087_R1.fastq
sample012_R2.fastq  sample037_R2.fastq  sample062_R2.fastq  sample087_R2.fastq
sample013_R1.fastq  sample038_R1.fastq  sample063_R1.fastq  sample088_R1.fastq
sample013_R2.fastq  sample038_R2.fastq  sample063_R2.fastq  sample088_R2.fastq
sample014_R1.fastq  sample039_R1.fastq  sample064_R1.fastq  sample089_R1.fastq
sample014_R2.fastq  sample039_R2.fastq  sample064_R2.fastq  sample089_R2.fastq
sample015_R1.fastq  sample040_R1.fastq  sample065_R1.fastq  sample090_R1.fastq
sample015_R2.fastq  sample040_R2.fastq  sample065_R2.fastq  sample090_R2.fastq
sample016_R1.fastq  sample041_R1.fastq  sample066_R1.fastq  sample091_R1.fastq
sample016_R2.fastq  sample041_R2.fastq  sample066_R2.fastq  sample091_R2.fastq
sample017_R1.fastq  sample042_R1.fastq  sample067_R1.fastq  sample092_R1.fastq
sample017_R2.fastq  sample042_R2.fastq  sample067_R2.fastq  sample092_R2.fastq
sample018_R1.fastq  sample043_R1.fastq  sample068_R1.fastq  sample093_R1.fastq
sample018_R2.fastq  sample043_R2.fastq  sample068_R2.fastq  sample093_R2.fastq
sample019_R1.fastq  sample044_R1.fastq  sample069_R1.fastq  sample094_R1.fastq
sample019_R2.fastq  sample044_R2.fastq  sample069_R2.fastq  sample094_R2.fastq
sample020_R1.fastq  sample045_R1.fastq  sample070_R1.fastq  sample095_R1.fastq
sample020_R2.fastq  sample045_R2.fastq  sample070_R2.fastq  sample095_R2.fastq
sample021_R1.fastq  sample046_R1.fastq  sample071_R1.fastq  sample096_R1.fastq
sample021_R2.fastq  sample046_R2.fastq  sample071_R2.fastq  sample096_R2.fastq
sample022_R1.fastq  sample047_R1.fastq  sample072_R1.fastq  sample097_R1.fastq
sample022_R2.fastq  sample047_R2.fastq  sample072_R2.fastq  sample097_R2.fastq
sample023_R1.fastq  sample048_R1.fastq  sample073_R1.fastq  sample098_R1.fastq
sample023_R2.fastq  sample048_R2.fastq  sample073_R2.fastq  sample098_R2.fastq
sample024_R1.fastq  sample049_R1.fastq  sample074_R1.fastq  sample099_R1.fastq
sample024_R2.fastq  sample049_R2.fastq  sample074_R2.fastq  sample099_R2.fastq
sample025_R1.fastq  sample050_R1.fastq  sample075_R1.fastq  sample100_R1.fastq
sample025_R2.fastq  sample050_R2.fastq  sample075_R2.fastq  sample100_R2.fastq
```

</details>

------

3. **_Bonus:_** Count the number of "`R1`" files by first using `ls` with a globbing
  pattern that only selects R1 files, and then piping the `ls` output into **`wc -l`**.

<details><summary>Click for the solution</summary>

```bash
# wc -l will count the number of lines, i.e. the number of files
# (Note that this works properly even though raw ls output may
# put multiple files on 1 line.)
ls *R1*fastq | wc -l
```
```bash-out
100
```

</details>

4. **_Bonus:_** Copy all files *except the two for "`sample100`"* into a new
  directory called `selection` --- use a wildcard to do the move with a single command.
  (You will first need to create the new dir separately.)

<details><summary>Click for the solution</summary>

First create the `selection` dir:

```sh
mkdir selection
```

Method 1 --- Exclude sample numbers starting with a 1:

```bash
cp sample[^1]* selection/
```

Method 2 --- Other way around; include sample numbers starting with a 0:

```bash
cp sample0* selection/ 
```

</details>

:::

<br>
