---
title: "Week 3 exercises: Working with files in the Unix shell"
pagetitle: "PRACS25: Week 3 exercises"
number-sections: false
date: 2025-09-08
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
other-links:
  - text: "Week 3 overview"
    icon: book
    href: w3_overview.html
  - text: "w3-1: Shell files I"
    icon: bookmarks
    href: w3_1_shellfiles.html
  - text: "w3-2: Shell files II"
    icon: bookmarks
    href: w3_2_shellfiles.html
  - text: "Bonus: Unix data tools II"
    icon: book
    href: ../bonus/shell-data.html
  - text: "Bonus: Misc. advanced shell"
    icon: book
    href: ../bonus/shell.html
bibliography: ../references.bib
---

---------

<br>

### Introduction

In these exercises, you will practice with Unix commands,
especially those that operate on files as seen in this week's classes.

Before you start, I would recommend to reread the pages for this week's sessions
([session 1](./w3_1_shellfiles.qmd); [session 2](./w3_2_shellfiles.qmd)).
At the very least, make sure you have read the contents of all the callout boxes
on those pages, many of which we likely skipped over in class!

#### Setting up

- Start a VS Code session through OSC OnDemand in the folder
  `/fs/ess/PAS2880/users/$USER`.
- Create and use a Markdown file to keep notes on what you're doing.
- You'll be using the @garrigós2023 data files,
  which you should have in your personal dir.

<details><summary>_Click here for instructions if you need to (re)download these files._</summary>
```bash
# Make sure you're in your personal dir:
cd /fs/ess/PAS2880/users/$USER
  
git clone https://github.com/jelmerp/garrigos-data
```
</details>

<hr style="height:1pt; visibility:hidden;" />

## Exercise 1: Moving, copying and removing

_Use Unix commands to complete all the exercises below._

1. Create a dir `week03/ex1` within your personal dir^[
   `/fs/ess/PAS2880/users/$USER/`], and navigate there.
   _Use this as the working dir for all followings questions in this exercise,_
   _so avoid navigating anywhere else._

2. Create a new dir `seqs`,
   and use the below command to create some dummy FASTQ files in there.
   Then, check the result with `ls` and get a count of the number of files you
   created (do so using code!).

   ```bash
   touch seqs/sample{01..25}_R{1,2}.fastq
   ```

3. Copy the files for samples `01` through `09` into your working dir with a
   single command.

4. Remove the files you just copied and when doing so,
   make the command report what it's doing (i.e. make it verbose).

5. Move all R1 files into a dir `seqs_R1`, and then rename `seqs`,
   which should now only contain R2 files, to `seqs_R1`.

6. Copy the Garrigos et al. metadata file into your current working dir,
   giving the copy the name `garrigos_metadata.tsv`.

<hr style="height:1pt; visibility:hidden;" />

## Exercise 2: Exploring the GTF annotation file

_Before you start, make you sure you have read the box_
_"GTF file info for this week's exercises" at the bottom of_
_[the page for this week's second session](./w3_2_shellfiles.qmd)._

1. Create a dir `week03/ex2` within your personal dir^[
   `/fs/ess/PAS2880/users/$USER/`], and navigate there.

2. Copy the genome annotation file `garrigos-data/ref/GCF_016801865.2.gtf.gz`
   to a file called `annot.gtf.gz` inside your `ex2` working dir.

3. Check the size of the `annot.gtf.gz` file.
   Then, unzip (decompress) the GTF file with the `gunzip` command as shown below.
   Finally, check the size of the resulting `annot.gtf` file.
   How large is the size difference between the compressed and uncompressed files?

   ```bash
   gunzip annot.gtf.gz
   ```

4. How many lines does the GTF file contain?

5. The total number of features in a GTF file is simply the number of lines in
   its table.
   
   - Combine `grep -v` and `wc -l` to count the number of features.
     _(First, you may want to take a peek at the file with `less -S` to decide on_
     _a search pattern for `grep`.)_
   
   - Comparing the linecount from this and the previous exercise,
     does the difference reflect the number of header lines?
   
   - If not, can you figure out which other line(s) contain the pattern you used
     with `grep` above?
     _(Review the "Additional `grep` tips" box in_
     _[the section on `grep`](week03/w3_2_shellfiles.html#grep-to-print-lines-that-match-a-pattern)_
     _to find an option that might help you make sense of that.)_

6. How many distinct "sequences" (chromosome/scaffolds/contigs) are represented
   in the annotation?
   
   <details><summary>_Click here for a hint_</summary>
   In this and all following questions, you'll only want to consider the table
   part of the file, so you should start your commands with `grep -v` as above.
   </details>

7. Store a list of these distinct sequences in the GTF in a file `scaffolds.txt`.

8. Print a "count table"
   (like we did towards the end of [this section](./w3_2_shellfiles.html#combining-cut-sort-and-uniq-to-create-a-list))
   of feature types in the annotation:
   i.e. for each feature type, generate a count representing the number of times it occurs.
   This will allow you to see, for example, how many genes have been annotated in this genome.

9. For a gene of interest,
   you may wonder how many exons and other annotated features it has.
   GTF files have an implicit hierarchical structure,
   where e.g. each exon row contains a reference to the gene it is a part of
   (its "parent") in the final column.
   For gene `LOC120427725`, print a count table of its feature types.
   _(You can assume that this gene's name does not occur in any lines_
   _describing features that are not part of the gene.)_

10. **_Bonus_**: Produce a 3-column table with the sequence name, start position,
    and end position of each _distinct_ start codon in the GTF file.
    Store that table in a file `start_codons.tsv`.
    _(You can assume that the string `start_codon` occurs only in the third column,_
    _so that all lines with that string contain start codon features.)_

11. **_Bonus_**: In this genome, which sequence (chromosome/scaffold/contig)
    appears to be the largest one?

    <details><summary>_Click here for a hint_</summary>
    This information is not directly contained in this GTF file,
    but if you are able find the highest number in the (start or) end coordinate
    column, and check which sequence that is on, you should get the correct answer.
    
    To do this, you need to first `cut` the relevant columns, and then `sort`
    specifically by the coordinate column (using the `-k` option).
    </details>

12. **_Bonus_**: Count the number of small nuclear RNAs (`snRNA`) in the annotation.
    You'll want a "gene"-level count
    (i.e. a count of the number of `gene` features annotated as `snRNA`),
    but because the word "snRNA" also occurs for other features,
    the search pattern `snRNA` would not work.
    An initial `grep` search would help to find a good final search pattern ---
    to spare you that trouble, it should be: `gene_biotype "snRNA"`.
    But this poses another challenge: the pattern contains double quotes (`"`),
    which we've been using to indicate where the search pattern begins and ends.

    <details><summary>_Click here for a hint_</summary>
    Use single quotes (`'`) instead of double quotes around the entire pattern.
    </details>
    
<hr style="height:1pt; visibility:hidden;" />

## Exercise 3: Exploring the FASTQ files

_For all questions below except the Bonus question,_
_use the FASTQ file `ERR10802863_R1.fastq.gz`._
_Also, keep in mind that the file is compressed, and operate on the compressed_
_file directly (don't decompress it)._

1. Navigate into the dir with FASTQ files from the Garrigos et al. data.

2. How many reads does the file contain?

   <details><summary>_Click here for a hint_</summary>
   A linecount of the compressed file will **not** give you the correct answer.
   Therefore, use the `zcat <file.gz> | <...>` idiom instead.
   
   Also, remember that one read covers 4 lines and that FASTQ files only contain
   lines with reads.
   </details>

3. How many reads contain the sequence `ACGT`?
   _(You can assume that this does not occur in the sequence quality lines.)_
   
4. Using the read length information in the FASTQ header lines,
   print a count table of read lengths.
   
   <details><summary>_Click here for some hints_</summary>
   
   - First you need to select only the header lines.
     When doing so, you can assume that no `@`s occur in the other lines.
   
   - Next, you'll need to extract / single out the read length numbers in these
     header lines, which are in the format `length=74`.
     One way to do this is a fun trick:
     by using `=` as the delimiter (`-d` option) to `cut`!
   </details>
   
5. Count the number of reads that contain at least 10 consecutive `N`s,
   i.e. uncalled bases.
   _(You can assume that stretches of N's do not occur in the sequence quality lines.)_
  
6. Compare the number you got in the previous question,
   with the number of 35-bp reads from the question before that.
   What does this seem to tell you?
   To confirm, can you check what a sample of 35-bp reads look like?
   
   <details><summary>_Click here for a hint_</summary>
   With `grep -A1`, you can print the line _after_ each match.
   This will allow you to see the sequences in the 35-bp reads.
   Pipe to `less` or `head` so you don't get thousands of lines printed to screen.
   </details>

7. **_Bonus_**: Can you find out, with a single command,
   what the total number of reads across all R1 files is?

   <details><summary>_Click here for a hint_</summary>
   Use `zcat` with a globbing (file selection) pattern with a `*` to operate on
   all R1 files at once -- then pipe that into the familiar line counting command.
   </details>
   
<br>

## Solutions

### Exercise 1

<details><summary>**1.** Create a new dir and navigate there</summary>

```bash
# (You should already be in /fs/ess/PAS2880/users/$USER/)
cd /fs/ess/PAS2880/users/$USER/week03
mkdir ex2
cd ex2
```
</details>

<details><summary>**2.** Create a dir with dummy sequence files</summary>

- Create the dir:

  ```bash
  mkdir seqs
  ```

- Create the dummy files:

  ```bash
  touch seqs/sample{01..25}_R{1,2}.fastq
  ```
  
  This uses a construct called **brace expansion**, which we won't cover in class.
  If you want to learn more, check [this section](../bonus/shell.qmd#brace-expansion) 
  on the optional reading page "Miscellaneous advances shell".

- Check the result:

  ```bash
  ls seqs
  ```
  ```bash-out
  sample01_R1.fastq  sample03_R1.fastq  sample05_R1.fastq  sample07_R1.fastq  sample09_R1.fastq  sample11_R1.fastq  sample13_R1.fastq  sample15_R1.fastq  sample17_R1.fastq  sample19_R1.fastq  sample21_R1.fastq  sample23_R1.fastq  sample25_R1.fastq
sample01_R2.fastq  sample03_R2.fastq  sample05_R2.fastq  sample07_R2.fastq  sample09_R2.fastq  sample11_R2.fastq  sample13_R2.fastq  sample15_R2.fastq  sample17_R2.fastq  sample19_R2.fastq  sample21_R2.fastq  sample23_R2.fastq  sample25_R2.fastq
sample02_R1.fastq  sample04_R1.fastq  sample06_R1.fastq  sample08_R1.fastq  sample10_R1.fastq  sample12_R1.fastq  sample14_R1.fastq  sample16_R1.fastq  sample18_R1.fastq  sample20_R1.fastq  sample22_R1.fastq  sample24_R1.fastq
sample02_R2.fastq  sample04_R2.fastq  sample06_R2.fastq  sample08_R2.fastq  sample10_R2.fastq  sample12_R2.fastq  sample14_R2.fastq  sample16_R2.fastq  sample18_R2.fastq  sample20_R2.fastq  sample22_R2.fastq  sample24_R2.fastq
  ```

- Count the number of files:

  ```bash
  ls seqs | wc -l
  ```
  ```bash-out
  50
  ```

  Note that this gives the correct count even though when printed to screen,
  `ls` output typically used multiple columns and therefore shows more than one
  file per line.
  
  In contrast,
  the count from `ls -l` is _not_ correct, since its output includes a header line:
  
  ```bash
  ls -l seqs | wc -l
  ```
  ```bash-out
  51
  ```

</details>

<details><summary>**3.** Copy the files for samples 01 through 09 into your working dir with a single command</summary>

- Copy the files --
  recall to use `.` to indicate your current working dir as the destination path.

  ```bash
  cp seqs/sample0* .
  ```

- Let's check the result:

  ```bash
  ls
  ```
  ```bash-out
  sample01_R1.fastq  sample02_R1.fastq  sample03_R1.fastq  sample04_R1.fastq  sample05_R1.fastq  sample06_R1.fastq  sample07_R1.fastq  sample08_R1.fastq  sample09_R1.fastq  seqs
sample01_R2.fastq  sample02_R2.fastq  sample03_R2.fastq  sample04_R2.fastq  sample05_R2.fastq  sample06_R2.fastq  sample07_R2.fastq  sample08_R2.fastq  sample09_R2.fastq
  ```

</details>

<details><summary>**4.** Remove the files you just copied</summary>

```bash
rm -v sample0*
```
```bash-out
removed 'sample01_R1.fastq'
removed 'sample01_R2.fastq'
removed 'sample02_R1.fastq'
removed 'sample02_R2.fastq'
removed 'sample03_R1.fastq'
removed 'sample03_R2.fastq'
removed 'sample04_R1.fastq'
removed 'sample04_R2.fastq'
removed 'sample05_R1.fastq'
removed 'sample05_R2.fastq'
removed 'sample06_R1.fastq'
removed 'sample06_R2.fastq'
removed 'sample07_R1.fastq'
removed 'sample07_R2.fastq'
removed 'sample08_R1.fastq'
removed 'sample08_R2.fastq'
removed 'sample09_R1.fastq'
removed 'sample09_R2.fastq'
```

</details>

<details><summary>**5.** Move all R1 files into a dir `seqs_R1` and rename `seqs`</summary>

```bash
# Create the new dir:
mkdir seqs_R1

# Move the R1 files into the new dir:
mv seqs/*R1.fastq seqs_R1

# Rename the old dir:
mv seqs seqs_R2

# Check the result:
tree -C
```
```bash-out
.
├── seqs_R1
│   ├── sample01_R1.fastq
│   ├── sample02_R1.fastq
│   ├── sample03_R1.fastq
│   ├── sample04_R1.fastq
│   ├── sample05_R1.fastq
│   ├── sample06_R1.fastq
│   ├── sample07_R1.fastq
│   ├── sample08_R1.fastq
│   ├── sample09_R1.fastq
│   ├── sample10_R1.fastq
│   ├── sample11_R1.fastq
│   ├── sample12_R1.fastq
│   ├── sample13_R1.fastq
│   ├── sample14_R1.fastq
│   ├── sample15_R1.fastq
│   ├── sample16_R1.fastq
│   ├── sample17_R1.fastq
│   ├── sample18_R1.fastq
│   ├── sample19_R1.fastq
│   ├── sample20_R1.fastq
│   ├── sample21_R1.fastq
│   ├── sample22_R1.fastq
│   ├── sample23_R1.fastq
│   ├── sample24_R1.fastq
│   └── sample25_R1.fastq
└── seqs_R2
    ├── sample01_R2.fastq
    ├── sample02_R2.fastq
    ├── sample03_R2.fastq
    ├── sample04_R2.fastq
    ├── sample05_R2.fastq
    ├── sample06_R2.fastq
    ├── sample07_R2.fastq
    ├── sample08_R2.fastq
    ├── sample09_R2.fastq
    ├── sample10_R2.fastq
    ├── sample11_R2.fastq
    ├── sample12_R2.fastq
    ├── sample13_R2.fastq
    ├── sample14_R2.fastq
    ├── sample15_R2.fastq
    ├── sample16_R2.fastq
    ├── sample17_R2.fastq
    ├── sample18_R2.fastq
    ├── sample19_R2.fastq
    ├── sample20_R2.fastq
    ├── sample21_R2.fastq
    ├── sample22_R2.fastq
    ├── sample23_R2.fastq
    ├── sample24_R2.fastq
    └── sample25_R2.fastq

2 directories, 50 files
```

</details>

<details><summary>**6.** Copy the Garrigos et al. metadata file into your current working dir</summary>

```bash
cp ../../garrigos-data/meta/metadata.tsv garrigos_metadata.tsv
```
</details>

<hr style="height:1pt; visibility:hidden;" />

### Exercise 2

<details><summary>**1.** Create a new dir and navigate there</summary>

```bash
# (You should already be in /fs/ess/PAS2880/users/$USER/)
cd /fs/ess/PAS2880/users/$USER/week03
mkdir ex2
cd ex2
```
</details>

<details><summary>**2.** Copy the genome annotation file `garrigos-data/ref/GCF_016801865.2.gtf.gz`</summary>

```bash
cp ../ref/GCF_016801865.2.gtf.gz annot.gtf.gz
```
</details>

<details><summary>**3.** Unzip (decompress) the GTF file</summary>

- Check the file size:
  
  ```bash
  ls -lh
  ```
  ```bash-out
  -rw-rw----+ 1 jelmer PAS0471 5.1M Jul 14 18:55 annot.gtf.gz
  ```
  
- Unzip:

  ```bash
  gunzip annot.gtf.gz
  ```

- Check the file size (and name) again:
  
  ```bash
  ls -lh
  ```
  ```bash-out
  -rw-rw----+ 1 jelmer PAS0471 123M Jul 14 18:55 annot.gtf
  ```
  
- That's a pretty big difference, from 5.1 Mb to 123 Mb!
  The amount of space saved by file compression varies a lot and depends on the
  amount of repetition in the uncompressed file.
  GTF files are highly repetitive, so relatively much space can be saved.

</details>

<details><summary>**4.** How many lines does the GTF file contain?</summary>

A simple line count tells you that the file has 408,402 lines:

```bash
wc -l annot.gtf 
```
```bash-out
408402 annot.gtf 
```
</details>

<details><summary>**5.** Count the number of line in the GTF table.</summary>

- Since the header lines contain a `#`,
  you'll want to exclude those and then count the remaining number of lines:

  ```bash
  grep -v "#" annot.gtf | wc -l
  ```
  ```bash-out
  408397
  ```

- The file has only 4 header lines, while the line count has decreased by 5
  (from 408402 to 408397). So, which other line in the file has a `#`?
  
  Use the `-n` option to `grep` to print line numbers along with each match:

  ```bash
  grep -n "#" annot.gtf
  ```
  ```bash-out
  1:#gtf-version 2.2
  2:#!genome-build TS_CPP_V2
  3:#!genome-build-accession NCBI_Assembly:GCF_016801865.2
  4:#!annotation-source NCBI RefSeq GCF_016801865.2-RS_2022_12
  408402:###
  ```

  So, it looks like the very last line also has a `#`:
  it is simply `###`, functioning as an end-of-file marker.

</details>

<details><summary>**6.** How many distinct sequences are represented in the annotation?</summary>

- Make sure to first exclude the header lines with `grep -v`
- The first column contains the sequence name (`cut -f 1`)
- To only keep distinct sequences, use `sort | uniq`
- To get a count of the resulting list of distinct sequences, use `wc -l`.

```bash
grep -v "#" annot.gtf | cut -f 1 | sort | uniq | wc -l
```
```bash-out
167
```

</details>

<details><summary>**7.** Store a list of distinct sequences in the GTF in a file `scaffolds.txt`.</summary>

- Same command as above,
  but we get rid of `wc -l` and instead redirect the output of `uniq` to a file:

  ```bash
  grep -v "#" annot.gtf | cut -f 1 | sort | uniq > scaffolds.txt
  ```

- Take a peek at `scaffolds.txt` for a sanity check:

  ```bash
  head -n 3 scaffolds.txt
  ```
  ```bash-out
  NC_015079.1
  NC_068937.1
  NC_068938.1
  ```

</details>

<details><summary>**9.** Produce a "count table" of feature types in the annotation</summary>

- The feature type is in the third column (`cut -f 3`)
- To produce a count table, use the `sort | uniq -c` idiom.

```bash
grep -v "#" annot.gtf | cut -f 3 | sort | uniq -c
```
```bash-out
 141444 CDS
 166177 exon
  19673 gene
  25864 start_codon
  25892 stop_codon
  29347 transcript
```
</details>

<details><summary>**9.** Print a count table of annotated features for gene `LOC120427725`</summary>

```bash
grep "LOC120427725" annot.gtf | cut -f 3 | sort | uniq -c
```
```bash-out
     15 CDS
     20 exon
      1 gene
      3 start_codon
      3 stop_codon
      3 transcript
```

</details>

<details><summary>**10.** Print a start codon genomic coordinate table</summary>

- After `grep`ing for `start_codon`,
  you need to select (`cut`) the first, fourth, and fifth columns.

- Taking a peek at the output, it appears that start codons may duplicated:

  ```bash
  grep "start_codon" annot.gtf | cut -f 1,4,5 | head -n 5
  ```
  ```bash-out
  NC_068937.1     70143   70145
  NC_068937.1     70143   70145
  NC_068937.1     70143   70145
  NC_068937.1     49062   49064
  NC_068937.1     160735  160737
  ```
  
  This is because distinct transcripts of a gene (producing different isoforms)
  may share the same start codon.
  
- To get rid of the duplicates, use `sort | uniq` ---
  and then we can redirect the output to `start_codons.tsv`:
  
  ```bash
  grep "start_codon" annot.gtf | cut -f 1,4,5 | sort | uniq > start_codons.tsv
  ```

- Take a peek at the output file for a sanity check:

  ```bash
  head -n 5 start_codons.tsv
  ```
  ```bash-out
  NC_015079.1     10427   10429
  NC_015079.1     12600   12602
  NC_015079.1     211     213
  NC_015079.1     3055    3057
  NC_015079.1     3898    3900
  ```
</details>

<details><summary>**11.** Which sequence (scaffold) appears to be the largest one?</summary>

- You'll want to reverse (`-r`) numerically (`-n`) sort by the (fourth or) fifth column.
- To only get the feature with the largest end position, add `head -n 1`
- (We could add `| cut -f 1` to only get the sequence name, not the entire line.)

```bash
grep -v "#" annot.gtf | sort -k5nr | head -n 1
```
```bash-out
NC_068938.1     Gnomon  exon    224093433       224093803       .       +       .       gene_id "LOC120429120"; transcript_id "XM_039594310.2"; db_xref "GeneID:120429120"; experiment "COORDINATES: polyA evidence [ECO:0006239]"; gene "LOC120429120"; model_evidence "Supporting evidence includes similarity to: 6 Proteins"; product "caprin homolog"; transcript_biotype "mRNA"; exon_number "4"; 
```

- So the largest sequence appears to be `NC_068938.1`.

</details>

<details><summary>**12.** Count the number of snRNAs in the annotation.</summary>

Because the search pattern itself contains double quotes (`"`),
the easiest way out is to use **single quotes** (`'`) around it:

```bash
grep -c 'gene_biotype "snRNA"' annot.gtf
```
```bash-out
58
```
</details>

<hr style="height:1pt; visibility:hidden;" />

### Exercise 3

<details><summary>**1.** Navigate into the dir with FASTQ files</summary>

```bash
# Assuming you are in `garrigos-data/ref` after the previous exercise
cd ../fastq

# Or:
# cd /fs/ess/PAS2880/users/$USER/garrigos-data/fastq
```
</details>

<details><summary>**2.** How many reads does the file contain?</summary>

- As the hint suggested, use `zcat <file> | wc -l` to get an "uncompressed count":

```bash
zcat ERR10802863_R1.fastq.gz | wc -l
```
```bash-out
2000000
```

- This means that the number of reads is 2,000,000 / 4  =  500,000.

- To confirm -- a direct line count on the compressed file gives the wrong answer!

```bash
wc -l ERR10802863_R1.fastq.gz
```
```bash-out
101139
```

</details>

<details><summary>**3.** How many reads contain the sequence `ACGT`?</summary>

- Either use `zcat <file> | grep`:

  ```bash
  zcat ERR10802863_R1.fastq.gz | grep -c "ACGT"
  ```
  ```bash-out
  100465
  ```

- Or `zgrep`:

  ```bash
  zgrep -c "ACGT" ERR10802863_R1.fastq.gz
  ```
  ```bash-out
  100465
  ```
  
</details>

<details><summary>**4.** Print a count table of read lengths</summary>

- First select only header lines with `grep "@"`.
- Then use `=` as the `cut` delimiter and select the second "column".
- Finally, use the by now familiar `sort | uniq -c` idiom to create the count table.

```bash
zcat ERR10802863_R1.fastq.gz | grep "@" | cut -d "=" -f 2 | sort | uniq -c
```
```bash-out
  32678 35
      4 36
      7 37
      2 38
      3 39
      4 40
      4 41
      3 42
      6 43
      6 44
      4 45
      8 46
      6 47
      3 48
      2 49
     11 50
     14 51
     14 52
     12 53
     11 54
     18 55
     13 56
     13 57
     17 58
     21 59
     27 60
     28 61
     28 62
     47 63
     90 64
     61 65
     49 66
     78 67
    276 68
    620 69
   1962 70
   8483 71
  28617 72
 123453 73
 303297 74
```

</details>

<details><summary>**5.** Count the number of reads that contain at least 10 consecutive `N`s</summary>

```bash
zcat ERR10802863_R1.fastq.gz | grep -c "NNNNNNNNNN"
```
```bash-out
32612
```

</details>

<details><summary>**6.** What's up with the 35-bp reads?</summary>

The number of reads with at least 10 consecutive `N`s (32,612 -- previous question)
is rather close to the number of 35-bp reads (32,678 -- question before that).
Might nearly all 35-bp reads consist of mostly or only `N`s?

One way to see a sample of 35-bp reads is by using `grep`s `-A` option to also
print the line _after_ each match:

```bash
zcat ERR10802863_R1.fastq.gz | grep -A1 "length=35" | head -n 20
```
```bash-out
@ERR10802863.11918285 11918285 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.6436756 6436756 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.31676291 31676291 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.3768169 3768169 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.4421608 4421608 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.4569065 4569065 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
--
@ERR10802863.14070693 14070693 length=35
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

They do!
Note that this makes some sense because the target length of these reads is 75 bp.
Read length variation in Illumina reads is usually very minor, with >99% of reads
typically being up to 1 or bases from the target base length.
As such, these 35-bp reads are unusual to begin with, and it may not be entirely
surprising that they are of very poor quality.

</details>

<details><summary>**7.** What is the total number of reads across all R1 files?</summary>

We can use `zcat` with a `*` wildcard pattern to print the contents of all R1
files, and simply perform a line count on that:

```bash
zcat *_R1.fastq.gz | wc -l
```
```bash-out
44000000
```

So, the total number of reads is 44,000,000 / 4 = 11,000,000.
This makes sense because we have 22 R1 FASTQ files, each of which has 500 k reads.

</details>