project:
  type: website
  output-dir: docs

website:
  title: "PRACS-AU25"
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#666666"
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data and OSC"
          href: week01/w1_overview.qmd
        - text: "Week 2: Project organization and Unix shell basics"
          href: week02/w2_overview.qmd 
        - text: "Week 3: Working with files in the Unix shell [TBA]"
        - text: "Week 4: Version control with Git and GitHub [TBA]"
        - text: "Week 5: Data and software management at OSC [TBA]"
        - text: "Week 6: Shell scripts and CLI tools [TBA]"
        - text: "Week 7: Slurm batch jobs at OSC [TBA]"
        - text: "Week 8: Using generative AI when coding [TBA]"
        - text: "Week 9: Automated pipelines with Nextflow [TBA]"
        - text: "Week 10: Building Nextflow pipelines [TBA]"
        - text: "Week 11: R -- basics and Quarto [TBA]"
        - text: "Week 12: R -- data wrangling [TBA]"
        - text: "Week 13: R -- data visualization [TBA]"
        - text: "Week 14: R -- omics data [TBA]"
        - text: "Week 15: Nextflow nf-core pipelines [TBA]"
      - text: "Exercises"
        menu:
        - text: "Week 3: Unix shell [TBA]"
        - text: "Week 5: OSC data and software [TBA]"
        - text: "Week 7: Slurm batch jobs [TBA]"
        - text: "Week 9: Nextflow [TBA]"
        - text: "Week 11: R basics [TBA]"
        - text: "Week 12: R data wrangling [TBA]"
        - text: "Week 13: R data visualization [TBA]"
        - text: "Week 13: Nextflow pipelines [TBA]"
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "GRADED"
        - text: "1. Markdown and Unix shell basics (Week 2)"
          href: week02/w2_ga.qmd
        - text: "2. Version control with Git and GitHub (Week 4) [TBA]"
        - text: "3. Shell scripting (Week 6) [TBA]"
        - text: "4. Slurm batch jobs (Week 8) [TBA]"
        - text: "5. Nextflow (Week 10) [TBA]"
        - text: "6. R (Week 14) [TBA]"
        - text: "----------"
        - text: "UNGRADED"
        - text: "Week 1: Pre-course survey"
        - text: "Week 1: OSC account setup"
          href: week01/w1_ua_osc-setup.qmd
        - text: "Week 4: GitHub account setup [TBA]"
        - text: "Week 16: Post-course survey [TBA]"
      - text: "Final project"
        menu:
        - text: "General info [TBA]"
        - text: "Checkpoint I: Proposal [TBA]"
        - text: "Checkpoint II: Oral presentation [TBA]"
        - text: "Checkpoint III: Final submission [TBA]"
    right:
      - text: Other
        menu:
        - text: "Course glossary [TBA]"
        - text: "References"
          href: ref/refs.qmd
        - text: "Further learning resources [TBA]"
        - text: "----------"
        - text: "OPTIONAL SELF-STUDY CONTENT:"
        - text: "Unix data tools (wk3) [TBA]"
        - text: "Misc. Unix shell (wk3) [TBA]"
        - text: "Git (wk4) [TBA]"
        - text: "Software management with Conda (wk5) [TBA]"
        - text: "SSH connection (wk5) [TBA]"
        - text: "OSC file transfer (wk5) [TBA]"
        - text: "Shell scripting and looping (wk6) [TBA]"
        - text: "Slurm batch jobs (wk7) [TBA]"
        - text: "----------"
        - text: TOPIC OVERVIEWS
      - text: About
        href: ref/about.qmd
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/187770
        aria-label: "The CarmenCanvas site for this course"
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
        aria-label: "The OSC OnDemand website"
    tools:
      - icon: github
        aria-label: "The GitHub repo for this website"
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  #margin-footer: |
  #  ![](/img/CFAES-Horiz-RGBHEX.svg){width="50%"}
  page-footer:
    left: |
      2025, Jelmer Poelstra, [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)   ![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png){width="10%"}
    center: |
      ![](/img/CFAES-Horiz-RGBHEX.svg){width="40%"}
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25
        aria-label: "The GitHub repo for this website"
        #https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/25-aria-labels/

format:
  html:
    css: styles.css
    theme: cosmo
    highlight-style: atom-one
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 850px
    #self-contained: true
    #license: "CC BY-NC"

execute:
  freeze: auto
  engine: knitr
  eval: false
editor: source
