project:
  type: website
  output-dir: docs

website:
  title: "pracs-sp24"
  site-url: https://jelmerp.github.io/pracs-sp24
  repo-url: https://github.com/jelmerp/pracs-sp24
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Course intro, OSC and shell basics"
          href: week01/w1_overview.qmd
        - text: "Week 2: Project organization, Markdown & files in the shell"
        - text: "Week 3: Git and GitHub"
        - text: "Week 4: Shell script and CLI tools"
        - text: "Week 5: Software and batch jobs at OSC"
        - text: "Week 6: Pipelines"
        - text: "Week 7: Course recap"
      - text: "Lectures I"
        menu:
        - text: "Week 1: Introduction"
        - text: "I: Course Intro (slides)"
        - text: "II: Omics Data (slides)"
        - text: "III: OSC intro"
        - text: "--------"
        - text: "Week 2: Project organization"
        - text: "I: Project organization"
        - text: "II: VS Code & Markdown"
        - text: "III: Managing files in the shell"
        - text: "--------"
        - text: "Week 3: Git"
        - text: "I: Getting started with Git"
        - text: "II: Git remotes on GitHub"
        - text: "_(Bonus: Branching, collaborating, and undoing)_"
        - text: "--------"
        - text: "Week 4: Shell scripts"
        - text: "I: Shell scripts"
        - text: "II: Running CLI tools with shell scripts"
        - text: "_(Bonus: while loops, arrays, and more)_"
      - text: "Lectures II"
        menu:
        - text: "Week 5: Software and batch jobs at OSC"
        - text: "I: A closer look at OSC"
        - text: "II: Using software at OSC"
        - text: "III: Slurm batch jobs"
        - text: "_(Bonus: Connecting with SSH)_"
        - text: "--------"
        - text: "Week 6: Runner scripts and pipelines"
        - text: "I: Runner scripts and pipelines"
        - text: "II: Running an nf-core Nextflow pipeline"
        - text: "--------"
        - text: "Week 7: Course recap"
        - text: "Course recap & File transfer"
      - text: "Homework"
        menu:
        - text: "Exercises"
        - text: "Week 1: Shell basics"
          href: week01/w1_exercises.qmd
        - text: "Week 2: Markdown and files in the shell"
        - text: "Week 3: Git and GitHub"
        - text: "Week 4: Shell scripts and CLI tools"
        - text: "Week 5: Software and batch jobs at OSC"
        - text: "Week 6: Runner scripts and pipelines"
        - text: "--------"
        - text: "Assignments"
        - text: "Week 1: OSC account setup"
          href: week01/w1_osc-setup.qmd
        - text: "Week 2: GitHub account"
      - text: "Final project"
        menu:
        - text: "General info"
        - text: "I: Proposal (Due Apr 8)"
        - text: "II: Oral presentation (Apr 16 & 18)"
        - text: "III: Final submission (Due Apr 29)"
    right:
      - text: Miscellaneous
        menu: 
        - text: About this website
          href: about.qmd
        - text: "Course glossary"
        - text: "Unix shell reference"
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/163340
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
      - text: "{{< fa book >}}"
        href: https://library.ohio-state.edu/record=b8624007~S7
      - text: "{{< fa book-open >}}"
        href: https://library.ohio-state.edu/record=b9490023~S7
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  page-footer:
    left: "2024, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25

format:
  html:
    highlight-style: atom-one
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

execute:
  freeze: auto
  engine: knitr
editor: source
