project:
  type: website
  output-dir: docs

website:
  title: "PRACS-AU25"
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#666666"
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data and OSC"
          href: week01/w1_overview.qmd
        - text: "Week 2: Project organization, Markdown, and Unix shell basics"
          href: week02/w2_overview.qmd 
        - text: "Week 3: Working with files in the Unix shell"
          href: week03/w3_overview.qmd 
        - text: "Week 4: Version control with Git and GitHub"
          href: week04/w4_overview.qmd 
        - text: "Week 5: Data and software management at OSC"
        - text: "Week 6: Shell scripts and CLI tools"
        - text: "Week 7: Slurm batch jobs at OSC"
        - text: "Week 8: Using generative AI when coding"
        - text: "Week 9: Automated pipelines with Nextflow"
        - text: "Week 10: Building Nextflow pipelines"
        - text: "Week 11: R -- basics"
        - text: "Week 12: R -- data wrangling and visualization"
        - text: "Week 13: R -- Quarto"
        - text: "Week 14: R -- omics data"
        - text: "Week 15: Nextflow nf-core pipelines"
      - text: "Exercises"
        menu:
        - text: "Week 3: Unix shell"
          href: week03/w3_exercises.qmd
        - text: "Week 5: OSC data and software"
        - text: "Week 7: Slurm batch jobs"
        - text: "Week 9: Nextflow"
        - text: "Week 11: R basics"
        - text: "Week 12: R data visualization"
        - text: "Week 13: R for omics data"
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "GRADED"
        - text: "1. Week 2: Markdown and Unix shell basics"
          href: week02/w2_ga.qmd
        - text: "2. Week 4: Version control with Git and GitHub"
          href: week04/w4_ga.qmd
        - text: "3. Week 6: Shell scripting"
        - text: "4. Week 8: Slurm batch jobs"
        - text: "5. Week 10: Nextflow"
        - text: "6. Week 14: R"
        - text: "----------"
        - text: "UNGRADED"
        - text: "Week 1: Pre-course survey"
        - text: "Week 1: OSC account setup"
          href: week01/w1_ua_osc-setup.qmd
        - text: "Week 4: GitHub account setup"
          href: week04/w4_ua_github-account.qmd
        - text: "Week 16: Post-course survey"
      - text: "Final project"
        menu:
        - text: "General info"
        - text: "Checkpoint I: Proposal"
        - text: "Checkpoint II: Oral presentation"
        - text: "Checkpoint III: Final submission"
    right:
      - text: Other
        menu:
        - text: "Course glossary"
        - text: "References"
          href: ref/refs.qmd
        - text: "Further learning resources"
        - text: "----------"
        - text: OPTIONAL SELF-STUDY CONTENT
        - text: "Unix data tools (wk3)"
        - text: "Misc. Unix shell (wk3)"
        - text: "Git (wk4)"
        - text: "Software management with Conda (wk5)"
        - text: "SSH connection (wk5)"
        - text: "OSC file transfer (wk5)"
        - text: "Shell scripting and looping (wk6)"
        - text: "Slurm batch jobs (wk7)"
        - text: "----------"
        - text: TOPIC OVERVIEWS
      - text: About
        href: ref/about.qmd
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/187770
        aria-label: "The CarmenCanvas site for this course"
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
        aria-label: "The OSC OnDemand website"
    tools:
      - icon: github
        aria-label: "The GitHub repo for this website"
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  #margin-footer: |
  #  ![](/img/CFAES-Horiz-RGBHEX.svg){width="50%"}
  page-footer:
    left: |
      2025, Jelmer Poelstra, [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)   ![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png){width="10%"}
    center: |
      ![](/img/CFAES-Horiz-RGBHEX.svg){width="40%"}
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25
        aria-label: "The GitHub repo for this website"
        #https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/25-aria-labels/

format:
  html:
    css: styles.css
    theme: cosmo
    highlight-style: atom-one
    #license: "CC BY-NC"
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

execute:
  freeze: auto
  engine: knitr
  eval: false
editor: source
