project:
  type: website
  output-dir: docs

website:
  title: "pracs-au25"
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Course intro, omics data, and OSC intro"
          href: week01/w1_overview.qmd
        - text: "Week 2: Unix shell basics"
          href: week02/w2_overview.qmd 
        - text: "Week 3: Project organization, Markdown & files in the shell"
        - text: "Week 4: Git and GitHub"
        - text: "Week 5: Shell scripts and CLI tools"
        - text: "Week 6: Data and software management at OSC"
        - text: "Week 7: Slurm batch jobs at OSC"
        - text: "Week 8: Manual versus automated pipelines"
        - text: "Week 9: Nextflow nf-core pipelines"
        - text: "Week 10: Building Nextflow pipelines I"
        - text: "Week 11: Building Nextflow pipelines II"
        - text: "Week 12: R -- basics"
        - text: "Week 13: R -- data wrangling and visualization"
        - text: "Week 14: R -- Quarto"
        - text: "Week 15: R -- omics data"
      - text: "Exercises"
        menu:
        - text: "Week 2"
          href: week02/w2_exercises.qmd
        - text: "Week 3"
        - text: "Week 4"
        - text: "Week 5"
        - text: "Week 6"
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "Week 1: OSC account setup (ungraded)"
          href: week01/w1_ua_osc-setup.qmd
        - text: "Week 3: GitHub account (ungraded)"
          href: week03/w3_ua_github-account.qmd
      - text: "Final project"
        menu:
        - text: "General info"
        - text: "I: Proposal"
        - text: "II: Oral presentation"
        - text: "III: Final submission"
    right:
      - text: Miscellaneous
        menu: 
        - text: About this website
          href: about.qmd
        - text: "Course glossary"
        - text: "Unix shell reference"
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/163340
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
      - text: "{{< fa book >}}"
        href: https://library.ohio-state.edu/record=b8624007~S7
      - text: "{{< fa book-open >}}"
        href: https://library.ohio-state.edu/record=b9490023~S7
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  page-footer:
    left: "2025, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25

format:
  html:
    highlight-style: atom-one
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

execute:
  freeze: auto
  engine: knitr
editor: source
