project:
  type: website
  #output-dir: docs

website:
  title: "PRACS-AU25"
  favicon: img/favicon.png
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#666666"
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data and OSC"
          href: week01/w1_overview.qmd
        - text: "Week 2: Project organization and Unix shell basics"
          href: week02/w2_overview.qmd
        - text: "Week 3: Working with files in the Unix shell"
          href: week03/w3_overview.qmd
        - text: "Week 4: Version control with Git and GitHub"
          href: week04/w4_overview.qmd
        - text: "Week 5: Software management at OSC"
          href: week05/w5_overview.qmd
        - text: "Week 6: Shell scripts and CLI tools"
          href: week06/w6_overview.qmd
        - text: "Week 7: Slurm batch jobs at OSC [TBA]"
        - text: "Week 8: Halfway recap [TBA]"
        - text: "Week 9: Reproducibility and data management [TBA]"
        - text: "Week 10: Workflow management [TBA]"
        - text: "Week 11: R -- basics [TBA]"
        - text: "Week 12: R -- Quarto [TBA]"
        - text: "Week 13: R -- data visualization [TBA]"
        - text: "Week 14: R -- omics data [TBA]"
        - text: "Week 15: Nextflow nf-core pipelines [TBA]"
      - text: "Exercises"
        menu:
        - text: "Week 3: Unix shell"
          href: week03/w3_exercises.qmd
        - text: "Week 5: GitHub and software at OSC"
          href: week05/w5_exercises.qmd
        - text: "Week 7: Slurm batch jobs [TBA]"
        - text: "Week 9: Nextflow [TBA]"
        - text: "Week 11: R basics [TBA]"
        - text: "Week 12: Quarto [TBA]"
        - text: "Week 14: R for omics data [TBA]"
        - text: "Week 15: nf-core pipelines [TBA]"
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "GRADED"
        - text: "GA 1: Markdown and Unix shell basics (Week 2)"
          href: week02/w2_ga.qmd
        - text: "GA 2: Unix shell data tools and Git (Week 4)"
          href: week04/w4_ga.qmd
        - text: "GA 3: Shell scripting (Week 6) [TBA]"
        - text: "GA 4: Slurm batch jobs at OSC (Week 8) [TBA]"
        - text: "GA 5: Nextflow (Week 10) [TBA]"
        - text: "GA 6: Data analysis with R (Week 13) [TBA]"
        - text: "----------"
        - text: "UNGRADED"
        - text: "UA 1: Pre-course survey (week 1)"
          href: https://forms.office.com/r/YfMxzmzRdH
        - text: "UA 2: OSC account setup (week 1)"
          href: week01/w1_ua_osc-setup.qmd
        - text: "UA 3: GitHub account setup (week 4)"
          href: week04/w4_ua_github-account.qmd
        - text: "UA 4: Post-course survey (week 16) [TBA]"
      - text: "Final project"
        menu:
        - text: "General info [TBA]"
        - text: "FP 1: Proposal (week 12) [TBA]"
        - text: "FP 2: Draft (week 14) [TBA]"
        - text: "FP 3: Oral presentation (week 16) [TBA]"
        - text: "FP 4: Final submission (week 16) [TBA]"
    right:
      - text: Other
        menu:
        - text: "Course references"
          href: ref/refs.qmd
        - text: "Course glossary [TBA]"
        - text: "Collected further learning resources [TBA]"
      - text: About
        href: ref/about.qmd
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/187770
        aria-label: "The CarmenCanvas site for this course"
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
        aria-label: "The OSC OnDemand website"
    tools:
      - icon: github
        aria-label: "The GitHub repo for this website"
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  #margin-footer: |
  #  ![](/img/CFAES-Horiz-RGBHEX.svg){width="50%"}
  page-footer:
    left: |
      2025, Jelmer Poelstra, [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)   ![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png){width="10%"}
    center: |
      ![](/img/CFAES-Horiz-RGBHEX.svg){width="40%"}
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25
        aria-label: "The GitHub repo for this website"
        #https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/25-aria-labels/

format:
  html:
    css: styles.css
    theme: cosmo
    highlight-style: atom-one
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 850px
    #self-contained: true
    #license: "CC BY-NC"

execute:
  freeze: auto
  engine: knitr
  eval: true
editor: source

knitr:
  opts_chunk:
    class-output: regular-r-output
    class-message: regular-r-output
    class-warning: warning-r-output
    class-error: error-r-output
