project:
  type: website
  output-dir: docs

website:
  title: "PRACS-AU25"
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data and OSC"
          href: week01/w1_overview.qmd
        - text: "Week 2: Unix shell basics"
          href: week02/w2_overview.qmd 
        - text: "Week 3: Project organization and Markdown"
          href: week03/w3_overview.qmd 
        - text: "Week 4: Version control with Git and GitHub"
          href: week04/w4_overview.qmd 
        - text: "Week 5: Shell scripts and CLI tools"
          href: week05/w5_overview.qmd 
        - text: "Week 6: Data and software management at OSC"
          href: week06/w6_overview.qmd 
        - text: "Week 7: Slurm batch jobs at OSC"
          href: week07/w7_overview.qmd 
        - text: "Week 8: Using generative AI when coding"
          href: week08/w8_overview.qmd 
        - text: "Week 9: Automated pipelines with Nextflow"
          href: week09/w9_overview.qmd 
        - text: "Week 10: Building Nextflow pipelines"
          href: week10/w10_overview.qmd 
        - text: "Week 11: R -- basics"
          href: week11/w11_overview.qmd 
        - text: "Week 12: R -- data wrangling and visualization"
          href: week12/w12_overview.qmd 
        - text: "Week 13: R -- Quarto"
          href: week13/w13_overview.qmd 
        - text: "Week 14: R -- omics data"
          href: week14/w14_overview.qmd 
        - text: "Week 15: Nextflow nf-core pipelines"
          href: week15/w15_overview.qmd 
      - text: "Exercises"
        menu:
        - text: "Week 2: Unix shell basics"
          href: week02/w2_exercises.qmd
        - text: "Week 3: Project file organization"
          href: week03/w3_exercises.qmd
        - text: "Week 6: OSC data and software"
          href: week06/w6_exercises.qmd
        - text: "Week 8: Using generative AI"
          href: week08/w8_exercises.qmd
        - text: "Week 9: Nextflow"
          href: week09/w9_exercises.qmd
        - text: "Week 11: R basics"
          href: week11/w11_exercises.qmd
        - text: "Week 12: R data visualization"
          href: week12/w12_exercises.qmd
        - text: "Week 13: R for omics data"
          href: week13/w13_exercises.qmd
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "GRADED"
        - text: "1. Week 2: Shell basics"
          href: week02/w2_ga_shell.qmd
        - text: "2. Week 4: Markdown & Git"
          href: week04/w4_ga_git.qmd
        - text: "3. Week 5: Shell scripting"
          href: week05/w5_ga_shell-scripts.qmd
        - text: "4. Week 7: Slurm batch jobs"
          href: week07/w7_ga_slurm.qmd
        - text: "5. Week 10: Nextflow"
          href: week10/w10_ga_nextflow.qmd
        - text: "6. Week 14: R"
          href: week14/w14_ga_R.qmd
        - text: "----------"
        - text: "UNGRADED"
        - text: "Week 1: Pre-course survey"
        - text: "Week 1: OSC account setup"
          href: week01/w1_ua_osc-setup.qmd
        - text: "Week 4: GitHub account setup"
          href: week04/w4_ua_github-account.qmd
        - text: "Week 16: Post-course survey"
      - text: "Final project"
        menu:
        - text: "General info"
        - text: "Checkpoint I: Proposal"
        - text: "Checkpoint II: Oral presentation"
        - text: "Checkpoint III: Final submission"
    right:
      - text: Bonus & overviews
        menu:
        - text: OPTIONAL SELF-STUDY MATERIAL
        - text: "A deeper dive into Unix data tools"
        - text: "Advanced Git (wk4)"
          href: week05/w5_3_bonus.qmd
        - text: "Advanced Unix shell (wk5)"
          href: week05/w5_3_bonus.qmd
        - text: "OSC SSH connections (wk6)"
          href: week06/w6_4_bonus_ssh.qmd
        - text: "Other OSC file transfer options (wk6)"
          href: ref/file-transfer.qmd
        - text: "----------"
        - text: TOPIC OVERVIEWS
      - text: Miscellaneous
        menu: 
        - text: About this website
          href: ref/about.qmd
        - text: "Course readings"
          href: ref/readings.qmd
        - text: "Further learning resources"
          href: ref/resources.qmd
        - text: "Course glossary"
          href: ref/glossary.qmd
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/163340
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
#      - text: "{{< fa book >}}"
#        href: https://library.ohio-state.edu/record=b8624007~S7
#      - text: "{{< fa book-open >}}"
#        href: https://library.ohio-state.edu/record=b9490023~S7
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  page-footer:
    left: "2025, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25

format:
  html:
    highlight-style: atom-one
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

execute:
  freeze: auto
  engine: knitr
editor: source
