project:
  type: website
  output-dir: docs

website:
  title: "PRACS-AU25"
  site-url: https://mcic-osu.github.io/pracs-au25
  repo-url: https://github.com/mcic-osu/pracs-au25
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: Week overviews
        menu: 
        - text: "Week 1: Omics data and OSC"
          href: week01/w1_overview.qmd
        - text: "Week 2: Unix shell basics"
          href: week02/w2_overview.qmd 
        - text: "Week 3: Project organization and Markdown"
          href: week03/w3_overview.qmd 
        - text: "Week 4: Version control with Git and GitHub"
          href: week04/w4_overview.qmd 
        - text: "Week 5: Shell scripts and CLI tools"
          href: week05/w5_overview.qmd 
        - text: "Week 6: Data and software management at OSC"
          href: week06/w6_overview.qmd 
        - text: "Week 7: Slurm batch jobs at OSC"
        - text: "Week 8: Using generative AI when coding"
        - text: "Week 9: Automated pipelines with Nextflow"
        - text: "Week 10: Building Nextflow pipelines"
        - text: "Week 11: R -- basics"
        - text: "Week 12: R -- data wrangling and visualization"
        - text: "Week 13: R -- Quarto"
        - text: "Week 14: R -- omics data"
        - text: "Week 5: Nextflow nf-core pipelines"
      - text: "Exercises"
        menu:
        - text: "Week 2: Shell basics"
          href: week02/w2_exercises.qmd
        - text: "Week 3: Project file organization"
          href: week03/w3_exercises.qmd
        - text: "Week 4: Version control"
          href: week04/w4_exercises.qmd
        - text: "Week 5: Shell scripts"
          href: week05/w5_exercises.qmd
        - text: "Week 6: OSC"
        - text: "--------"
      - text: "Assignments"
        menu:
        - text: "Week 1: OSC account setup (ungraded)"
          href: week01/w1_ua_osc-setup.qmd
        - text: "Week 3: GitHub account setup (ungraded)"
          href: week03/w3_ua_github-account.qmd
      - text: "Final project"
        menu:
        - text: "General info"
        - text: "I: Proposal"
        - text: "II: Oral presentation"
        - text: "III: Final submission"
    right:
      - text: Miscellaneous
        menu: 
        - text: About this website
          href: about.qmd
        - text: "Course glossary"
        - text: "Unix shell reference"
      - text: "{{< fa graduation-cap >}}"
        href: https://osu.instructure.com/courses/163340
      - text: "{{< fa desktop >}}"
        href: https://ondemand.osc.edu
      - text: "{{< fa book >}}"
        href: https://library.ohio-state.edu/record=b8624007~S7
      - text: "{{< fa book-open >}}"
        href: https://library.ohio-state.edu/record=b9490023~S7
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mcic-osu/pracs-au25
          - text: Report an Issue
            url:  https://github.com/mcic-osu/pracs-au25/issues/new
  page-footer:
    left: "2025, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/pracs-au25

format:
  html:
    highlight-style: atom-one
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

execute:
  freeze: auto
  engine: knitr
editor: source
