---
title: "About this site and course"
author: Jelmer Poelstra
date: 2025-06-02
number-sections: false
---

-----

<hr style="height:1pt; visibility:hidden;" />

This is the GitHub website for the course
**Practical Computing Skills for Omics Data** (PLNTPTH 5006),
a 3-credit course taught at Ohio State University during the Fall semester of 2025.

The course is taught by by [Jelmer Poelstra](mailto:poelstra.1@osu.edu) from 
OSU's [Molecular and Cellular Imaging Center (MCIC)](https://mcic.osu.edu)
for the [Department of Plant Pathology](https://plantpath.osu.edu).

<hr style="height:1pt; visibility:hidden;" />

### Course description

As datasets have rapidly grown larger in biology,
coding has been recognized as an increasingly important skill for biologists.
This is especially true in “omics” research with data from e.g. genomics and
transcriptomics, which typically cannot be analyzed on a desktop computer,
where cutting-edge software has a command-line interface,
and where workflows can include many steps that need to be coordinated.

In this course, students will gain hands-on experience with a set of general
and versatile tools for data-intensive research in omics and beyond.
The course will focus on foundational skills such as working in the Unix shell
and writing shell scripts,
managing software and submitting jobs at a compute cluster
(the Ohio Supercomputer Center),
and building flexible, automated workflows.
Additionally, the course will cover reproducibly organizing, documenting,
and version-controlling research projects.
Taken together, this course will allow students to reproduce their own research, 
and enable others to reproduce their research, with as little as a single command.

<hr style="height:1pt; visibility:hidden;" />

### More information

#### Topics taught

- Unix shell: basics, scripting, running command-line programs
- R: Basics, data wrangling & visualization, Quarto, and specifics to omics data
- Supercomputer usage: basics, software, and running Slurm batch jobs
- Version control with Git and GitHub
- Reproducibility including project documentation with Markdown,
  project file organization, and data management
- Running and building Nextflow pipelines

#### Course books

- Allesina S, Wilmes M (2019).
  *[Computing Skills for Biologists](https://library.ohio-state.edu/record=b8624007~S7)*.
  Princeton UP.
- Buffalo V (2015).
  *[Bioinformatics Data Skills: Reproducible and Robust Research with Open Source Tools](https://library.ohio-state.edu/record=b9490023~S7)*.
  O'Reilly Media, Inc.

#### CarmenCanvas website

If you are a student in this course, you should also refer to the
CarmenCanvas site for this course (link TBA).
