---
number-sections: false
toc: false
format:
  html:
    grid:
      body-width: 1300px
---

<h4 align="center" style="font-size:30px">
[**Practical Computing Skills for Omics Data**]{style="color:#bb0000"} <br>       [Ohio State PLNTPTH 5004 -]{style="color:#969696"} [Autumn 2025]{style="color:#969696"}
</h4>

<hr style="height:1pt; visibility:hidden;" />

| Week | Tue session | Thu session | Ex./GA UA |
|-----------------|------------------|------------------|---------------------|
| [{{< fa book >}}](week01/w1_overview.qmd)   **01** | 08/26: [Course intro (slides)](week01/w1_1_course-intro.qmd) & [Omics data (slides)](week01/w1_2_omics-data.qmd) | 08/28: [The Ohio Supercomputer Center (OSC)](week01/w1_3_osc.qmd) |               [{{< fa laptop-code >}}](week01/w1_ua_osc-setup.qmd) |
| [{{< fa book >}}](week02/w2_overview.qmd)   **02** | 09/02: [Project organization](week02/w2_1_project-org.qmd) & [VS Code + Markdown](week02/w2_2_vscode-markdown.qmd) | 09/04: [Unix shell: Basics](week02/w2_3_shell.qmd) | [{{< fa tasks >}}](week02/w2_ga_markdown.qmd) |
| [{{< fa book >}}](week03/w3_overview.qmd)   **03** | 09/09: [Unix shell: Working with files I](week03/w3_1_shellfiles.qmd) | 09/11: [Unix shell: Working with files II](week03/w3_2_shellfiles.qmd) | [{{< fa user-edit >}}](week03/w3_exercises.qmd) |
| [{{< fa book >}}](week04/w4_overview.qmd)   **04** | 09/16: [Version control: Git](week04/w4_1_git.qmd) | 09/18: [Version control: GitHub](week04/w4_2_github.qmd) | [{{< fa tasks >}}](week04/w4_ga_git.qmd)         [{{< fa laptop-code >}}](week04/w4_ua_github-account.qmd) |
| [{{< fa book >}}](week05/w5_overview.qmd)   **05** | 09/23: [OSC part II](week05/w5_1_osc.qmd) & [Data management](week05/w5_2_data-management.qmd) | 09/25: [Software management](week05/w5_3_software.qmd) | [{{< fa user-edit >}}](week06/w6_exercises.qmd) |
| [{{< fa book >}}](week06/w6_overview.qmd)   **06** | 09/30: [Shell scripting: basics](week06/w6_1_scripts.qmd) | 10/02: [Shell scripting: running CLI software](week06/w6_2_cli-tools.qmd) | [{{< fa tasks >}}](week06/w6_ga_shell-scripts.qmd) |
| [{{< fa book >}}](week07/w7_overview.qmd)   **07** | 10/07: [Slurm batch jobs](week07/w7_1_slurm.qmd) | 10/09: [Workflow management with batch jobs](week07/w7_2_protocol.qmd) | [{{< fa user-edit >}}](week07/w7_exercises.qmd) |
| [{{< fa book >}}](week08/w8_overview.qmd)   **08** | 10/14: Using generative AI when coding | [*Fall break*]{style="color:#bebfc2"} | [{{< fa tasks >}}](week08/w8_ga.qmd) |
| [{{< fa book >}}](week09/w9_overview.qmd)   **09** | 10/21: [Workflow management with Nextflow](week09/w9_1_pipeline-intro.qmd) | 10/23: Building Nextflow pipelines I | [{{< fa user-edit >}}](week09/w9_exercises.qmd) |
| [{{< fa book >}}](week10/w10_overview.qmd)   **10** | 10/28: Building Nextflow pipelines II | 10/30: Building Nextflow pipelines III | [{{< fa tasks >}}](week10/w10_ga_nextflow.qmd) |
| [{{< fa book >}}](week11/w11_overview.qmd)   **11** | 11/04: R language basics | 11/06: Data wrangling with R | [{{< fa user-edit >}}](week11/w11_exercises.qmd) |
| [{{< fa book >}}](week12/w12_overview.qmd)   **12** | [*Veteran's day*]{style="color:#bebfc2"} | 11/13: Data visualization with R | [{{< fa user-edit >}}](week12/w12_exercises.qmd) |
| [{{< fa book >}}](week13/w13_overview.qmd)   **13** | 11/18: R for omics data I | 11/20: R for omics data II | [{{< fa user-edit >}}](week13/w13_exercises.qmd) |
| [{{< fa book >}}](week14/w14_overview.qmd)   **14** | 11/25: R + Markdown with Quarto | [*Thanksgiving*]{style="color:#bebfc2"} | [{{< fa tasks >}}](week14/w14_ga_R.qmd) |
| [{{< fa book >}}](week15/w15_overview.qmd)   **15** | 12/02: [Running nf-core pipelines I](week15/w15_1_nfcore.qmd) | 12/04: Running nf-core pipelines II | [{{< fa user-edit >}}](week15/w15_exercises.qmd) |
| [{{< fa book >}}](week16/w16_overview.qmd)   **16** | 12/09: Student presentations |  | |

: {.striped .hover}

::: legend2
{{< fa book >}} = Week overview       Ex. / {{< fa user-edit >}} = Exercises       UA / {{< fa laptop-code >}} = Ungraded assignment       GA / {{< fa tasks >}} = Graded assignment
:::
