---
title: "Pre-course assignment: OSC access"
author: Jelmer Poelstra
date: 2022-02-19
number-sections: false
toc: false
---

---------

<hr style="height:1pt; visibility:hidden;" />

### Overview

Before the course starts, you should make sure that you have access to the
Ohio Supercomputer Center (OSC), and the OSC Project for this course (PAS2700).

### Background

Much of the coding during this course will be done through your browser at the Ohio Supercomputer Center (OSC).
To access OSC, you will need to have an account.
This course has its own OSC Project,
and membership of this specific project will allow you to access our shared files and reserve "compute nodes".

### What you should do

After completing the [pre-course survey](https://forms.gle/vx2va7qfnNjRhg2M7),
you will receive an invitation email from OSC referencing the course project number PAS2700:

- **If you don't have an OSC account yet**\
  Follow the instructions in the email to sign up for OSC and accept the invitation.
  
- **If you already have an OSC account**\
  The email will likely tell you that you have been added to the project and don't have to do anything.

- **In either case, check whether you can log in**\
  Go to <https://ondemand.osc.edu> and log in by typing your username and password
  on the left-hand side of the page.
  If you just created your account, it may take up to half an hour or so before you can log in.

_If you have any questions about this or run into problems, don't hesitate to contact Jelmer._
