---
title: "Week 1: Intro to the course, omics data, and OSC"
pagetitle: "Week 1 overview"
number-sections: false
date: 2025-08-22
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "w1a: Course intro (slides)"
    icon: bookmarks
    href: w1a_course-intro.html
  - text: "w1b: Omics data (slides)"
    icon: bookmarks
    href: w1b_omics-data.html
  - text: "w1c: OSC"
    icon: bookmarks
    href: w1c_osc.html
  - text: "Ungraded assignment: OSC account setup"
    icon: pencil
    href: w1_ua_osc-setup.html
bibliography: ../references.bib
---

------------------------------------------------------------------------

<br>

## Overview

Welcome to the AU25 course Practical Computing Skills for Omics Data!
In this first week of the course,
you will get an overview of the course's contents
and introductions to omics data and the Ohio Supercomputer Center (OSC).

## Learning goals & lectures

In each of the following lectures, you will learn:

#### [**Course intro**](./w1a_course-intro.qmd) (Tuesday class)

- What to expect from this course
- Which tools and languages we will use
- What is expected of you during this course

#### [**Omics data**](./w1b_omics-data.qmd) (Tuesday/Thursday class)

- What omics data is
- What the main high-throughput sequencing technologies are
- How Illumina sequence libraries are structured
- What reference genomes are, and what they are good for
- What the main sequence file types are and what FASTA, FASTQ, and GFF/GTF files look like

#### [**The Ohio Supercomputer Center (OSC)**](./w1c_osc.qmd) (Thursday class)

- What a supercomputer is, and why they are useful
- What resources the Ohio Supercomputer Center (OSC) provides
- How to access OSC resources through its OnDemand webportal

## Readings

- @poinsignon2023: *Working with omics data: An interdisciplinary challenge at the crossroads of biology and computer science*  
  This book chapter provides an overview of different kinds of omics data.
  
- @markowetz2015: *Five selfish reasons to work reproducibly*  
  This short paper gives a light-hearted overview of self-interested reasons to
  perform your research reproducibly.
  
- ["Overview of Illumina Sequencing by Synthesis Workflow"](./w1b_omics-data.html#/video-of-illumina-technology)  
  Watch this 5-minute video to learn how Illumina sequencing works.
  This is meant to provide a bit more background,
  given that the example data in this course will be from Illumina sequencing.
  This is a very quick overview and you don't need to understand all the details!
  _(Optionally, also watch the video overviews of Oxford Nanopore and Pacific Biosciences_
  _sequencing technology that are embedded in the next two slides.)_

## Assignments & exercises

- **Ungraded assignment**: [Pre-course survey](https://forms.office.com/r/YfMxzmzRdH) [*Deadline: Tue Aug 26, 10 am*]{style="color:#bb0000"}
- **Ungraded assignment**: [Ohio Supercomputer Center account setup](w1_ua_osc-setup.qmd) [*Deadline: Wed Aug 27, 5 pm*]{style="color:#bb0000"}

## Further resources

Throughout the course, chapters from these two books are optional readings for this course.
Both can be accessed online for free with OSU credentials via the links below.

- @buffalo2015: [Bioinformatics Data Skills (Buffalo 2015)](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507) \
    This week: Preface and Chapter 1 -- *How to Learn Bioinformatics*

- @allesina2019: [Computing Skills for Biologists (Allesina & Wilmes 2019)](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085456156508507) \
    This week: Chapter 0 -- *Building a Computing Toolbox* (Introduction & Section 0.1 only)

Browse through the below paper titles and see if any of these spark your interest ---
many of these present omics and HTS data in a more field-specific light,
e.g. plant pathology.

- @lee2023: *The principles and applications of high-throughput sequencing technologies*
  ([link](https://www.ksdb.org/archive/view_article?pid=dr-27-1-9))
- @dijk2023: *Genomics in the long-read sequencing era* ([link](https://www-cell-com.proxy.lib.ohio-state.edu/trends/genetics/fulltext/S0168-9525(23)00119-1))
- @vonderheyden2025: *Advancing species conservation and management through omics tools* ([link](https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.14123))
- @nizamani2023: *High-throughput sequencing in plant disease management: a comprehensive review of benefits, challenges, and future perspectives* ([link](https://phytopatholres.biomedcentral.com/articles/10.1186/s42483-023-00199-5))
- @aragona2022: *New-generation sequencing technology in diagnosis of fungal plant pathogens: A dream comes true?* ([link](https://pmc.ncbi.nlm.nih.gov/articles/PMC9320658/))
- @mahmood2022: *Multi-omics revolution to promote plant breeding efficiency* ([link](https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2022.1062952/full))
- @rai2019: *A new era in plant functional genomics* ([link](https://www-sciencedirect-com.proxy.lib.ohio-state.edu/science/article/pii/S2452310019300216))
- @pinto2024: *Sequencing-based analysis of microbiomes* ([link](https://www.nature.com/articles/s41576-024-00746-6))
- @manzoni2018: *Genome, transcriptome and proteome: the rise of omics data and their integration in biomedical sciences* ([link](https://academic.oup.com/bib/article/19/2/286/2562648))
