---
title: "Ungraded assignment: OSC account setup"
subtitle: "Week 1 (deadline: Wed Aug 27, 5 pm)"
date: 2025-08-22
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 1 overview"
    icon: book
    href: w1_overview.html
  - text: "w1a: Course intro (slides)"
    icon: bookmarks
    href: w1a_course-intro.html
  - text: "w1b: Omics data (slides)"
    icon: bookmarks
    href: w1b_omics-data.html
  - text: "w1c: OSC"
    icon: bookmarks
    href: w1c_osc.html
number-sections: false
toc: false
---

---------

<hr style="height:1pt; visibility:hidden;" />

### Before you start

By [5 pm on Wed Aug 27]{style="color:#bb0000"},
you should make sure that you have access to the Ohio Supercomputer Center (OSC),
and the OSC Project for this course (PAS2880).

You will do much of your work during this course through your browser
at the Ohio Supercomputer Center (OSC),
starting this week's class on Thursday.

To access OSC, you will need to have an account.
This course has its own OSC "Project",
and membership of this specific project will allow you to access our
shared files and to reserve computing resources.

### What you should do

After completing the pre-course survey,
you will receive an invitation email from OSC referencing the course's project
number PAS2880, and:

- **If you don't have an OSC account yet**\
  Follow the instructions in the email to create an OSC account.
  
- **If you already have an OSC account**\
  The email will likely tell you that you have been added to the project and don't have to do anything.

- **In either case, check whether you can log in**\
  Go to <https://ondemand.osc.edu> and log in by typing your username and password
  on the left-hand side of the page.
  (If you just created your account,
  it can sometimes take up to half an hour or so before you can log in.)

_If you have any questions about this or run into problems, don't hesitate to contact Jelmer._
