---
title: "Software management: modules and containers"
subtitle: "Week 5 -- part III"
pagetitle: "PRACS25: software at OSC"
date: 2025-10-02
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
other-links:
  - text: "Week 5 overview"
    icon: book
    href: w5_overview.html
  - text: "Week 5 exercises"
    icon: pencil
    href: w5_exercises.html
  - text: "w5-1: OSC part II"
    icon: bookmarks
    href: w5_1_osc.html
  - text: "w5-2: Data management"
    icon: bookmarks
    href: w5_2_data-management.html
  - text: "Bonus: Conda"
    icon: book
    href: ../ref/conda.html
  - text: "Bonus: SSH connections"
    icon: book
    href: ../ref/ssh.html
  - text: "Bonus: More on file transfer"
    icon: book
    href: ../ref/file-transfer.html
editor_options: 
  chunk_output_type: console
engine: knitr
---

----------------------------------------------------------------------------------------------------

<br>

## Before we start

### Learning goals

### Setting up

<br>

## Introduction

### Software management (at OSC)

To analyze omics data sets, especially in genomics and transcriptomics,
a typical workflow includes running a sequence of specialized bioinformatics
software/programs/tools (I will use these terms interchangeably).

At OSC, there are system-wide installations of a number of bioinformatics programs.
We do need to "**load modules**" containing such programs before we can use them.
In this session, we will first talk about that process.

However, OSC's collection of bioinformatics programs is not comprehensive,
and the most recent versions are often not available.
(Additionally, your scripts are somewhat less portable
--as in, less likely to work across different computers/computing environments--
and therefore less reproducible when they contain `module load` commands
that will likely not work outside of OSC.)
We therefore need an additional way to use bioinformatics programs at OSC.
Two common ones are:

- **Containers**, which are self-contained software environments that include
  operating systems, akin to mini virtual machines.
  Docker containers are the most well-known, but OSC uses Apptainer
  (formerly known as Singularity).
  
- The **Conda** software management program,
  which creates software "environments" that you can load.
  
Conda and containers are useful:

- Specifically at supercomputers like OSC,
  where they bypass issues with dependencies^[
    Other software upon which the software that you are trying to install depends.]
  and administrator privileges^[
    When your personal computer asks you to "authenticate" while you are
    installing something, you are authenticating yourself as a user with
    administrator privileges. At OSC, you don't have such privileges.]
  that you may have when trying to install software in other ways.

- More generally for **reproducible software environments**.

- Because they make it easy to switch between different versions of the same
  software, or to use mutually incompatible software.

In this session, you will learn how to obtain and use Containers,
while [this optional-reading page covers Conda](../ref/conda.qmd).

::: {.callout-tip}
#### Other options to install software / get it installed at OSC

- Send an **email to [OSC Help](mailto:oschelp@osc.edu)**.
  They might be able to help you with your installation, or in case of commonly
  used software, might be willing to perform a system-wide installation
  (that is, making it available through Lmod / `module` commands).

- **"Manually" install the software**, which in the best case involves
  downloading a directly functioning binary (executable),
  but more commonly requires you to "compile" (build) the program.
  This is sometimes straightforward but can also become extremely tricky,
  especially at OSC where you don't have "administrator privileges"[^2]
  and will often have difficulties with "dependencies"[^3].
:::

<hr style="height:1pt; visibility:hidden;" />

### The FastQC software

As an example piece of bioinformatics software, we will use FastQC in this session.

FastQC is a ubiquitous tool for **quality control of FASTQ files**.
Running FastQC or a similar program is the first step in nearly any
high-throughput sequencing project.
FastQC is also a good introductory example of a tool with a command-line interface.

For each FASTQ file, FastQC outputs an **HTML file** that you can open in your
browser with about a dozen graphs showing different QC metrics.
The most important one is the *per-base quality score* graph:

![A FastQC per-base quality score graph for files with reasonably good quality reads.
The y-axis shows Phred quality scores (higher is better, see also the color-coding) and the x-axis shows the position along the read.](../img/fastqc_good.png){fig-align="center" width="70%"}

<br>

## Loading software at OSC with Lmod modules

OSC administrators manage software with the "Lmod" system of software modules.
This means that even though a piece of software may be installed,
**we may only be able to use it after we explicitly load it.**
That may seem like a drag, but on the upside,
this practice enables the use of different versions of the same software,
and of mutually incompatible software on a single system.

We can load, unload, and search for available software modules using the
**`module`** command and its sub-commands.

::: callout-note
#### Not all software has to be loaded
Not all software has to be loaded:
besides all the basic Unix commands we have been using,
very widely used software like Git, Python, and Apptainer (as we'll see below)
is available to us without loading anything.
:::

<hr style="height:1pt; visibility:hidden;" />

### Checking whether a piece of software is available

The OSC website has a
[list of installed software](<https://www.osc.edu/resources/available_software/software_list>).
You can also search for available software in the shell
using two subtly different `module` commands:
  
- `module spider` lists all installed modules.
- `module avail` lists modules that *can be directly loaded* given the current environment
  (i.e., when taking into account which other software has been loaded,
  which can make a difference).

Simply running `module spider` or `module avail` spits out complete lists
of installed/available programs ---
it is therefore more useful to add a **search term** as an argument.
For example, try to use `module spider` to search for `fastqc`:

```bash
module spider fastqc
```
``` {.bash-out}
--------------------------------------------------------------------------------
  fastqc: fastqc/0.12.1
--------------------------------------------------------------------------------

    This module can be loaded directly: module load fastqc/0.12.1

    Help:
      A quality control tool for high throughput sequence data.
```

We can see that `nextflow` is available, namely version `24.10.4`
(that is, it is printed as `<software>/<version>`).

::: callout-tip
#### These two search commands are not case-sensitive, but `module load` (below) _is_
:::

<hr style="height:1pt; visibility:hidden;" />

### Loading modules

All other Lmod software functionality is also accessed using `module` commands.
For instance, to make a program available to you, use the `load` command.

But first, let's check that we can indeed not use FastQC before doing so.
As the command to check whether FastQC is working,
we will use `fastqc -v`,
which should print the FastQC _version_ if that program is indeed available.

```bash
fastqc -v
```
```bash-out
bash: fastqc: command not found...
Failed to search for file: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer.
```

Now, let's load the modle ---
specify the module name _and_ its version exactly as `module spider` printed it:

```bash
module load fastqc/0.12.1
```

And we check again:

```bash
fastqc -v
```
```bash-out
FastQC v0.12.1
```

Note that module loading does _not_ persist across shell sessions.
Whenever you get a fresh shell session
(including but not limited to after logging into OSC again),
you will have to reload any modules you want to use!

#### Including `module load` in your shell script

When you run a program that is loaded with Lmod in your shell script,
always include the `module load` command in the script,
and it is best to do so way at the top of the script:

```bash
#!/bin/bash
set -euo pipefail

# Load software
module load fastqc/0.12.1
```

::: {.callout-tip collapse="true"}
#### Other `module` commands  _(Click to expand)_

To check which modules are loaded, use `module list`.
Its output also includes _automatically_ loaded modules ---
for example, after loading `miniconda3/24.1.2-py310`,
it should list `miniconda3` as the 9^th^ entry^[
This may vary over time and also depends on whether you run this in the VS Code
Server terminal --- some of the loaded modules are related to that.]:

```bash
module list
```
```{.bash-out}
Currently Loaded Modules:
  1) xalt/latest               3) intel/19.0.5     5) modules/sp2020     7) git/2.18.0              9) miniconda3/24.1.2-py310
  2) gcc-compatibility/8.4.0   4) mvapich2/2.3.3   6) project/ondemand   8) app_code_server/4.8.3
```

Occasionally, when you run into conflicting (mutually incompatible) modules,
it can be useful to unload modules,
which you can do with `module unload` or `module purge`:

```bash
module unload miniconda3    # Unload a specific module
module purge                # Unload all modules
```
:::

::: {.callout-note collapse="true"}
#### Another `module load` example: different versions with `pandoc` _(Click to expand)_

Say we wanted to use `pandoc`,
the software that can render Markdown files to e.g. HTML and PDF.
Let's check if it's available:

```bash
pandoc -v
```
```bash-out
pandoc 2.14.0.3
Compiled with pandoc-types 1.22.1, texmath 0.12.3.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
User data directory: /users/PAS0471/jelmer/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Hmmm, version 2.14 is [not nearly the most recent one](https://pandoc.org/releases.html).
Might a more recent one be available in a module?

```bash
module spider pandoc
```
```bash-out
------------------------------------------------------------------------------------------------------------------------------------------------------------
  pandoc:
------------------------------------------------------------------------------------------------------------------------------------------------------------
     Versions:
        pandoc/2.19.2
        pandoc/3.6.4
```

So, there are two additional versions available -- let's load the most recent one:

```bash
module load pandoc/3.6.4

pandoc -v
```
```bash-out
pandoc 3.6.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /users/PAS0471/jelmer/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Excellent!
:::

::: {.callout-note collapse="true"}
#### Another `module load` example: two-step procedure with `R` _(Click to expand)_

We'll start with testing if R doesn't just work out of the box:

```bash
R
```
```bash-out
bash: R: command not found...
```

Nope. Is it available as a module?

```bash
module spider R
```
```bash-out
------------------------------------------------------------------------------------------------------------------------------------------------------------
  R: R/4.4.0
------------------------------------------------------------------------------------------------------------------------------------------------------------

     Other possible modules matches:
        amber, app_code_server, app_jupyter, blender, connectome-workbench, darshan-runtime, darshan-util, deepemhancer, fmriprep, freesurfer, ...

    You will need to load all module(s) on any one of the lines below before the "R/4.4.0" module is available to load.

      gcc/12.3.0
 
    Help:
      R is 'GNU S', a freely available language and environment for
      statistical computing and graphics which provides a wide variety of
      statistical and graphical techniques: linear and nonlinear modelling,
      statistical tests, time series analysis, classification, clustering,
      etc. Please consult the R project homepage for further information.

------------------------------------------------------------------------------------------------------------------------------------------------------------
  To find other possible module matches execute:

      $ module -r spider '.*R.*'
```

Yes, so let's try to load it:

```bash
module load R/4.4.0
```
```bash-out
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested: "R/4.4.0"

   You encountered this error for one of the following reasons:
   1. Missing version specification: On Ascend, you must specify an available version.
   2. Missing required modules: Ensure you have loaded the appropriate compiler and MPI modules.

   Try: "module spider R/4.4.0" to view available versions or required modules.

   If you need further assistance, please contact oschelp@osc.edu with the subject line "lmod error: R/4.4.0"
```

If we carefully read the earlier message printed by `module spider`, ....

```bash
module load gcc/12.3.0 R/4.4.0
```
```bash-out
Lmod is automatically replacing "intel/2021.10.0" with "gcc/12.3.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) mvapich/3.0
```

```bash
R
```
```bash-out
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
```

Type `q()` or use the general keyboard short for exiting
<kbd>Ctrl/Cmd</kbd>+<kbd>D</kbd> to exit R.
:::

<hr style="height:1pt; visibility:hidden;" />

## Using Apptainer containers

**Containers** are similar to Virtual Machines
(and different from Modules and Conda environments)
in that they come with an entire _operating system_.

Among container platforms, Apptainer (formerly known as Singularity)
and especially Docker are the most widely used ones.
At supercomputers like OSC, however, only Apptainer containers can be used^[
But luckily, the Apptainer program can work with Docker container images:
it will convert them on the fly.].
Some container terminology:

- **Container image**: File that contains the container application.
- **Container** (sensu stricto): A _running_ container image.
- **Definition file**:
  A plain text file that contains the recipe to build a container image.
  
Here, you will learn how to find container "images" online and use them at OSC.
We will not cover writing Definition files to create your own custom computers,
as this is very rarely needed especially given recent developments in online
container availability (covered below).

### Quick overview

The **first step** to using a container is obtaining it: for example,
we will see how to get a link for a container that is available online.
Like regularly installing software, obtaining the container is one-time thing:
once you use or explicitly download it, the container image will remain. 

The **second step** is to run an appropriate command to access the software
in the container.
To run a command that is installed inside a container, the general syntax is:

- Referencing a `.sif` container image on your computer:

  ```bash
  apptainer exec <my-container.sif> <command>
  ```
  
- Referencing a container image online (!):

  ```bash
  apptainer exec <URL> <command>
  ```

This means that if the command in question is `fastqc`,
and we had a container image file `fastqc.sif`...

- Instead of running:

  ```bash
  fastqc -v
  ```

- You would run:

  ```bash
  apptainer exec fastqc.sif fastqc -v
  ```

  So, you just need to preface your "regular" command with `apptainer exec <sif/URL>`.

<hr style="height:1pt; visibility:hidden;" />

### Finding container images online

There are several online repositories with publicly available container images,
but I would strongly recommend Seqera Containers.
This is the most reliable site,
and also allows you to _very_ easily build custom containers that have a
combination of software.

Here is a step-by-step procedure to get a container for FastQC:

1. Go to **<https://seqera.io/containers>**.

2. In the **search box** below "Containers", enter `fastqc`.

3. After waiting for a bit for the list to populate,
   the **top hit** should be `bioconda::fastqc`,
   showing version `0.12.1` (the most recent version should always be shown).
  
4. **Add FastQC** by clicking the blue `+ Add` button.
   At this point, you could add additional software to your container,
   but we are happy with creating/fetching a container that only has FastQC.

5. In "**Container settings**" below the search box,
   change from `Docker` to `Singularity`
   (and leave the other dropdown as is - should be `linux/amd64`).
  
6. **Get a link** to the container image by clicking the blue
   `Get Container` button.

7. A link to the container image should appear immediately.
   In this case, the link should be: 
   `oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960`.
  
<hr style="height:1pt; visibility:hidden;" />

::: callout-tip
#### Other tips

- If we had wanted a different version of FastQC,
  we could have used the dropdown menu...

- In this case, after we clicked Get Container,
  it should have immediately said "Container is ready" in the pop-up box.
  This means that the container was already available in the repository.
  In other cases, however, the container may need to still be built,
  which could take one or a few minutes, and while the link won't change,
  you can only download/use the container once the "Container is ready".
  
- Always pick the Bioconda ones!
:::

<hr style="height:1pt; visibility:hidden;" />

### Running a container image

To recap, running a program in a container is done with a kind-of two-part command:

1. `apptainer exec <URL>` (or `apptainer exec <SIF>`) followed by
2. the "regular" command, e.g. `fastqc -v`

Let's check that we can run run FastQC in the container:

```bash
# [Don't run this, we'll need to add a TrimGalore command]
apptainer exec oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960 \
  fastqc -v
```
```bash-out
INFO:    Downloading oras image
384.0MiB / 384.0MiB [======================================================================================================================] 100 % 51.8 MiB/s 0s
INFO:    gocryptfs not found, will not be able to use gocryptfs
FastQC v0.12.1
```

Above, I broke the command up across two lines,
which can be done by ending the first line with a `\`.
This helps for readability for really long commands like this one
(and makes particular sense here given the "two-part structure" of the command
with the `apptainer prefix`).

The first time you run this command,
the container image will be downloaded to a default location (see box below),
as you can see in he output above --- this will take a minute or so.

When rerunning the same command,
Apptainer will realize that the container image has already been downloaded and
will automatically use the downloaded version:

```bash
# [Don't run this, we'll need to add a TrimGalore command]
apptainer exec oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960 \
  fastqc -v
```
```bash-out

TBA

INFO:    gocryptfs not found, will not be able to use gocryptfs
FastQC v0.12.1
```

_(You will keep seeing the `gocryptfs not found` message,_
_but this is nothing to worry about.)_

::: callout-tip
### The container image cache

(by default it will be downloaded to `~/.apptainer/cache`,
but you can change this by setting the `$APPTAINER_CACHEDIR` environment variable).
:::

<hr style="height:1pt; visibility:hidden;" />

### Running FastQC

As explained above,
you'll want to run bioinformatics tools like FastQC using a script that we'll
submit to the compute job queue at OSC.
For now, though,
you will get a feel for using the program by running it directly in the shell 
(i.e., "interactively"). 

The command `fastqc` will run the FastQC program.
If you want to analyze a FASTQ file with default FastQC settings,
a complete FastQC command would simply be `fastqc` followed by the file name:

``` bash
# [Don't run this]
apptainer exec oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960 \
  fastqc garrigos-data/fastq/ERR10802863_R1.fastq.gz
```

However, an annoying FastQC default behavior is that it writes its output files
in the same dir that contains the input FASTQ files ---
this means mixing your raw data with your results, which we don't want!

#### Changing the output directory?

To figure out how to change that behavior,
first consider that many standard Unix commands and bioinformatics tools alike
have an **option `-h` and/or `--help`** to print usage information to the screen.
Let's try that:

``` bash
apptainer exec oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960 \
  fastqc -h
```
``` bash-out

TBA

```

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} **Exercise**: FastQC help and output dir
Look at FastQC's help info,
and figure out which option you can use to specify a custom output directory.

<details><summary>*Click for the solution*</summary>
Running `fastqc -h` or `fastqc --help` will work to show the help info.
You'll get quite a bit of output printed to screen,
including the snippet about output directories that is reproduced below:

``` bash
fastqc -h
```
``` bash-out
  -o --outdir     Create all output files in the specified output directory.
                    Please note that this directory must exist as the program
                    will not create it.  If this option is not set then the 
                    output file for each sequence file is created in the same
                    directory as the sequence file which was processed.
```

So, you can use `-o` or equivalently, `--outdir`, to specify an output dir.
</details>
:::

<hr style="height:1pt; visibility:hidden;" />

#### The final command

With the added `--outdir` (or `-o`) option,
let's try to run the following FastQC command:

``` bash
# We'll have to first create the outdir ourselves, in this case
mkdir -p results/fastqc

# Now we run FastQC
apptainer exec oras://community.wave.seqera.io/library/fastqc:0.12.1--104d26ddd9519960 \
  fastqc --outdir results/fastqc garrigos-data/fastq/ERR10802863_R1.fastq.gz
```
``` bash-out
Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
[...truncated...]
Analysis complete for ERR10802863_R1.fastq.gz
```

In the output dir we specified, we have a `.zip` file,
which contains tables with FastQC's data summaries,
and an `.html` (HTML) file, which contains the graphs:

``` bash
ls -lh results/fastqc
```
``` bash-out
total 512K
-rw-rw----+ 1 jelmer PAS0471 241K Mar 21 09:53 ERR10802863_R1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 256K Mar 21 09:53 ERR10802863_R1_fastqc.zip
```

::: callout-note
#### Specifying an output dir vs. output file(s)
FastQC allows us to specify the output directory, but not the output file names:
these will be automatically determined based on the input file name(s).
This kind of behavior is fairly common for bioinformatics programs,
since they will often produce multiple output files.
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} **Exercise**: Another FastQC run

Run FastQC for the corresponding R2 FASTQ file.
Would you use the same output dir or a separate one?

<details><summary>*Click for the solution*</summary>

Yes, it makes sense to use the same output dir, since as you could see above,
the output file names have the input file identifiers in them.
As such, we don't need to worry about overwriting files,
and it will be more convenient to have all results in a single dir.

To run FastQC for the R2 (reverse-read) file:

``` bash
fastqc --outdir results/fastqc garrigos-data/fastq/ERR10802863_R2.fastq.gz
```
``` bash-out
Started analysis of ERR10802863_R2.fastq.gz
Approx 5% complete for ERR10802863_R2.fastq.gz
Approx 10% complete for ERR10802863_R2.fastq.gz
Approx 15% complete for ERR10802863_R2.fastq.gz
[...truncated...]
Analysis complete for ERR10802863_R2.fastq.gz
```

``` bash
ls -lh results/fastqc
```
``` bash-out
total 1008K
-rw-rw----+ 1 jelmer PAS0471 241K Mar 21 09:53 ERR10802863_R1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 256K Mar 21 09:53 ERR10802863_R1_fastqc.zip
-rw-rw----+ 1 jelmer PAS0471 234K Mar 21 09:55 ERR10802863_R2_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 244K Mar 21 09:55 ERR10802863_R2_fastqc.zip
```

Now, we have four files: two for each of our preceding successful FastQC runs.

</details>
:::
