---
title: "Running command-line tools with shell scripts"
subtitle: "Week 5 - part III"
pagetitle: "PRACS25: CLI tools in shell scripts"
author: Jelmer Poelstra
date: 2025-09-25
editor_options: 
  chunk_output_type: console
---

----------------------------------------------------------------------------------------------------

<br>

## Introduction

### Learning goals

This session focuses on using programs, like various bioinformatics tools,
with command-line interfaces (CLIs), and on running these **using shell scripts**.

Recall from the previous session's learning goals that this is one step in being
able to run your analyses highly efficiently by submitting scripts as
-potentially large numbers of- "batch jobs" using HPC resources like those at OSC.

More specifically, the strategy you'll learn is
**writing scripts that run a single program a single time**.
This will be true even if you need to run the program many times, so you will:

- loop over files/samples _outside_ of that script and run/submit the script
  possibly many times;
  
- need to make these scripts flexible:
  instead of "hard-coding" file paths and potentially other settings,
  you will pass arguments to scripts like you learned in the previous session.
  
When your scripts are flexible and you commonly loop over them,
this means that
**you'll also type lots of important code outside of these scripts**.
You will need to store this code,
as it will provide a record of what you did and can easily be reorganized into
a reproducible protocol of your workflow.
_We will continue to a use Markdown files for purpose. _

We'll start with a quick intro to FASTQ files and the FastQC program,
which will be our first example of a CLI tool.

### Getting ready {-}


<br>

## Running FastQC interactively

As explained above,
you'll want to run bioinformatics tools like FastQC using a script that we'll
submit to the compute job queue at OSC.
For now, though,
you will get a feel for using the program by running it directly in the shell 
(i.e., "interactively"). 

The command `fastqc` will run the FastQC program.
If you want to analyze a FASTQ file with default FastQC settings,
a complete FastQC command would simply be `fastqc` followed by the file name:

``` bash
# (Don't run this)
fastqc garrigos_data/fastq/ERR10802863_R1.fastq.gz
```

However, an annoying FastQC default behavior is that it writes its output files
in the same dir that contains the input FASTQ files ---
this means mixing your raw data with your results, which we don't want!

To figure out how we can change that behavior,
first consider that many commands and bioinformatics tools alike have an
**option `-h` and/or `--help`** to print usage information to the screen.
Let's try that:

``` bash
fastqc -h
```
``` bash-out
bash: fastqc: command not found...
```

However, there is a wrinkle --- while FastQC is installed at OSC[^2],
we have to first **"load it"**^[
We'll talk more about loading (and installing) software at OSC next week.]:

[^2]: For a full list of installed software at OSC:
<https://www.osc.edu/resources/available_software/software_list>.

``` bash
module load fastqc/0.12.1
```

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} **Exercise**: FastQC help and output dir
Print FastQC's help info,
and figure out which option you can use to specify a custom output directory.

<details><summary>*Click for the solution*</summary>
Running `fastqc -h` or `fastqc --help` will work to show the help info.
You'll get quite a bit of output printed to screen,
including the snippet about output directories that is reproduced below:

``` bash
fastqc -h
```
``` bash-out
  -o --outdir     Create all output files in the specified output directory.
                    Please note that this directory must exist as the program
                    will not create it.  If this option is not set then the 
                    output file for each sequence file is created in the same
                    directory as the sequence file which was processed.
```

So, you can use `-o` or equivalently, `--outdir` to specify an output dir.
</details>
:::

<hr style="height:1pt; visibility:hidden;" />

With the added `--outdir` (or `-o`) option, let's try to run the following FastQC command:

``` bash
# We'll have to first create the outdir ourselves, in this case
mkdir -p results/fastqc

# Now we run FastQC
fastqc --outdir results/fastqc garrigos_data/fastq/ERR10802863_R1.fastq.gz
```
``` bash-out
Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
[...truncated...]
Analysis complete for ERR10802863_R1.fastq.gz
```

In the output dir we specified, we have a `.zip` file,
which contains tables with FastQC's data summaries,
and an `.html` (HTML) file, which contains the graphs:

``` bash
ls -lh results/fastqc
```
``` bash-out
total 512K
-rw-rw----+ 1 jelmer PAS0471 241K Mar 21 09:53 ERR10802863_R1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 256K Mar 21 09:53 ERR10802863_R1_fastqc.zip
```

::: callout-note
#### Specifying an output dir vs. output file(s)
FastQC allows us to specify the output directory, but not the output file names:
these will be automatically determined based on the input file name(s).
This kind of behavior is fairly common for bioinformatics programs,
since they will often produce multiple output files.
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} **Exercise**: Another FastQC run

Run FastQC for the corresponding R2 FASTQ file.
Would you use the same output dir or a separate one?

<details><summary>*Click for the solution*</summary>

Yes, it makes sense to use the same output dir, since as you could see above,
the output file names have the input file identifiers in them.
As such, we don't need to worry about overwriting files,
and it will be more convenient to have all results in a single dir.

To run FastQC for the R2 (reverse-read) file:

``` bash
fastqc --outdir results/fastqc garrigos_data/fastq/ERR10802863_R2.fastq.gz
```
``` bash-out
Started analysis of ERR10802863_R2.fastq.gz
Approx 5% complete for ERR10802863_R2.fastq.gz
Approx 10% complete for ERR10802863_R2.fastq.gz
Approx 15% complete for ERR10802863_R2.fastq.gz
[...truncated...]
Analysis complete for ERR10802863_R2.fastq.gz
```

``` bash
ls -lh results/fastqc
```
``` bash-out
total 1008K
-rw-rw----+ 1 jelmer PAS0471 241K Mar 21 09:53 ERR10802863_R1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 256K Mar 21 09:53 ERR10802863_R1_fastqc.zip
-rw-rw----+ 1 jelmer PAS0471 234K Mar 21 09:55 ERR10802863_R2_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 244K Mar 21 09:55 ERR10802863_R2_fastqc.zip
```

Now, we have four files: two for each of our preceding successful FastQC runs.

</details>
:::

<br>

## Running FastQC with a shell script

Instead of running FastQC interactively, we'll want to write a script that runs it.
Specifically, our script will deliberately run FastQC on **only one FASTQ file**.

In bioinformatics, you commonly need to run a CLI tool many times,
because many tools can or have to be run separately run for each file or sample.
Instead of writing a script that runs one file or sample,
a perhaps more intuitive approach would be writing a script that 
_processes all files/samples in a single run_.
That could for example be accomplished by:

- Looping over files/samples inside the script; _**or**_
- Passing many file names or a glob with `*` to a single run of the tool
  (this can be done with _some_ tools).

However, given that we have access to OSC's clusters, it will save running time
-potentially _a lot of_ it- when we **submit a separate batch job for each FASTQ file**^[
  Another alternative is to use **Slurm job arrays**,
  which is a very reasonable approach as well but not what we will use.
  One drawback of this approach is that you start to rely more on specific capabilities
  of the Slurm job scheduler, so it is less flexible/portable.
].
This is why we will write a script such that runs only one file,
and then we'll run that script many times using a loop _outside_ of the script.

For now, we'll practice with writing scripts this way, and running them interactively.
In two weeks, we will take the next step and submit each run of the script as a batch job.

<hr style="height:1pt; visibility:hidden;" />

### Arguments to the script

Our favored approach of running the script for one FASTQ file at a time means that
our script needs to **accept a FASTQ file name as an argument**.

Then, inside the script, instead of using a line like the one we ran above...

```bash
# [Don't copy or run this]
fastqc --outdir results/fastqc garrigos_data/fastq/ERR10802863_R2.fastq.gz
```

...we would run FastQC using a variable for the file name --- for example:

```bash
# [Don't copy or run this]
fastqc --outdir results/fastqc "$fastq_file"
```

And while we're at it, we may also want to use a script argument for the output dir,
so would not have to hard-code that in the script's code either:

```bash
# [Don't copy or run this]
fastqc --outdir "$outdir" "$fastq_file"
```

With code to copy the placeholder variables that contain the command-line arguments,
that part of the script would then look as follows:

```bash
# [Don't copy or run this]
# Copy the placeholder variables
fastq_file=$1
outdir=$2

# Run FastQC
fastqc --outdir "$outdir" "$fastq_file"
```

<hr style="height:1pt; visibility:hidden;" />

::: callout-note
#### Running the script
And such a script would be run for a single file as follows:

```bash
# [Don't copy or run this]
# Syntax: 'bash <script-path> <argument1> <argument2>'
bash scripts/fastqc.sh garrigos_data/fastq/ERR10802863_R2.fastq.gz results/fastqc
```

And it would be run for all files by looping over all them as follows:

```bash
# [Don't copy or run this]
# Run the script separately for each FASTQ file
for fastq_file in data/fastq/*fastq.gz; do
    bash scripts/fastqc.sh "$fastq_file" results/fastqc
done
```
:::

<hr style="height:1pt; visibility:hidden;" />

### Creating an initial script

We saw some code to run FastQC inside a script,
to which we should add a number of "boilerplate" bits of code:

- The shebang line and strict Bash settings:

  ```bash
  #!/bin/bash
  set -euo pipefail
  ```

- A line to load the relevant OSC software module:

  ```bash
  module load fastqc/0.12.1
  ```
  
- A line to create the output directory if it doesn't yet exist:

  ```bash
  mkdir -p "$outdir"
  ```

:::{.callout-tip collapse="true"}
## Refresher: the `-p` option to `mkdir` _(Click to expand)_

Using the `-p` option does two things at once,
and both are necessary for a foolproof inclusion of this command in a script:

- It will enable `mkdir` to create multiple levels of directories at once
  (i.e., to act _recursively_):
  by default, `mkdir` errors out if the parent directory/ies of the
  specified directory don't yet exist.

  ```bash
  mkdir newdir1/newdir2
  ```
  ```{.bash-out}
  mkdir: cannot create directory ‘newdir1/newdir2’: No such file or directory
  ```

  ```bash
  # This successfully creates both directories
  mkdir -p newdir1/newdir2
  ```

- If the directory already exists, it won't do anything and won't return an error.
  Without this option, `mkdir` would return an error in this case,
  which would in turn lead the script to abort at that point with our `set` settings:
  
  ```bash
  mkdir newdir1/newdir2
  ```
  ```{.bash-out}
  mkdir: cannot create directory ‘newdir1/newdir2’: File exists
  ```

  ```bash
  # This does nothing since the dirs already exist
  mkdir -p newdir1/newdir2
  ```
:::

With those additions, our partial script would look like this:

```bash
# [Don't copy or run this - we'll add to it later]

#!/bin/bash
set -euo pipefail

# Load the OSC module for FastQC
module load fastqc/0.12.1

# Copy the placeholder variables
fastq_file=$1
outdir=$2

# Create the output dir if needed
mkdir -p "$outdir"

# Run FastQC
fastqc --outdir "$outdir" "$fastq_file"
```

Notice that this script to run a CLI tool is very similar to our "toy scripts"
from the previous sessions: mostly standard ("boilerplate") code with
**just a single command to run our program of interest.**
Therefore, you can adopt this script as a template for scripts that run other
command-line programs, and will generally only need minor modifications!

<hr style="height:1pt; visibility:hidden;" />

### Add some "logging" statements

It is often useful to have your scripts "report" or "log" what is going on.
For instance:

- At what date and time did we run this script. 
- Which arguments were passed to the script.
- What are the designated output dirs/files.
- Perhaps even summaries of the output (we won't do this here).

All of this can help with troubleshooting and record-keeping[^3].
Let's try this with our FastQC script:

[^3]: We'll see in the upcoming Slurm module that we when
      submit scripts to the OSC queue (rather than running them directly),
      the output of scripts that is normally printed to screen,
      will instead go to a sort of "log" file.
      So, your script's reporting will end up in this file.

```bash
#!/bin/bash
set -euo pipefail

# Load the OSC module for FastQC
module load fastqc/0.12.1

# Copy the placeholder variables
fastq_file=$1
outdir=$2

# Initial reporting
echo "# Starting script fastqc.sh"
date
echo "# Input FASTQ file:   $fastq_file"
echo "# Output dir:         $outdir"
echo

# Create the output dir if needed
mkdir -p "$outdir"

# Run FastQC
fastqc --outdir "$outdir" "$fastq_file"

# Final reporting
echo
echo "# Done with script fastqc.sh"
date
```

A couple of notes about the lines that were added to the script above:

- We printed a "marker line" `Done with script` that indicates the end of the
  script was reached. This is handy due to our `set` settings:
  **seeing this line printed means that no errors were encountered**.
- Running `date` at the beginning and end of the script is one way to check the
  running time of the script.
- Printing the input files can be particularly useful for troubleshooting.
- The lines that only have `echo` will simply print a blank line,
  basically as a separator between sections.

{{< fa user-edit >}} Create a script to run FastQC:

```bash
touch scripts/fastqc.sh
```

Open it and paste in the code in the box above.

### Add the program version

Here is one small best-practice addition to shell scripts that was used in last
week's exercises, which I also wanted to point out here
(you may want to use this in your final project!).
For scripts that run bioinformatics tools,
it's a good idea **include a line to print the program version**.
For example, the FastQC script contained the following lines at the end:

```bash
echo "# Used FastQC version:"
fastqc --version
```

This way you'll always have a clear record of the version that you used when you
ran the script, at least if you keep the Slurm log file
(and in last week's exercises, we additionally moved Slurm log files to a
`logs` dir within the output dir).

<hr style="height:1pt; visibility:hidden;" />

### Running your FastQC script for 1 file

Run your FastQC script for one FASTQ file:

```bash
bash scripts/fastqc.sh garrigos_data/fastq/ERR10802863_R1.fastq.gz results/fastqc
```
```bash-out
# Starting script fastqc.sh
Wed Mar 27 21:53:13 EDT 2024
# Input FASTQ file:   garrigos_data/fastq/ERR10802863_R1.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
Approx 20% complete for ERR10802863_R1.fastq.gz
Approx 25% complete for ERR10802863_R1.fastq.gz
Approx 30% complete for ERR10802863_R1.fastq.gz
Approx 35% complete for ERR10802863_R1.fastq.gz
Approx 40% complete for ERR10802863_R1.fastq.gz
Approx 45% complete for ERR10802863_R1.fastq.gz
Approx 50% complete for ERR10802863_R1.fastq.gz
Approx 55% complete for ERR10802863_R1.fastq.gz
Approx 60% complete for ERR10802863_R1.fastq.gz
Approx 65% complete for ERR10802863_R1.fastq.gz
Approx 70% complete for ERR10802863_R1.fastq.gz
Approx 75% complete for ERR10802863_R1.fastq.gz
Approx 80% complete for ERR10802863_R1.fastq.gz
Approx 85% complete for ERR10802863_R1.fastq.gz
Approx 90% complete for ERR10802863_R1.fastq.gz
Approx 95% complete for ERR10802863_R1.fastq.gz
Approx 100% complete for ERR10802863_R1.fastq.gz
Analysis complete for ERR10802863_R1.fastq.gz

# Done with script fastqc.sh
Wed Mar 27 21:53:19 EDT 2024
```

However, as discussed above,
we'll eventually want to run the script for each FASTQ file.
We will write the loop to do so in an accompanying Markdown document.

<br>

## Markdown files to document your progress and store your workflow

### Storing the code that runs/submits your scripts

The abovementioned loop code _could_ be directly typed in the terminal,
but we need to keep a record of and/or build a protocol of our analysis steps,
so we will save this in a Markdown file.

For small projects, this could be added to your main `README.md`.
For larger projects,
you will probably want to store this in one or more separate files.

For anything but the smallest projects, you should also distinguish between:

- A "lab notebook"-style file that has chronological entries with everything of note
  that you did, including mishaps, dead ends, and things that were redone differently
  later on.

- A "protocol" (or "recipe" / "workflow") style file that has the final code that
  can be used to run and rerun your project's analyses.

TBA expand

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-tip collapse="false"}
#### Keep the scripts for individual steps simple
It is a good idea to keep the shell scripts you will submit (e.g., `fastqc.sh`) simple
_in the sense that they should generally just run one program_,
and not a sequence of programs.

Once you get the hang of writing these scripts,
it may seem appealing to string a series of programs/steps together in a single script,
so that it's easier to rerun everything at once ---
but in practice, that will often end up leading to more difficulties than convenience.
If you do want to develop a workflow that can be easily run and rerun
from start to finish,
you should learn a workflow management system like Snakemake or Nextflow ---
we will talk about Nextflow later in the course.
:::

<hr style="height:1pt; visibility:hidden;" />

### Creating our protocol document

Create a new file...

```bash
touch 00_run.md
```

...and open it in the VS Code editor.

In this file, add an explanatory note followed by a `bash` code block,
and then run the code inside the code block:

````markdown
- Step 1: run FastQC for each FASTQ file:

```bash
for fastq_file in garrigos_data/fastq/*fastq.gz; do
    bash scripts/fastqc.sh "$fastq_file" results/fastqc
done
```
````

```bash-out
# Starting script fastqc.sh
Thu Mar 21 10:06:46 EDT 2024
# Input FASTQ file:   garrigos_data/fastq/ERR10802863_R1.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
Approx 20% complete for ERR10802863_R1.fastq.gz
Approx 25% complete for ERR10802863_R1.fastq.gz
Approx 30% complete for ERR10802863_R1.fastq.gz
Approx 35% complete for ERR10802863_R1.fastq.gz
Approx 40% complete for ERR10802863_R1.fastq.gz
Approx 45% complete for ERR10802863_R1.fastq.gz
Approx 50% complete for ERR10802863_R1.fastq.gz
Approx 55% complete for ERR10802863_R1.fastq.gz
Approx 60% complete for ERR10802863_R1.fastq.gz
Approx 65% complete for ERR10802863_R1.fastq.gz
Approx 70% complete for ERR10802863_R1.fastq.gz
Approx 75% complete for ERR10802863_R1.fastq.gz
Approx 80% complete for ERR10802863_R1.fastq.gz
Approx 85% complete for ERR10802863_R1.fastq.gz
Approx 90% complete for ERR10802863_R1.fastq.gz
Approx 95% complete for ERR10802863_R1.fastq.gz
Approx 100% complete for ERR10802863_R1.fastq.gz
Analysis complete for ERR10802863_R1.fastq.gz

# Done with script fastqc.sh
Thu Mar 21 10:06:51 EDT 2024

# Starting script fastqc.sh
Thu Mar 21 10:06:51 EDT 2024
# Input FASTQ file:   garrigos_data/fastq/ERR10802863_R2.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R2.fastq.gz
Approx 5% complete for ERR10802863_R2.fastq.gz
Approx 10% complete for ERR10802863_R2.fastq.gz
# [...output truncated...]
```

<br>

## Looping over samples rather than files 

In some cases, we can't simply loop over all files like we have done so far.
For example, in many tools that process paired-end FASTQ files,
the corresponding R1 and R2 files for each sample must be processed together.
That is, we don't run the tool separately for each FASTQ file,
but separately for each sample i.e. each _pair_ of FASTQ files.

How can we loop over pairs of FASTQ files instead? There are two main ways:

- Create a list of **sample IDs**, loop over these IDs, and find the pair of
  FASTQ files with matching names.
- Loop over the **R1 files only** and then infer the name of the corresponding
  R2 file within the loop. This is generally straightforward because the file names
  should be identical other than the read-direction identifier (`R1`/`R2`).

Below, we will use the second method --- but first, we'll recap/learn a few prerequisites.

<hr style="height:1pt; visibility:hidden;" />

### Recap of `basename`, and `dirname`

Running the `basename` command on a filename will strip any directories in its name:
  
```sh
basename garrigos_data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
ERR10802863_R1.fastq.gz
```

You can also provide any arbitrary *suffix to also strip* from the file name:

```sh
basename garrigos_data/fastq/ERR10802863_R1.fastq.gz .fastq.gz
```
```bash-out
ERR10802863_R1
```

If you instead want the _directory_ part of the path, use the `dirname` command:

```sh
dirname garrigos_data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
garrigos_data/fastq
```

<hr style="height:1pt; visibility:hidden;" />

### Parameter expansion

You can use so-called "parameter expansion", with parameter basically being another
word for variable, to search-and-replace text in your variable's values.
For example:

- Assign a short DNA sequence to a variable:

  ```bash
  dna_seq="AAGTTCAT"
  echo "$dna_seq"
  ```
  ```bash-out
  AAGTTCAT
  ```

- Use parameter expansion to replace all `T`s with `U` to convert the DNA to RNA:

  ```bash
  echo "${dna_seq//T/U}"
  ```
  ```bash-out
  AAGUUCAT
  ```

- You can also assign the result of the parameter expansion back to a variable:

  ```bash
  rna_seq="${dna_seq//T/U}"
  echo "$rna_seq"
  ```
  ```bash-out
  AAGUUCAT
  ```

So, the syntax for this type of parameter expansion is `{var_name//<search>/replace}` ---
let's deconstruct that:

1. Reference the variable, using the full notation, with braces (`${var_name}`)
2. After the first two forward slashes, enter the search pattern: (`T`)
3. After another forward slash, enter the replacement: (`U`).

If you needed to replace at most one of the search patterns, a single backslash
after the variable name would suffice: `{var_name/<search>/replace}`.

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: Get the R2 file name with parameter expansion
File names of corresponding R1 and R2 FASTQ files should be identical other than
the marker indicating the read direction,
which is typically `R1`/`R2` (and in some cases just `1` and `2`).

After assigning the file name `garrigos_data/fastq/ERR10802863_R1.fastq.gz` to a variable,
as shown below,
add the parameter expansion we need to obtain the name of the corresponding R2 file
by completing the second line:

```bash
fastq_R1=garrigos_data/fastq/ERR10802863_R1.fastq.gz
fastq_R2=
```

<details><summary>Solutions</summary>

```bash
fastq_R1=garrigos_data/fastq/ERR10802863_R1.fastq.gz
fastq_R2=${fastq_R1/_R1/_R2}
```

Test that it worked:

```bash
echo "$fastq_R2"
```
```bash-out
garrigos_data/fastq/ERR10802863_R2.fastq.gz
```
</details>
:::

<hr style="height:1pt; visibility:hidden;" />

### A per-sample loop

We will now create a loop that:

- Loops over R1 FASTQ files only, and then infers the corresponding R2 file name.
- Defines output file names that are the same as the input file names but in a different dir.

To stay focused just on the shell syntax here,
we won't include code to run an actual bioinformatics tool
(you'll do that in [this week's exercises](w5_exercises.qmd)),
but will use a fictional tool `trimmer`:

```bash
# [Don't run or copy this]

# Define and create an output dir
outdir=results/trimmer
mkdir -p "$outdir"

# Loop over the R1 files - our glob is `*_R1.fastq.gz` to only select R1 files
for R1_in in garrigos_data/fastq/*_R1.fastq.gz; do
    # Get the R2 file name with parameter expansion
    R2_in=${R1_in/_R1/_R2}
    
    # Define the output files (assume that a variable $outdir exists)
    R1_out="$outdir"/$(basename "$R1_in")
    R2_out="$outdir"/$(basename "$R2_in")
    
    # Report
    echo "Input files: $R1_in $R2_in"
    echo "Output files: $R1_out $R2_out"
    
    # Use the imaginary program 'trimmer' with options --in1/--in2 for the R1/R2 input files,
    # and --out1/--out2 for the R1/R2 output files:
    trimmer --in1 "$R1_in" --in2 "$R2_in" --out1 "$R1_out" --out2 "$R2_out"
done
```

<hr style="height:1pt; visibility:hidden;" />

### Converting to the single-sample script format

But wait! Aren't we supposed to write a script that only processes one sample at
a time, and then run/submit that script with a loop?
That's right, so now that we know what to do, let's switch to that setup.

Create a new script `scripts/trim_mock.sh` and paste the following code into it:

```bash
#!/bin/bash
set -euo pipefail

# Copy the placeholder variables
R1_in=$1
outdir=$2

# Create the output dir if needed
mkdir -p "$outdir"

# Infer the R2_in file name
R2_in=${R1_in/_R1/_R2}
    
# Define the output file names
R1_out="$outdir"/$(basename "$R1_in")
R2_out="$outdir"/$(basename "$R2_in")

# Initial reporting
echo "# Starting script trim_mock.sh"
date
echo "# Input R1 file:       $R1_in"
echo "# Input R2 file:       $R2_in"
echo "# Output R1 file:      $R1_out"
echo "# Output R2 file:      $R2_out"
echo

# Mock-run the tool: I preface the command with 'echo',
# so it will just print the commands (instead of trying to run a non-existing program)
echo trimmer --in1 "$R1_in" --in2 "$R2_in" --out1 "$R1_out" --out2 "$R2_out"

# Final reporting
echo
echo "# Done with script trim_mock.sh"
date
```

Now, add the following code to your `run.md` file, and run the code in it:

````markdown
- Step 2: run the trim_mock.sh script for each _sample_.
  We will loop over R1 files only and let the script infer the corresponding
  R2 file name:

```bash
for R1_in in garrigos_data/fastq/*_R1.fastq.gz; do
    bash scripts/trim_mock.sh "$R1_in" results/trim_mock
done
```

````

```bash-out
# Starting script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024
# Input R1 file:       garrigos_data/fastq/ERR10802863_R1.fastq.gz
# Input R2 file:       garrigos_data/fastq/ERR10802863_R2.fastq.gz
# Output R1 file:      results/trim_mock/ERR10802863_R1.fastq.gz
# Output R2 file:      results/trim_mock/ERR10802863_R2.fastq.gz

trimmer --in1 garrigos_data/fastq/ERR10802863_R1.fastq.gz --in2 garrigos_data/fastq/ERR10802863_R2.fastq.gz --out1 results/trim_mock/ERR10802863_R1.fastq.gz --out2 results/trim_mock/ERR10802863_R2.fastq.gz

# Done with script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024

# Starting script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024
# Input R1 file:       garrigos_data/fastq/ERR10802864_R1.fastq.gz
# Input R2 file:       garrigos_data/fastq/ERR10802864_R2.fastq.gz
# Output R1 file:      results/trim_mock/ERR10802864_R1.fastq.gz
# Output R2 file:      results/trim_mock/ERR10802864_R2.fastq.gz
# [...output truncated...]
```

<br>

## At-home reading: Script arguments and hard-coding

We've been writing shell scripts that accept arguments,
instead of including variable things like inputs and outputs in the scripts themselves.
The latter method can be referred to as "hard-coding" these items.
  
You can also use arguments for _settings_ like bioinformatics program options
you may want to vary among different runs of the script,
or relatedly, for information about your data like read length or RNA-seq library
strandedness (as you did in last week's exercises).
If you don't hard-code these options in your script but have arguments for them,
it will be easier to re-use your script in different contexts.

But there is balance to be struck here, and you can also "hobble" your script
with a confusing array of arguably too many arguments.
Along those lines, here are two things to consider:

- When you do hard-code potentially variable things in your script,
  it can be a good idea to define them clearly **at the top of your script**.
  For example:
  
  ```bash
  # Settings and constants
  WORKFLOW_DIR=software/nfc-rnaseq/3_14_0
  ```

  Such variables can be referred to as "constants", since they are hard-coded
  in the script, and in shell code, ALL-CAPS is regularly used for them^[
  But this is far from universal. It is also fairly common to use all-caps
  for all shell variables, but this is not what we've been doing.].

- It is also possible to make your shell script accept _options_.
  The example below uses both long and short options (e.g. `-o | --outdir`).
  It also uses "flag" options that turn functionality on/off (e.g. `--no_gcbias`)
  and options that take arguments (e.g. `--infile`).

  ```bash
  # Process command-line options
  while [ "$1" != "" ]; do
      case "$1" in
          -o | --outdir )     shift && outdir=$1 ;;
          -i | --infile )     shift && infile=$1 ;;
          --transcripts )     shift && transcripts=$1 ;;
          --no_gcbias )       gcbias=false ;;
          --dl_container )    dl_container=true ;;
          -h | --help )       script_help; exit 0 ;;
          -v | --version )    echo "Version 2025-10-01" && exit 0 ;;
          * )                 echo "Invalid option $1" && exit 1 ;;
      esac
      shift
  done
  ```
  
  Such a script could for example be run like so:
  
  ```bash
  sbatch scripts/salmon.sh -i my.bam -o results/salmon --no_gcbias
  ```
  
  That's more readable less error-prone than "anonymous" positional arguments.
  It also makes it possible to add several/many settings that have defaults ---
  when a script only takes arguments, all of them always need to be provided.
  
