---
title: "Week 5: Data and software management (at OSC)"
date: 2025-09-22
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
other-links:
  - text: "Week 5 exercises"
    icon: pencil
    href: w5_exercises.html
  - text: "w5-1: OSC part II"
    icon: bookmarks
    href: w5_1_osc.html
  - text: "w5-2: Data management"
    icon: bookmarks
    href: w5_2_data-management.html
  - text: "w5-3: Software management"
    icon: bookmarks
    href: w5_3_software.html
  - text: "Bonus: Conda"
    icon: book
    href: ../bonus/conda.html
  - text: "Bonus: SSH connections & file transfer"
    icon: book
    href: ../bonus/ssh-and-transfer.html
---

---------

<br>

:::callout-caution
#### THIS PAGE IS STILL UNDER CONSTRUCTION
:::

<br>

## Content overview

This week, we'll start with an introduction to OSC and supercomputers.
Then, we'll see how we can submit shell scripts to OSC's queue for compute jobs
with the widely-used Slurm resource manager.
Finally, we will learn about installing and managing software with Conda,
and loading pre-installed software with the "module" system.

**Some of the things you will learn this week:**

- When and why we need to run our analyses on supercomputers.
- Key terminology around supercomputers.
- Different ways to access and transfer data to and from OSC.
- Different ways to start "compute jobs":
  via OnDemand, with interactive jobs, and with scripts.
- Some strategies around requesting appropriate resources for your compute jobs.
- The Slurm/`sbatch` syntax to request specific resources for your compute jobs.
- How to monitor Slurm jobs.
- How to load pre-installed software at OSC with the "module" system.
- How to install and manage software with Conda.

- Tuesday -- [A closer look at OSC](./w5_1_osc.qmd)
- Tuesday -- [Data transfer and management](./w5_2_data-management.qmd)
- Thursday -- [Software at OSC](w5_3_software.qmd)

<hr style="height:1pt; visibility:hidden;" />

## Exercises & assignments

- [Exercises](./w5_exercises.qmd)

<hr style="height:1pt; visibility:hidden;" />

## Readings

#### Optional readings

- [Buffalo](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507)
  Chapter 4: "Working with Remote Machines"
