---
title: "Reproducibility in (computational) research"
subtitle: "Week 5 - part TBA"
pagetitle: "PRACS25: data management"
date: 2025-09-30
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 5 overview"
    icon: book
    href: w5_overview.html
  - text: "w5-1: OSC part II"
    icon: bookmarks
    href: w5a_osc.html
  - text: "w5-3: Software management"
    icon: bookmarks
    href: w5c_software.html
  - text: "Week 5 exercises"
    icon: pencil
    href: w5_exercises.html
  - text: "Bonus: Conda"
    icon: book
    href: ../bonus/conda.html
  - text: "Bonus: SSH and file transfer"
    icon: book
    href: ../bonus/ssh-and-transfer.html
number-sections: false
editor_options: 
  chunk_output_type: console
bibliography: ../references.bib
---

------

<br>

## Before we start

<hr style="height:1pt; visibility:hidden;" />

## Reproducibility

- <https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-112723-034436>

> To clarify reproducibility further, we can consider Leek & Jager's (2017) review as an example. They summarize the assessment of reproducibility of a scientific study with two questions: “Are code and data both readily available?” and “Does running the provided code exactly produce the study results?” (Leek & Jager 2017, p. 120).

::: callout-note
#### Reproducibility in Plant Pathology

In a special issue of Phytopathology on
"Key Challenges in Plant Pathology in the Next Decade",
@wang2024 noted reproducibility as one of these challenges.

The paper by @grünwald2024 ...

:::

<hr style="height:1pt; visibility:hidden;" />

## Coding best practices

Some practice we have covered or will cover:

- Use a modular approach and limit the scope of individual scripts
- Literate programming (in R)
- Make scripts stop upon error (in the shell)
- Annotate your code
- Use a workflow management system like Nextflow
- Don't repeat yourself --- use loops (esp. shell) and write functions (esp. R)
- Environment management? SessionInfo?

<hr style="height:1pt; visibility:hidden;" />

## Tidy (meta)data

- Spreadsheet recommendations from the Turing Way
- Tidy data
