---
title: "Week 14: RNA-Seq count data analysis in R"
pagetitle: "Week 14 overview"
date: 2025-11-24
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "w14a: RNA-Seq count data analysis in R"
    icon: bookmarks
    href: w14a_deseq.html
  - text: "Week 14 exercises"
    icon: pencil
    href: w14_exercises.html
  - text: "Final Project progress report"
    icon: pencil
    href: ../finalproj/FP2_draft.html
---

--------------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This is the final lecture of the R program.
This week, we will cover the use of the **DESeq2 package** to identify differentially expressed genes (both 
up-regulated and down-regulated). We will begin by learning how to create a `DESeq2 object`, which consists of 
three key components: `metadata`, `count table`, and `statistical design`. After that, we will perform 
`differential expression analysis` and visualize the results using a `volcano plot`.

## Lectures & Learning goals

Some of the things you will learn this week:

#### [RNA-Seq count data analysis in R](./w14a_deseq.qmd)

- Create an R object that also incorporates the metadata
- Perform exploratory data analysis including a PCA
- Run a Differential Expression (DE) analysis
- Extract and visualize the DE results

## Assignments and exercises

- [**Final Project progress report**](../finalproj/FP2_draft.qmd) [_(Due 12/01)_]{style="color:#bb0000"}
- [Exercises for this week](./w14_exercises.qmd)

## Further resources
