---
title: "Week 12: Quarto"
pagetitle: "Week 12 overview"
date: 2025-11-08
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
other-links:
  - text: "w12a: Quarto"
    icon: bookmarks
    href: w11a_r-basics.html
  - text: "Week 12 exercises"
    icon: pencil
    href: w12_exercises.html
  - text: "Final Project Proposal"
    icon: pencil
    href: ../finalproj/FP1_proposal.html
---

------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week we will introduce the basics of [Quarto](https://quarto.org/). 
Quarto is an extension of Markdown that allows to combine **YAML header**, **code chunks** and **text**. 
We will create Quarto documents, use several options to
display/hide codes and figures, and render your Quarto source document
to an output HTML document.

## Lectures & Learning goals

Some of the things you will learn this week:

#### [Introduction to Quarto](./w12a_quarto.qmd)

-   Basics of **Quarto (syntax and formats)**
-   How to create and render a Quarto document in RStudio
-   Understand three components of Quarto ; **YAML header, code chunks and text**

## Assignments and exercises

- [**Final Project proposal**](../finalproj/FP1_proposal.qmd) [_(Due 11/16)_]{style="color:#bb0000"}
- [Exercises for this week](./w12_exercises.qmd)

## Further resources

TBA

