---
title: "Week 12 Exercises: Quarto document"
pagetitle: "Week 12 Exercises"
date: 2025-11-10
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
editor_options: 
  chunk_output_type: console
---

------------------------------------------------------------------------

<br>

## Setting up

- At <https://ondemand.osc.edu>, start a new RStudio session
  ([Starting an RStudio Server session at OSC](../week11/w11a_r-basics.html#starting-an-rstudio-server-session-at-osc)).

- Switch to your `week11` RStudio Project
  ([Working directory and RStudio Projects](../week11/w11a_r-basics.html#Working-directory-and-RStudio-Projects))

- Create a new directory `week12` in your home directory using function
  `dir.create("week12")`
  
- Open a new `Quarto file` in RStudio:
  `File` -> `New File` -> `Quarto Documents` and save the file as 
  `w12_exercises.qmd` (inside `week12`). You will write your answers 
  to the questions below in this Quarto file

## Exercise

1.  Create a PDF by saving the Quarto(.qmd) file you created to save
    your script.
    
2.  Add the following to the YAML header of your Quarto document:
    -   Author name
    -   Date
    -   Table of contents
    -   Theme
    
3.  Load the package `palmerpenguins` installed in `week11` exercise and
    save the `penguins` data in a object called penguin_data.
    
4.  Create a scatter plot of `flipper_length_mm` (x-axis) and
    `body_mass_g` (y-axis) colored by `species` using `ggplot2` package.
    
5.  Customize the figure by adding figure caption, changing the figure
    dimensions (height and width) and aligning it to the center.
    
6.  Add a text section explaining the figure you created above.
