---
title: "R + Markdown with Quarto"
subtitle: "Week 12 -- Lecture A"
pagetitle: "w12a: Quarto"
date: 2025-11-08
author:
  - name: Menuka Bhandari
    #orcid: TBA
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
editor_options: 
  chunk_output_type: console
other-links:
  - text: "Week 12 overview"
    icon: book
    href: w12_overview.html
---

--------------------------------------------------------------------------------

<br>

:::callout-caution
#### THIS PAGE IS STILL UNDER CONSTRUCTION

- Use these as inspiration:
  - <https://osu-codeclub.github.io/posts/S10E01_reprod_01/>
  - <https://osu-codeclub.github.io/posts/S10E02_reprod_02/>
  - <https://biodash.github.io/codeclub/07_rmarkdown/>
:::

## Introduction

### Overview 
This session introduces [Quarto](https://quarto.org/)


### Learning goals
In this session, you will learn:
- Basics of Quarto
- Explore Quarto features

Quarto is the next-generation version of R Markdown that allows to combine prose, code, 
results. Quarto is not limited to single programming language but is available in R, Python, 
Julia and Observable. Here, we will learn to use it in RStudio.
Quarto documents are reproducible and support different output formats 
such as PDFs, Word files, presentations.

Advantages of using Quarto:
1. Communicate with your collaborator: It includes code, results and steps
2. Supports multiformat outputs such as HTML, PDF, Markdow, websites and more
2. Reproducibility of research

### Components of Quarto
1. YAML header
2. Text
3. Code chunks

### Open a new Quarto document in Rstu

### YAML header
The header for the Quarto document is written in YAML language. It consists of series of metadata.







Render a Quarto document:
Rendering a Quarto document help to convert the requested format.




