---
title: "Bioconductor: R for omics data"
subtitle: "Week 13 -- lecture B"
pagetitle: "w13a: Bioconductor"
date: 2025-11-15
author:
  - name: Menuka Bhandari
    #orcid: 0000-0002-3514-7462
    email: bhandari.72@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
editor_options: 
  chunk_output_type: console
other-links:
  - text: "Week 13 overview"
    icon: book
    href: w13_overview.html
  - text: "w13b: Bioconductor: R for omics data"
    icon: bookmarks
    href: w13b_bioconductor.html
execute:
  eval: false
---

--------------------------------------------------------------------------------

<br>

## Introduction
R packages are available in many places. In our previous lecture, we learnt to install R packages through CRAN using `install.packages()` function.
In this lecture, we will learn about [Bioconductor](https://bioconductor.org/), a specialized repository
for **bioinformatics packages in R** that focuses on analysis of high-throughput genomic data. 
Initially developed for the analysis of microarray data, Bioconductor packages 
are used to analyze
a wide range of omics data types such as bulk and single-cell RNA-seq, ChIP seq, copy number analysis, 
microarray methylation and 
classic expression analysis,  flow cytometry, and many other domains. 
One of the key requirement of Bioconductor packages is to have high level documentation,
and workflows. The packages available in Bioconducter are provided [here](https://bioconductor.org/packages/release/BiocViews.html#___Software).

There are 4 different types of software packages available in Bioconducter:
1. Software packages for the analysis and comprehension of high-throughput genomic data.
2. Annotation data packages that provide mappings between different biological identifiers and genomic coordinates.
3. Experiment data packages that contain example datasets for testing and demonstrating analysis methods.
4. Workflows and vignettes that provide step-by-step guides for common bioinformatics analyses.

BioConductor delivers releases where a set of packages is published at once and intended for 
compatibility only with a certain version of R. This is in contrast to CRAN where 
packages are added continuously with no reference to particular versions of R.

Bioconductor Help

1. Bioconductor Packages

2. biocViews

3. Bioconductor Forums




Bioconducter page provide guidance on package acquisition,
create the documents that are computable and better software engineering.

## Install Bioconductor packages

Similar to CRAN, Bioconductor packages needs to be installed once.  However, packages are installed slightly differently in Bioconductor.
To install Bioconductor packages, you first need to install the `BiocManager` package from
CRAN (if you haven't already done so). You can then use `BiocManager::install()` to install
specific Bioconductor packages.

### install BiocManager through which we can install Bioconductor packages
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
    
### install a Bioconductor package, e.g., GenomicRanges
BiocManager::install("DECIPHER")

### Load the DECIPHER package
library(DECIPHER)

BiocManager::install(update = TRUE, ask = FALSE)

::: {.callout-tip}
## Package movement from CRAN and Bioconductor

Packages can become available on CRAN after being available in Bioconductor and viceversa.
what is the reason for it
`vcfR` package was first available in 
:::








this lecture, we will introduce you to Bioconductor, a powerful 
open-source software project that provides tools for the analysis and 
comprehension of high-throughput genomic data.

Bioconductor is a source project and repository for bioinformatics packages
in the R programming language. Since its start in 2001, Bioconductor package has grown 
to include more than 2000 packages contributed by a diverse community of researchers worldwide. 
The latest release of Bioconductor (version 3.22, released in October 2025) is compatible with R version 4.5.0.

## What type of packages are available in Bioconducter?
Bioconductor hosts a wide variety of packages that cater to different aspects of bioinformatics and computational biology. 

Some of the main types of packages available in Bioconductor include:

1. Software packages for the analysis and comprehension of high-throughput genomic data.
2. Annotation data packages that provide mappings between different biological identifiers and genomic coordinates.
3. Experiment data packages that contain example datasets for testing and demonstrating analysis methods. 
4. Workflows and vignettes that provide step-by-step guides for common bioinformatics analyses.



Bioconductor

Package is extension of CRAN R packages and provides specialized data structures 
and functions for handling biological data types such as DNA sequences, gene expression data, and genomic annotations.
Bioconducter was started to write the high level documentation,
create the documents that are computable and better software engineering.
Biocondcuter page provide guidance on package acquisition,
methods of learning, approach to use and development.

BiocViews: task view for package discovery
BiocViews is a controlled vocabulary for describing the content and functionality of Bioconductor packages.
### Overview & learning goals

In this lecture, you will learn ...
- Commonly used packages for understanding the structure of biological data
- How to install and load Bioconductor packages

Specifically, you will learn:

- TBA
- TBA

### Setting up

1. At <https://ondemand.osc.edu>,
   start an RStudio session like in the previous lecture _LINK TBA_
2. Switch to your `week11` RStudio Project ... TBA
3. Open a new R Script and save it as ... TBA









## Example packages

Maybe view an alignment with `DECIPHER`?

## Bioconductor objects can be complex


## WE will work on the Bioconducter packager DESEQ2 in the next lecture
