---
title: "Removed"
---

## Bonus material

### 1.4.3 – The trouble with spaces

Because spaces are special characters used to separate commands from options and
arguments, etc., using them in file names is inconvenient at best:

```bash
# You should be in /fs/ess/PAS2700/users/$USER/CSB/unix/sandbox
ls

cd Papers and reviews     # NOPE!

cd Papers\ and\ reviews   # \ to escape each individual space
cd "Papers and reviews"   # Quotes to escape special characters
```

We'll talk more about spaces and file names in week 2.

### 1.6.2 – `uniq -c`

Use `uniq -c` to count occurrences of each unique value (more on this in week 4):

```bash
cut -d ";" -f 2 Pacifici2013_data.csv | tail -n +2 | sort | uniq -c
```
```bash-out
   54 Afrosoricida
  280 Carnivora
  325 Cetartiodactyla
 1144 Chiroptera
   21 Cingulata
```

```bash
cut -d ";" -f 2 Pacifici2013_data.csv | tail -n +2 | sort | uniq -c | sort -nr
```
```bash-out
 2220 Rodentia
 1144 Chiroptera
  442 Eulipotyphla
  418 Primates
```

<hr style="height:1pt; visibility:hidden;" />

### 1.6.3 – Building a Unix pipeline with `tr` and others

Let's say we want a list of animals sorted by body weight...

```bash
cd ../sandbox/
tail -n +2 ../data/Pacifici2013_data.csv
```

In the following commands, we will build up our "pipeline".

First, we print the file with the exception of the first line (`tail -n +2`)
and then pipe that into `cut` to select the columns of interest ---
and to check our partial pipeline, end with a `head` command to only print the first lines:

```bash
# Using head just to check the output
tail -n +2 ../data/Pacifici2013_data.csv |
    cut -d ";" -f 5-6 | head
```

Second, we'll add a `tr` command to change the column *delimiter*:

```bash
tail -n +2 ../data/Pacifici2013_data.csv |
    cut -d ";" -f 5-6 | tr ";" " " | head
```

Finally, we'll sort in reverse numerical order with `sort`,
and redirect the output to a file:

```bash
tail -n +2 ../data/Pacifici2013_data.csv |
    cut -d ";" -f 5-6 | tr ";" " " | sort -r -n -k 3 > BodyM.csv
```

Let's take a look at the output:

```bash
head BodyM.csv
```

<hr style="height:1pt; visibility:hidden;" />

