---
title: "Unix shell basics"
pagetitle: "PRACS25: Shell Basics"
date: 2025-09-04
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
other-links:
  - text: Week 2 overview
    icon: book
    href: w2_overview.html
  - text: Week 2 assignment
    icon: pencil
    href: w2_ga_markdown.html
  - text: "w2-1: Project organization"
    icon: bookmarks
    href: w2_1_project-org.html
  - text: "w2-2: VS Code & Markdown"
    icon: bookmarks
    href: w2_2_vscode-markdown.html
editor_options: 
  chunk_output_type: console
---

--------------------------------------------------------------------------------

<br>

## Introduction

### Learning goals

In this session, you'll learn:

- What the Unix shell is and what you can do with it
- Why it can be beneficial to use a command-line interface in general and the shell specifically
- How Unix commands are stuctured
- How to navigate around your computer with Unix commands
  
### Some terminology and concepts

#### Unix (vs. Linux)

We can think of Unix (or "Unix-like" / "Unix-based")^[
_Technically_, the latter terms are more correct,
as Unix formally does refer to a specific operating system.]
as a **family of operating systems**, which includes Linux and Mac but not Windows.

For scientific computing, Unix-based operating systems are generally preferable.
Supercomputers, like the Ohio Supercomputer Center (OSC), use Linux.
In this course, though, your laptop/desktop can run on any operating system,
precisely because we will connect to OSC and do our work there.

#### Unix shell-related terms

We will be using the Unix shell.
How does that relate to some other terms you may have heard of?

- **Command Line** and **Command Line Interface (CLI)** — A user interface where you type commands
- **Shell** — a more specific and technical term for a command line interface _to your computer_
- **Unix shell** — the type of shell on Unix-based (Linux + Mac) computers
- **Bash** — the specific Unix shell _language_ that is most common
- **Terminal** — the program/app/window that can run a shell

While these are clearly not synonyms, in day-to-day computing,
they are often used interchangeably.

::: callout-note
#### CLI vs. GUI
Instead of a Command-line Interface (CLI),
most programs that we use on a day-to-day basis have a Graphical User Interface (GUI),
which are operated mostly by pointing and clicking rather than typing.
:::

<hr style="height:1pt; visibility:hidden;" />

### Why use the Unix shell?

The Unix shell has been around for a long time and may seem a bit archaic.
But astonishingly, a system largely built decades ago in an era with very
different computers and datasets has stood the test of time,
and the ability to use it is a crucial skill in applied bioinformatics.

Specifically, you may want to or need to use the Unix shell as opposed to
programs with Graphical User Interfaces (GUIs) because of:

- **Software needs**\
  When working with omics data, we don't code our entire analysis from scratch --
  for example, we don't build our own genome assembly or read alignment algorithm.
  Many of the external tools that we use for this are run in the shell with
  a Command-Line Interface (CLI).
- **Automation and fewer errors**\
  The shell allows you to repeat and automate tasks easily and without
  introducing errors.
- **Reproducibility**\
  It's more straightforward to keep a detailed record of what you have done.
- **Working with large files**\
  Shell commands are really good at processing _large, plain-text files_,
  which are very common in omics data.
- **Remote computing – especially supercomputers**\
  It is often only possible to work in a shell when doing remote computing.

But what about versus other coding languages?
Why do we need to know the Unix shell on top of R and/or Python?

- **Efficiency**\
  For many _simpler_ tasks, built-in shell tools are faster ---
  in terms of coding time, processing time,
  and the ease of working with very large files.
- **Running external software**\
  As mentioned above,
  we need to use many external programs with a CLI in omics data analysis.
  While those _can_ be called from within other languages,
  the shell has a _direct_ interface to them and is therefore often preferred.

<br>

## First steps in the shell

### Accessing a shell within VS Code

If you don't already have a VS Code session with a Unix shell ---
follow these steps:

1. Log in to OSC's OnDemand portal at <https://ondemand.osc.edu>.
2. In the blue top bar, select `Interactive Apps` and near the bottom, click `Code Server`.
3. In the form on the page that appears, fill out the following:
   - "_Cluster_": `pitzer-rhel9`
   - "_Account_" (= OSC Project): `PAS2880`.
   - "_Number of hours_": `2`
   - **"_Working Directory_": your personal dir in `/fs/ess/PAS2880/users`**
     (e.g. `/fs/ess/PAS2880/users/jelmer`) --
     this is different from what we did last time
   - "_App Code Server version_": `4.8.3`
4. Click `Launch`
5. Once the blue *Connect to VS Code* button appears,
   click that to open VS Code in a new browser tab.
6. In VS Code, open a terminal with a Unix shell by either:
   - Clicking   {{< fa bars >}}   =\> `Terminal` =\> `New Terminal`
   - Using the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>`</kbd>

I also recommend that you create and open a Markdown file to keep notes on
what we're doing in this session:

1. Click <i class="fa fa-bars"></i> => `File` => `New File`.
2. Save the file (e.g. <kbd>Ctrl/⌘</kbd>+<kbd>S</kbd>) inside the `week02` subdir,
   e.g. as `session3_shell-intro.md`.

<hr style="height:1pt; visibility:hidden;" />

### The shell's prompt

Inside your terminal, the "prompt" indicates that the shell is ready for a
command. What is shown exactly varies across shells and can also be customized,
but our prompts at OSC should show the following information:

`[<username>@<node-name> <working-dir>]$`

For example:

``` bash-in-nocolor
[jelmer@p0362 jelmer]$ 
```

The `<working-dir>` part only shows the name of the directory you are directly
located in, and doesn't give the entire path (`/fs/ess/PAS2880/users/jelmer`).

We type our commands after the dollar sign `$`,
and then press <kbd>Enter</kbd> to execute the command.
When the command has finished executing,
we'll get our prompt back and are able to type and execute a new command.

::: callout-tip
#### Clear the screen with <kbd>Ctrl</kbd>+<kbd>L</kbd>
OSC prints welcome messages and storage quota information when you open a shell.
To reduce the amount of text on the screen, I will **clear** the screen now and regularly throughout.
This can be done with the keyboard shortcut **<kbd>Ctrl</kbd>+<kbd>L</kbd>**.
:::

<hr style="height:1pt; visibility:hidden;" />

### A few simple commands: `date` and `pwd`

The Unix shell comes with hundreds of "commands":
small programs that perform specific actions.
(If you're familiar with R or Python,
a Unix *command* is like an R/Python *function*.)

Let's start with a few simple commands:

- The `date` command prints the current date and time:

  ``` bash
  date
  ```
  ``` bash-out
  Thu Sep 02 13:58:19 EST 2025
  ```

- The `pwd` (Print Working Directory) command prints the path to the directory
  you are currently located in:

  ``` bash
  pwd
  ```
  ``` bash-out
  /fs/ess/PAS2880/users/jelmer
  ```

Both of those commands provided us with some output.
That output was **printed to screen**,
which is the default behavior for nearly every Unix command.

<br>

## Options, arguments, and help

### The `cal` command --- and options & arguments

The `cal` command is another example of a command that simply prints some
information to the screen, in this case a calendar.
We'll use it to learn about command *options* and *arguments*.

Invoking `cal` without options or arguments will show a calendar for the current month:

```bash
cal
```
``` bash-out
    February 2024   
Su Mo Tu We Th Fr Sa
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29
```

#### Option examples

Use the *option* `-j` (a dash `-` and then `j`) to instead get a Julian calendar,
in which day numbering is continuous instead of restarting each month:

```bash
# Make sure to leave a space between `cal` and `-j`!
cal -j
```
```bash-out
       February 2024       
Sun Mon Tue Wed Thu Fri Sat
                 32  33  34
 35  36  37  38  39  40  41
 42  43  44  45  46  47  48
 49  50  51  52  53  54  55
 56  57  58  59  60
```

Use the `-3` option to show 3 months (adding the previous and next month):

```bash
cal -3
```
``` bash-out
    January 2024          February 2024          March 2024     
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
    1  2  3  4  5  6               1  2  3                  1  2
 7  8  9 10 11 12 13   4  5  6  7  8  9 10   3  4  5  6  7  8  9
14 15 16 17 18 19 20  11 12 13 14 15 16 17  10 11 12 13 14 15 16
21 22 23 24 25 26 27  18 19 20 21 22 23 24  17 18 19 20 21 22 23
28 29 30 31           25 26 27 28 29        24 25 26 27 28 29 30
                                            31   
```

We can combine multiple options -- for example:

```bash
cal -j -3
```
``` bash-out
        January 2024                February 2024                  March 2024        
Sun Mon Tue Wed Thu Fri Sat  Sun Mon Tue Wed Thu Fri Sat  Sun Mon Tue Wed Thu Fri Sat
      1   2   3   4   5   6                   32  33  34                       61  62
  7   8   9  10  11  12  13   35  36  37  38  39  40  41   63  64  65  66  67  68  69
 14  15  16  17  18  19  20   42  43  44  45  46  47  48   70  71  72  73  74  75  76
 21  22  23  24  25  26  27   49  50  51  52  53  54  55   77  78  79  80  81  82  83
 28  29  30  31               56  57  58  59  60           84  85  86  87  88  89  90
                                                           91 
```

Handily, options can be "pasted together" like so (output not shown - same as above):

```bash
cal -j3
```

#### Options summary

As we've seen, options are specified with a dash `-`
(or to dashes `--`, as you'll see later).
So far, we've only worked with the type of options that are also called "**flags**",
_which change some functionality in an ON/OFF type way_:

- Turning a Julian calender display ON with `-j`
- Turning a 3-month display ON with `-3`.

Generally speaking, we can say that options **change the behavior** of a command.

#### Arguments

Whereas options change the behavior of a command,
arguments typically tell the command **what to operate on**.
Most commonly, these are file or directory paths.

Admittedly, the `cal` command is not the best illustration of this pattern ---
when you give it one argument, this should be the year to show a calendar for:

```bash
cal 2020
```
```bash-out
                              2020                               

       January               February                 March       
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
          1  2  3  4                      1    1  2  3  4  5  6  7
 5  6  7  8  9 10 11    2  3  4  5  6  7  8    8  9 10 11 12 13 14
12 13 14 15 16 17 18    9 10 11 12 13 14 15   15 16 17 18 19 20 21
19 20 21 22 23 24 25   16 17 18 19 20 21 22   22 23 24 25 26 27 28
26 27 28 29 30 31      23 24 25 26 27 28 29   29 30 31

# [...output truncated, entire year is shown...]
```

We'll see some examples of commands operating on files or dirs later.
Finally, we can also _combine_ options and arguments:

```bash
cal -j 2020
```
```bash-out
                            2020                          

          January                       February         
Sun Mon Tue Wed Thu Fri Sat   Sun Mon Tue Wed Thu Fri Sat
              1   2   3   4                            32
  5   6   7   8   9  10  11    33  34  35  36  37  38  39
 12  13  14  15  16  17  18    40  41  42  43  44  45  46
 19  20  21  22  23  24  25    47  48  49  50  51  52  53
 26  27  28  29  30  31        54  55  56  57  58  59  60
 
# [...output truncated, entire year is shown...]
```
  
To summarize, different from options, _arguments_ to a command:

- Are not preceded by a `-` (or `--`)
- If options and arguments are combined, arguments **come after** options^[
  Though some commands are flexible and accept either order.].

::: callout-warning
#### TBA: Command structure visualization
:::

<hr style="height:1pt; visibility:hidden;" />

### Getting help

Many basic Unix commands – *and other command-line programs!* –
have a **`-h`** option for help,
which usually gives a concise summary of the command's "syntax",
i.e. its available options and arguments:

```bash
cal -h
```
```bash-out

Usage:
 cal [options] [[[day] month] year]

Options:
 -1, --one        show only current month (default)
 -3, --three      show previous, current and next month
 -s, --sunday     Sunday as first day of week
 -m, --monday     Monday as first day of week
 -j, --julian     output Julian dates
 -y, --year       show whole current year
 -V, --version    display version information and exit
 -h, --help       display this help text and exit
```

In this case, each option can be referred to in two ways:

- A short-form notation: a single dash followed by a single character (e.g. `-s`)
- A long-form notation: two dashes followed by a word (e.g. `--sunday`)

::: {.callout-note collapse="true"}
### Another way to see documentation: the `man` command _(Click to expand)_
An alternative way of getting help for Unix commands is with the `man` command:

```bash
man cal
```

This manual page often includes a lot more details than the `--help` output,
and it is opened inside a "pager" rather than printed to screen:
type **<kbd>q</kbd>** to exit the pager that `man` launches.
:::

::: exercise
#### {{< fa user-edit >}} Exercise: Interpreting the help output

- Look through the options listed when you ran `cal -h`, and try an option we
  haven't used yet.
  (You can also combine this new option with other options, if you want.)

<details><summary>*Click to see the solution*</summary>

```bash
# Print a calendar with Monday as the first day of th week (instead of the default, Sunday) 
cal -m
```
```bash-out
    February 2024   
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29
```

</details>

- Try using one or more options in their "long form" (with `--`).
  Why would those be useful?

<details><summary>*Click to see the solution*</summary>

For example:

```bash
cal --julian --monday
```
```bash-out
       February 2024       
Mon Tue Wed Thu Fri Sat Sun
             32  33  34  35
 36  37  38  39  40  41  42
 43  44  45  46  47  48  49
 50  51  52  53  54  55  56
 57  58  59  60
```

The advantage of using long options is that they are less cryptic and more descriptive.
Therefore, it is much more likely that any reader of the code
(including yourself next week) will immediately understand what these options are doing.

Note that long options **cannot** be "pasted together" like short options.

</details>

------

- **_Bonus_**: Try to figure out / guess what the meaning is of the top of the help text:
  `Usage: cal [options] [[[day] month] year]`.
  Based on that, can you print a calendar for April 2017?

<details><summary>*Click to see the solution*</summary>

First of all, the square brackets around `options` and all of the possible arguments
means that _none of these are required_ ---
as we've seen, just `cal` (with no options or arguments) is a valid command.

The structure of the multiple square brackets around the day-month-year arguments indicate that:

- _If_ you provide only one argument, it should be a year
- _If_ you provide a second argument, it should be a month
- _If_ you provide a third argument, it should be a day

Therefore, to print a calendar for April 2017:

```bash
cal 4 2017
```
```bash-out
     April 2017     
Su Mo Tu We Th Fr Sa
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30
```

</details>
:::

<br>

## Environment variables

You may be familiar with the concept of **variables** from previous experience
with perhaps R or another language.
Variables can hold values and other pieces of data and are essential in programming.

**Environment variables** are pre-existing variables that have been
automatically assigned values.
Two examples:

```bash
# $HOME contains the path to your Home dir:
echo $HOME
```
```bash-out
/users/PAS0471/jelmer
```

```bash
# $USER contains your user name:
echo $USER
```
```bash-out
jelmer
```

By the way, `echo` can also print literal text (as shown below) or combinations
of literals and variables (next exercise):
    
```bash
echo "Welcome to PLNTPTH 5004"
```
```bash-out
Welcome to PLNTPTH 5004
```

::: exercise
#### {{< fa user-edit >}} Exercise: environment variables

Using an environment variable,
print "_Hello, my name is \<your username\>_" (e.g. "Hello, my name is natalie").

<details><summary>*Click for the solution*</summary>

``` bash
# (This would also work without the " " quotes)
echo "Hello, my name is $USER"
```
``` bash-out
Hello, my name is jelmer
```
</details>
:::

<br>

## Navigation and keyboard shortcuts

### `cd` and command "actions"

All the commands so far "merely" provided some information,
which was printed to the screen.

But many commands perform another kind of **action**.
For example, the command **`cd`** will change your *working* directory.
And like many commands that perform a potentially invisible action,
`cd` normally has **no output** at all.

First, check again where you are ---
you should be in your personal dir within `/fs/ess/PAS2880/users`:

```bash
pwd
```
```bash-out
/fs/ess/PAS2880/users/jelmer
```

Now, let's use `cd` to move to another directory by specifying the *path* to that
directory as an argument:

``` bash
cd /fs/ess/PAS2880
```

```bash
# Double-check that you moved:
pwd
```
``` bash-out
/fs/ess/PAS2880
```

In summary:

- Like `cal`, `cd` accepts an argument. Unlike `cal`, this argument takes the form
  of a path that the command should operate on, which is much more typical.
- `cd` gives no output when it successfully changed the working directory.
  This is very common behavior for Unix commands that perform
  operations: **when they succeed, they are silent**.

Let's also see what happens when `cd` does not succeed — it gives an error:

  ``` bash
  cd /fs/ess/PAs2880
  ```
  
  ``` bash-out
  -bash: cd: /fs/ess/PAs2880: No such file or directory
  ```

<hr style="height:1pt; visibility:hidden;" />

::: callout-note
#### Case-sensitivity and comments

- Everything in the shell (and in coding in general) is **case-sensitive**,
  including commands and file names --- hence the error above.

- Any text that comes after a **`#`** is considered a **comment** instead of code!
  Comments are not executed but are ignored by the shell. For example:

  ``` bash
  # This entire line is a comment - you can run it and nothing will happen
  pwd    # 'pwd' will be executed but everything after the '#' is ignored
  ```
  ``` bash-out
  /users/PAS0471/jelmer
  ```

<hr style="height:1pt; visibility:hidden;" />
:::

<hr style="height:1pt; visibility:hidden;" />

### Keyboard shortcuts

Using keyboard shortcuts help you work much more efficiently in the shell.
Here are some of the most useful ones:

- **Command history** ---
  `Up` / `Down` arrow keys to cycle through your command history.

- **Tab completion** ---
  The shell will auto-complete partial commands or file paths when you press <kbd>Tab</kbd>.

- **Cancel/stop/abort** --- If your prompt is "missing", the shell is still
  busy executing your command, *or* you typed an incomplete command. To abort,
  press <kbd>Ctrl</kbd>+<kbd>C</kbd> and you will get your prompt back.

::: exercise
#### {{< fa user-edit >}} Exercise: Tab completion & command history

- Type **`/f`** and press <kbd>Tab</kbd> (will autocomplete to */fs/*)

- Add **`e`** (*/fs/e*) and press <kbd>Tab</kbd> (will autocomplete to */fs/ess/*).

- Add **`PAS`** (*/fs/ess/PAS*) and press <kbd>Tab</kbd>. Nothing should
  happen: there are multiple (many!) options.

- Press <kbd>Tab</kbd> <kbd>Tab</kbd> (i.e., twice in quick succession) and it should say:

  ``` bash-out
  Display all 619 possibilities? (y or n)
  ```

- Type `n` to answer no: we don't need to see all the dirs starting with `PAS`.

- Add **`288`** (*/fs/ess/PAS27*) and press <kbd>Tab</kbd>
  **twice in quick succession** (a single Tab won't do anything):
  you should see at least four dirs that start with `PAS288`.

- Add `0` so your line reads `/fs/ess/PAS2880`. Press <kbd>Enter</kbd>.
  You will get the following output, which is an error.
  Can you think of any reason why this you may have gotten an error here?

  ```bash-out-solo
  bash: /fs/ess/PAS2880/: Is a directory
  ```

<details><summary>*Click to see the solution*</summary>
Basically, everything you type in the shell should start with a command.
Just typing a path will not make the shell print some info about, or the contents of,
this dir or file.
Instead, since a path is not a command, you will get an error.
</details>

- Press **<kbd>⇧</kbd>** to get the previous "command" back on the prompt.

- Press **<kbd>Ctrl</kbd>+<kbd>A</kbd>** to move to the beginning of the line at once.

- Add `cd` and a space in front of the dir, and press <kbd>Enter</kbd> again.

  ```bash
  cd /fs/ess/PAS2880/
  ```
  
:::callout-tip  
#### Your **cursor** can be anywhere on a line (not just at the end) when you press <kbd>Enter</kbd> to execute a command!
:::
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: canceling

To simulate a long-running command that we may want to abort, we can use the
`sleep` command, which will make the computer wait for a specified amount of
time until giving your prompt back. Run the below command and instead of waiting
for the full 60 seconds, **press <kbd>Ctrl</kbd> + <kbd>C</kbd>** to get your prompt
back sooner!

``` bash
sleep 60s
```

As another example of a situation where you might have to use
<kbd>Ctrl</kbd> + <kbd>C</kbd>,
simply type an opening parenthesis `(` and press <kbd>Enter</kbd>:

``` bash
(
```

When you do this, nothing is executed and you are not getting your prompt back:
you should see a `>` on the next line.
This is the shell wanting you to "complete" you command. Why would that be?

<details><summary>*Click to see the solution*</summary>
This is an incomplete command by definition because any opening parenthesis
should have a matching closing parenthesis.
</details>

Press <kbd>Ctrl</kbd> + <kbd>C</kbd> to get your regular prompt back.
:::

::: {.callout-note collapse="false"}
#### Table with useful keyboard shortcuts

_(Note that even on Macs, you should use <kbd>Ctrl</kbd> instead of switching them_
_out for <kbd>Cmd</kbd> as you may be used to doing --_
_though in some cases, like copy/paste, both keys work)._

| Shortcut | Function |
|-----|------------|
| <kbd>Tab</kbd> | Tab completion |
| <kbd>⇧</kbd> / <kbd>⇩</kbd> | Cycle through previously issued commands | |
| <kbd>Ctrl</kbd>+<kbd>C</kbd> | Copy selected text | |
| <kbd>Ctrl</kbd>+<kbd>V</kbd> | Paste text from clipboard |
| <kbd>Ctrl</kbd>+<kbd>A</kbd> / <kbd>Ctrl</kbd>+<kbd>E</kbd> | Go to beginning/end of line |
| <kbd>Ctrl</kbd>+<kbd>U</kbd> /<kbd>Ctrl</kbd>+<kbd>K</kbd> | Cut from cursor to beginning / end of line |
| <kbd>Ctrl</kbd>+<kbd>W</kbd> | Cut word before before cursor |
| <kbd>Ctrl</kbd>+<kbd>Y</kbd> | Paste ("yank") text that was cut with one of the shortcuts above |
| <kbd>Alt</kbd>+<kbd>.</kbd> / <kbd>Esc</kbd>+<kbd>.</kbd>  | Retrieve last argument of previous command (very useful!) (<kbd>Esc</kbd>+<kbd>.</kbd> for Mac) |
| <kbd>Ctrl</kbd>+<kbd>R</kbd> | Search history: press <kbd>Ctrl</kbd>+<kbd>R</kbd> again to cycle through matches, <kbd>Enter</kbd> to put command in prompt. |
| <kbd>Ctrl</kbd>+<kbd>C</kbd> | Cancel (kill/stop/abort) currently active command |
| <kbd>Ctrl</kbd>+<kbd>D</kbd> | Exit (a program or the shell, depending on the context) (same as `exit` command) |
| <kbd>Ctrl</kbd>+<kbd>L</kbd> | Clear the screen (same as `clear` command) |
:::

<hr style="height:1pt; visibility:hidden;" />

### Path shortcuts

- **`~`** (a tilde) --- represents your Home directory.
  For example, `cd ~` moves you to your Home dir.
- **`.`** (a single period) --- represents the current working directory
  (we'll see soon why that can be useful).
- **`..`** (two periods) --- Represents the directory "one level up",
  i.e. towards the computer's root dir.

Some examples of `..`:

- Use `..` to go up one level in the dir hierarchy:

  ```bash
  # Start by reminding yourself of where you are:
  pwd
  ```
  ```bash-out
  /fs/ess/PAS2880
  ```
  ```bash
  # Move one level up:
  cd ..
  
  # Check where you are now:
  pwd
  ```
  ``` bash-out
  /fs/ess/
  ```

- TBA Move up then into a dir


- This pattern can be continued all the way to the root of the computer,
  so `../..` means two levels up:

  ``` bash
  cd ../..
  pwd
  ```
  ``` bash-out
  /
  ```

<hr style="height:1pt; visibility:hidden;" />

::: callout-tip
#### These path shortcuts work with many commands
These are *general shell shortcuts* that work with **any** command that accepts a path/file name.
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: navigation

- **A)** Move back to your personal dir 
  `/fs/ess/PAS2880/users/<user>`

<details><summary>*Click to see the solution*</summary>
``` bash
cd /fs/ess/PAS2880/users/<user>
```
</details>

- **B)** Use a relative path (with `..`) to move into the
  `/fs/ess/PAS2880/share` dir.

<details><summary>*Click to see the solution*</summary>
``` bash
cd ../../share
```
</details>
:::
