---
title: "Week 2 Exercises"
pagetitle: "PRACS25: Week 2 Exercises"
author: Jelmer Poelstra
date: 2025-09-01
number-sections: false
---

---------

<hr style="height:1pt; visibility:hidden;" />

*The solutions are at the bottom of the page.*

<br>

## Getting set up

You should already have the CSB book's GitHub repository with exercise files in
your personal dir within `/fs/ess/PAS2880` from Thursday's class.

::: {.callout-tip collapse="true"}
#### Don't have these files? _(Click to expand)_

1. Go to your personal dir within `/fs/ess/PAS2880`:

```bash
cd `/fs/ess/PAS2880/users/$USER
```

2. Download ("clone") the GitHub repository:

```bash
git clone https://github.com/CSB-book/CSB.git
```
:::

<hr style="height:1pt; visibility:hidden;" />

## Exercise 1: Course notes in Markdown

Create a Markdown document with course notes.
I recommend writing this document in *VS Code*.

Make notes of this week's material in some detail.
If you have notes from last week in another format, include those too.
(And try to keep using this document throughout the course!)

Some pointers:

- Use several header levels and use them consistently: e.g. a level 1 header
  (`#`) for the document's title, level 2 headers (`##`) for each week,
  and so on.

- Though this should foremost be a *functional* document for notes,
  try to incorporate any appropriate formatting option:
  e.g. **bold text**, *italic text*, `inline code`, code blocks,
  ordered/unordered lists, and hyperlinks.

- Make sure you understand and try out how Markdown deals with whitespace,
  e.g. starting a new paragraph and how to force a newline.

<hr style="height:1pt; visibility:hidden;" />

## Exercise 2: Navigation in the Unix shell

**(a)** Go to `/fs/ess/PAS2880/users/$USER`

**(b)** Navigate to the `sandbox` directory within the `CSB/unix` directory.  

**(c)** Use a *relative* path to go to the `data` directory within the `python` directory.  

**(d)** Use an *absolute* path to go to the `sandbox` directory within `CSB/python`.  

**(e)** Return to the `data` directory within the `python` directory.  

<details><summary>Show hints</summary>
We didn't see this in class, but the CSB book (page 21) mentions a shortcut you can use
with `cd` to go back to the dir you were in previously (a little like a Browser's "back" button).
</details>

<br>

## Solutions

### Exercise 2

<details><summary>Solution</summary>

**(a)** ~~Go to your home directory.~~ Go to `/fs/ess/PAS2700/users/$USER`.

```sh
cd /fs/ess/PAS2700/users/$USER # To home would have been: "cd ∼"
```

**(b)** Navigate to the `sandbox` directory within the `CSB/unix` directory.

```sh
cd CSB/unix/sandbox
```

**(c)** Use a *relative* path to go to the `data` directory within the `python`
directory.

```sh
cd ../../python/data
```

**(d)** Use an *absolute* path to go to the `sandbox` directory within `python`.

```sh
cd /fs/ess/PAS2700/users/$USER/CSB/python/sandbox
```

**(e)** Return to the `data` directory within the `python` directory.

- With `cd -`:

```sh
# The '-' shortcut for cd will move you back to the previously visited dir
# (Note: you can't keep going back with this: using it a second time will toggle you "forward" again.)
cd -
```

- Using a relative path:

```bash
cd ../data
```

</details>
