---
title: "Graded Assignment I: Markdown and Unix shell basics"
subtitle: "Week 2 -- due Monday Sept 8 at 10:00 pm"
pagetitle: "PRACS25: GA1"
date: 2025-09-01
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 2 overview"
    icon: book
    href: w2_overview.html
  - text: "w2-1: Project file organization"
    icon: bookmarks
    href: w2a_project-org.html
  - text: "w2-2: Markdown & VS Code"
    icon: bookmarks
    href: w2v_vscode-markdown.html
  - text: "w2-3: Unix shell basics"
    icon: bookmarks
    href: w2c_shell.html
number-sections: false
---

---------

<br>

## Overview

This graded assignment (maximum score: 10 points)
consists of creating two Markdown files:

1. One with notes and reflections on what you learned this week
2. Another that includes Unix shell code to practice with Unix shell basics.

Other general notes:

- You should work on both files in **VS Code at OSC**.
- You should save both files in a dir `week01/GA1` within your personal dir
  at `/fs/ess/PAS2880/users/<user>`.
- The **deadline** is Monday Sept 8 at 10:00 pm.
  You don't need to submit anything or notify the instructors:
  we will look for these files in the appropriate location.
  (We will also be able to see when the files were last modified.)

Specific requirements for the Markdown files ---
include each of the following components in at least one of your files:

- Use several header levels and use them consistently
- Include formatting like **bold text**, *italic text*, `inline code`,
  ordered/unordered lists, and hyperlinks
- Full Unix shell commands, like in Part II, should be in code blocks
  (not in inline code or as regular text)
- A small table
- Make sure you are not messing up whitespace --
  e.g. separate paragraphs as appropriate

<hr style="height:1pt; visibility:hidden;" />

## Part I: A Markdown document with class notes

Write a summary of what you've learned so far in this course.
The summary doesn't need to be comprehensive and can focus on elements that
you think were interesting or make sense to summarize.

The summary should be more wide-ranging than just hitting the below points,
but make sure to highlight:

- Things that you were excited to learn and perhaps things that represented
  an aha-moment of sorts.

- Things that you are (still) confused about.

- Recommendations (e.g., related to project file organization) that you are not
  sure you agree with, are sure you disagree with, or otherwise foresee problems
  with in terms of implementing them in your projects.

(If you really can't think of anything in one of these categories,
you can skip that one.)

<hr style="height:1pt; visibility:hidden;" />

## Part II: A Markdown document with Unix shell exercises

Copy each of the numbered instructions below into your document,
and insert your answers in between.
You'll mostly be inserting code blocks with Unix shell code,
but occassionally also need to enter explanations.

_(Your starting point working dir does not matter.)_

1. Print the location of your Home dir to screen using a
   [path shortcut](./w2c_shell.qmd#path-shortcuts).

2. Navigate to your Home dir using an
   [environment variable](./w2c_shell.qmd#environment-variables).

3. Would you say that you just moved to your Home dir using a relative path
   or using an absolute path? Why?

4. Navigate to `/fs/ess/PAS2880/users/$USER` using a relative path.

5. Type <kbd>"</kbd> (one double-quote character) and press <kbd>Enter</kbd>.
   What is happening, why is that happening, and how can you get out of it?
   
6. Print a Julian calendar for three months using "long-form" options.

7. Do you think you can "paste together" long-form options like you can short-form
   options (e.g., `-j -3` becomes `-j3`)? Test your intuition and report back.

8. Are you currently located on a login node or a compute node? Why?
