---
title: "Week 2: Project organization and Unix shell basics"
pagetitle: "Week 2 overview"
date: 2025-08-29
number-sections: false
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "w2a: Project file organization"
    icon: bookmarks
    href: w2a_project-org.html
  - text: "w2b: Markdown & VS Code"
    icon: bookmarks
    href: w2b_vscode-markdown.html
  - text: "w2c: Unix shell basics"
    icon: bookmarks
    href: w2c_shell.html
  - text: "Week 2 graded assignment"
    icon: pencil
    href: w2_overview.html
bibliography: ../references.bib
---

---------

<br>

## Overview

This week, we will cover best practices for project file organization,
documenting your project with Markdown files,
and the basics of the Unix shell.
You will also get to know VS Code,
a text editor you'll spend a lot of time in during this course.

## Learning goals & lectures

During the week's lecture, you will learn:

#### [**Project file organization**](./w2a_project-org.qmd) _(Tuesday)_

A number of best practices for research project...

- file organization
- file management
- documentation.

#### [**Markdown & VS Code**](./w2b_vscode-markdown.qmd) _(Tuesday/Thursday)_

- How to use Markdown for documentation (and beyond).
- Get to know VS Code, the text editor you'll use throughout the course.

#### [**Unix shell basics**](./w2c_shell.qmd) _(Thursday)_

- What the Unix shell is and what you can do with it
- Why it can be beneficial to use a command-line interface in general,
  and the Unix shell specifically
- How Unix commands are stuctured
- How to navigate around your computer with Unix commands

## Readings

_No required readings,_
_but see the "Further resources" section below for optional readings._

## Assignments & exercises

- **Graded assignment: [Markdown and shell basics](./w2_ga.qmd)** [_(due Sun 09/07)_]{style="color:#bb0000"}

## Further resources

- [Official VS Code introductory video](https://code.visualstudio.com/docs/introvideos/basics)  
  If you watch this, keep in mind that there are slight differences between the
  stand-alone VS Code app demonstrated in the video,
  and the VS Code _Server_ app that you run in your browser via OSC OnDemand.
  For example, there is no "Live Preview" extension for HTML files available
  for VS Code Server.

- @buffalo2015 -- Chapter 2: _Setting up and Managing a Bioinformatics Project_ ([OSU library link](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507))

- @allesina2019 -- Chapter 1: _Unix_ ([OSU library link](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085456156508507))

- @noble2009: _A quick guide to organizing computational biology projects_

- @wilson2017: _Good enough practices in scientific computing_

- [Official Markdown documentation](https://www.markdownguide.org)
