---
title: "Unix shell basics"
subtitle: "Week 2 -- Lecture C"
pagetitle: "w2c: Shell Basics"
date: 2025-08-29
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 2 overview"
    icon: book
    href: w2_overview.html
  - text: "w2a: Project organization"
    icon: bookmarks
    href: w2a_project-org.html
  - text: "w2b: VS Code & Markdown"
    icon: bookmarks
    href: w2b_vscode-markdown.html
  - text: "Week 2 graded assignment"
    icon: pencil
    href: w2_ga.html
editor_options: 
  chunk_output_type: console
---

--------------------------------------------------------------------------------

<br>

## Introduction

### Context & overview

You'll be using the Unix shell very regularly throughout the rest of this course.
Several lectures focus on learning different aspects of the shell, starting with this one.

### Learning goals

In this lecture, you'll learn:

- What the Unix shell is and what you can do with it
- Why it can be beneficial to use a command-line interface in general and the shell specifically
- How Unix commands are stuctured
- How to navigate around your computer with Unix commands

## The Unix shell

### Some terminology and concepts

#### Unix (vs. Linux)

Unix-like or Unix-based operating systems include MacOS and Linux but not Windows.

For scientific computing, Unix-based operating systems are generally preferable.
Linux specifically, while not as familiar to the general public,
is what supercomputers like those of OSC,
and most servers throughout the world run on.

::: {.callout-note appearance="simple"}
Don't be alarmed if you have a Windows laptop/desktop.
Certainly for the purposes of this course,
and in principle for your other research,
your computer can run on any operating system,
because you can connect to OSC and do your work there.
:::

#### Unix shell-related terms

This session introduces the "Unix shell".
How does that relate to some other terms you may have heard of?
Let's run by these terms going from more general ones to more specific ones:

| Term | Explanation
|----|----------|
| **Command Line** /<br>**Command Line Interface (CLI)** |   A user interface where you **type commands** rather than clicking-and pointing like you would in a _Graphical User Interface (GUI)_. This could "interface" to anything from a specific program to your computer. |
| **Shell** | A more specific and technical term for a command line interface _to your computer_
| **Unix shell** |The type of shell on Unix-based (Linux + Mac) computers
| **Bash** | A specific Unix shell _language_ (the most common one)

: {.striped .hover}

<hr style="height:1pt; visibility:hidden;" />

Also related is the word **terminal**:
the program/app/window in which the shell is run.
Finally, while all these terms are not synonyms, 
they are often used interchangeably in day-to-day computing.

### Why use the Unix shell?

The Unix shell has been around for a long time and may seem a bit archaic.
But astonishingly, a system largely built decades ago in an era with very
different computers and datasets has stood the test of time,
and the ability to use it is a crucial skill for example when working with HTS 
(high-throughput sequencing) data.

Specifically, you may want to or need to use the Unix shell as opposed to
programs with GUIs because of:

- **Software needs**\
  When working with omics data, we don't code our entire analysis from scratch --
  for example, we don't build our own genome assembly or read alignment algorithm.
  Many of the external software used for such tasks are run using a command-line
  interface from the Unix shell.
- **Automation and fewer errors**\
  The shell allows you to repeat and automate tasks easily and without
  introducing errors.
- **Reproducibility**\
  It's more straightforward to keep a detailed record of what you have done.
- **Working with large files**\
  Shell commands are really good at processing _large, plain-text files_,
  which are very common in omics data.
- **Remote computing – especially supercomputers**\
  When doing remote computing, working in the shell may be your only option.

Some of these advantages, like automation and reproducibility,
also apply to other coding languages --
so why do we need to know the Unix shell on top of R and/or Python?

- **Efficiency**\
  For many _simpler_ tasks, built-in shell tools are faster ---
  in terms of coding time, processing time,
  and the ease of working with very large files.
- **Running external software**\
  As mentioned above,
  we need to use many external programs with a CLI in omics data analysis.
  While those _can_ be called from within other languages,
  the shell has a _direct_ interface to them and is therefore often preferred.

## First steps in the shell

<details><summary>You should already have a VS Code session with a Unix shell open! If not, click here to see instructions.</summary>
TBA
</details>

### The shell's prompt

Inside your terminal, the "prompt" indicates that the shell is ready for a
command. What is shown exactly varies across shells and can also be customized,
but our prompts at OSC should show the following information:

`[<username>@<node-name> <working-dir>]$`

For example:

``` bash-in-nocolor
[jelmer@p0362 jelmer]$ 
```

The `<working-dir>` part only shows the name of the directory you are directly
located in (e.g. `jelmer`),
and doesn't give the entire path (e.g. `/fs/ess/PAS2880/users/jelmer`).

**You type your commands after the dollar sign `$`,**
**and then press <kbd>Enter</kbd> to execute the command.**
When the command has finished executing,
you'll "get your prompt back" and can type and execute a new command.

::: callout-tip
#### Code notation, clearing the screen, and the Home dir

- Code-formatted text between `<` and `>` (such as `<username>` above)
  is commonly used to indicate not literal code but something that should be
  be replaced (such as by your personal user name in the `<username>` example).

- OSC prints welcome messages and storage quota information when you open a shell.
  To reduce the amount of text on the screen,
  I will **clear the screen** now, and regularly throughout.
  This can be done with the keyboard shortcut **<kbd>Ctrl</kbd>+<kbd>L</kbd>**.
  
- If you see a `~` as the working-dir-part of your prompt,
  you are instead in your Home directory in `/users/` and you will need to go
  to `/fs/ess/PAS2880/users/<user>` instead.
  To do so: click `File` => `Open Folder` in VS Code and then type/select that dir.
  When you then open a Terminal again, the correct dir should be displayed.
:::

### A few simple commands: `date` and `pwd`

The Unix shell comes with hundreds of "commands":
small programs that perform specific actions.
(If you're familiar with R or Python,
a Unix *command* is like an R/Python *function*.)

Let's start with a few simple commands:

- The `date` command prints the current date and time:

  ``` bash
  date
  ```
  ``` bash-out
  Thu Sep 02 13:58:19 EST 2025
  ```

- The `pwd` (Print Working Directory) command prints the path to the directory
  you are currently located in:

  ``` bash
  pwd
  ```
  ``` bash-out
  /fs/ess/PAS2880/users/jelmer
  ```

Both of those commands provided us with some output.
That output was **printed to screen**,
which is the default behavior for nearly every Unix command.

## Options, arguments, and help

### The `cal` command --- and options & arguments

The `cal` command is another example of a command that simply prints some
information to the screen, in this case a calendar.
We'll use it to learn about command *options* and *arguments*.

Invoking `cal` without options or arguments will show a calendar for the current month:

```bash
cal
```
``` bash-out
   September 2025     
Su Mo Tu We Th Fr Sa  
    1  2  3  4  5  6  
 7  8  9 10 11 12 13  
14 15 16 17 18 19 20  
21 22 23 24 25 26 27  
28 29 30
```

#### Option examples

Use the *option* `-j` (a dash `-` and then `j`) to instead get a Julian calendar,
in which day numbering is continuous instead of restarting each month:

```bash
# Make sure to leave a space between `cal` and `-j`!
cal -j
```
```bash-out
       September 2025      
Sun Mon Tue Wed Thu Fri Sat
    244 245 246 247 248 249
250 251 252 253 254 255 256
257 258 259 260 261 262 263
264 265 266 267 268 269 270
271 272 273
```

Use the `-3` option to show 3 months (adding the previous and next month):

```bash
cal -3
```
``` bash-out
     August 2025         September 2025         October 2025    
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa
                1  2      1  2  3  4  5  6            1  2  3  4
 3  4  5  6  7  8  9   7  8  9 10 11 12 13   5  6  7  8  9 10 11
10 11 12 13 14 15 16  14 15 16 17 18 19 20  12 13 14 15 16 17 18
17 18 19 20 21 22 23  21 22 23 24 25 26 27  19 20 21 22 23 24 25
24 25 26 27 28 29 30  28 29 30              26 27 28 29 30 31   
31  
```

You can use multiple options at once -- for example:

```bash
cal -j -3
```
``` bash-out
        August 2025                 September 2025                October 2025       
Sun Mon Tue Wed Thu Fri Sat  Sun Mon Tue Wed Thu Fri Sat  Sun Mon Tue Wed Thu Fri Sat
                    213 214      244 245 246 247 248 249              274 275 276 277
215 216 217 218 219 220 221  250 251 252 253 254 255 256  278 279 280 281 282 283 284
222 223 224 225 226 227 228  257 258 259 260 261 262 263  285 286 287 288 289 290 291
229 230 231 232 233 234 235  264 265 266 267 268 269 270  292 293 294 295 296 297 298
236 237 238 239 240 241 242  271 272 273                  299 300 301 302 303 304    
243  
```

To save you some typing, options can be "pasted together" like so:

```bash
# [Output not shown - same as above]
cal -j3
```

::: callout-tip
#### "Comments" in code with `#`

Any text that comes after a **`#`** is considered a **comment** instead of code!
Comments are not executed but are ignored by the shell:

``` bash
# This entire line is a comment - you can run it and nothing will happen
cal # If you run this line, 'cal' will be executed but everything after the '#' is ignored
```
:::

#### Options summary

Options are specified with a dash `-` (or two dashes `--`, as you'll see later).
So far, you've only worked with the kind of option that is also called a **flag**,
_which changes functionality in an ON/OFF way_, such as:

- Turning a Julian calender display **on** with `-j`
- Turning a 3-month display **on** with `-3`.

Generally speaking, we can say that options **change the behavior** of a command.

#### Arguments

Whereas options change the behavior of a command,
arguments typically tell the command **what to operate on**.
Most commonly, these are file or directory paths.

Admittedly, the `cal` command is not the best illustration of this pattern ---
when you give it one argument, this is the year to show a calendar for:

```bash
cal 2020
```
```bash-out
                              2020                               

       January               February                 March       
Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa   Su Mo Tu We Th Fr Sa
          1  2  3  4                      1    1  2  3  4  5  6  7
 5  6  7  8  9 10 11    2  3  4  5  6  7  8    8  9 10 11 12 13 14
12 13 14 15 16 17 18    9 10 11 12 13 14 15   15 16 17 18 19 20 21
19 20 21 22 23 24 25   16 17 18 19 20 21 22   22 23 24 25 26 27 28
26 27 28 29 30 31      23 24 25 26 27 28 29   29 30 31

# [...output truncated, entire year is shown...]
```

You'll see some examples of commands operating on files or dirs soon.
Finally, you can also combine options and arguments:

```bash
cal -j 2020
```
```bash-out
                            2020                          

          January                       February         
Sun Mon Tue Wed Thu Fri Sat   Sun Mon Tue Wed Thu Fri Sat
              1   2   3   4                            32
  5   6   7   8   9  10  11    33  34  35  36  37  38  39
 12  13  14  15  16  17  18    40  41  42  43  44  45  46
 19  20  21  22  23  24  25    47  48  49  50  51  52  53
 26  27  28  29  30  31        54  55  56  57  58  59  60
 
# [...output truncated, entire year is shown...]
```
  
To summarize, different from options, _arguments_ to a command:

- Are not preceded by a letter with `-` (or a keyword with `--`)
- If options and arguments are combined, arguments **go after** options^[
  Though some commands are flexible and accept either order.].

![**Command structure visualization**.<br>Note that unfortunately, the most common way to refer to this entire line is also "command". Therefore, the term "command" can either refer to just a command like `cal` **or** what a command-line expression that includes options and arguments like `cal -j 2020`.](../img/w2-3_command-structure.png){width="50%" fig-align="center" fig-alt="A diagram showing the structure of a command." .lightbox}

### Getting help

Many basic Unix commands –*and other command-line programs!* –
have a **`-h`** option for help,
which usually gives a concise summary of the command's "syntax",
i.e. its available options and arguments:

```bash
cal -h
```
```bash-out

Usage:
 cal [options] [[[day] month] year]

Options:
 -1, --one        show only current month (default)
 -3, --three      show previous, current and next month
 -s, --sunday     Sunday as first day of week
 -m, --monday     Monday as first day of week
 -j, --julian     output Julian dates
 -y, --year       show whole current year
 -V, --version    display version information and exit
 -h, --help       display this help text and exit
```

In this case, each option can be referred to in two ways:

- A short-form notation: a single dash followed by a single character (e.g. `-s`)
- A long-form notation: two dashes followed by a word (e.g. `--sunday`)

::: {.callout-note collapse="true"}
### Another way to see documentation: the `man` command _(Click to expand)_
An alternative way of getting help for Unix commands is with the `man` command:

```bash
man cal
```

This manual page often includes a lot more details than the `--help` output,
and it is opened inside a "pager" rather than printed to screen:
type **<kbd>q</kbd>** to exit the pager that `man` launches.
:::

::: exercise
#### {{< fa user-edit >}} Exercise: Interpreting the help output

1. Look through the options listed when you ran `cal -h`,
   and try an option we haven't used yet.
   (You can also combine this new option with other options, if you want.)

   <details><summary>*Click to see a solution*</summary>

   - To print a calendar with Monday as the first day of the week
     (instead of the default, Sunday):
     
   ```bash
   cal -m
   ```
   ```bash-out
      September 2025   
   Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6  7
    8  9 10 11 12 13 14
   15 16 17 18 19 20 21
   22 23 24 25 26 27 28
   29 30  
   ```
  </details>

2. Try using one or more options in their "long form" (with `--`).
   Can you think of an advantage of using long form over short form options?

   <details><summary>*Click to see a solution*</summary>

   For example:

   ```bash
   cal --julian --monday
   ```
   ```bash-out
          September 2025      
   Mon Tue Wed Thu Fri Sat Sun
   244 245 246 247 248 249 250
   251 252 253 254 255 256 257
   258 259 260 261 262 263 264
   265 266 267 268 269 270 271
   272 273 
   ```

   The advantage of using long options is that they are less cryptic and more descriptive.
   Therefore, it is much more likely that any reader of the code
   (including yourself next week) will immediately understand what these options are doing.
   
   Note that long options **cannot** be "pasted together" like short options.
   
   </details>
:::

## Environment variables

You may be familiar with the concept of **variables** from previous experience
with perhaps R or another language.
Either way, variables can hold values and other pieces of data,
and are essential when coding.

More specifically, **environment variables** are pre-existing variables that
have been automatically assigned values by the computer.
Two examples:

```bash
# $HOME contains the path to your Home dir:
echo $HOME
```
```bash-out
/users/PAS0471/jelmer
```

```bash
# $USER contains your user name:
echo $USER
```
```bash-out
jelmer
```

In the Unix shell, variables are referenced using a leading `$`,
and to print their values to screen like above, you need the `echo` command.
`echo` is a very common command that can also just print literal text (as shown below)
or combinations of literals and variables (next exercise).
    
```bash
# (The quotes "..." aren't always necessary but are recommended for clarity)
echo "Welcome to PLNTPTH 5006"
```
```bash-out
Welcome to PLNTPTH 5006
```

::: exercise
#### {{< fa user-edit >}} Exercise: environment variables and `echo`

Using an environment variable,
get the Unix shell to print "_Hello, my name is \<your username\>_"
(e.g. "Hello, my name is natalie") to the screen.

<details><summary>*Click for the solution*</summary>

``` bash
# (This would also work without the " " quotes)
echo "Hello, my name is $USER"
```
``` bash-out
Hello, my name is jelmer
```
</details>
:::

## Navigation

### `cd` and command "actions"

All the commands so far "merely" provided some information,
which was printed to the screen.

But many commands perform another kind of **action**.
For example, the command **`cd`** will change your *working* directory.
And like many commands that perform a potentially invisible action,
`cd` normally has **no output** at all.

First, check again where you are ---
you should be in your personal dir within `/fs/ess/PAS2880/users`:

```bash
pwd
```
```bash-out
/fs/ess/PAS2880/users/jelmer
```

Now, let's use `cd` to move to another directory by specifying the *path* to that
directory as an argument:

``` bash
cd /fs/ess/PAS2880
```

```bash
# Double-check that you moved:
pwd
```
``` bash-out
/fs/ess/PAS2880
```

In summary:

- Like `cal`, `cd` accepts an argument.
  Unlike `cal`, this argument takes the form of a path that the command should
  operate on (which is very typical among Unix commands).
- `cd` gives no output when it successfully changed the working directory.
  This is very common behavior for Unix commands that perform
  operations: **when they succeed, they are silent**.

Let's also see what happens when `cd` does not succeed — it gives an error:

  ``` bash
  cd /fs/ess/PAs2880
  ```
  
  ``` bash-out
  -bash: cd: /fs/ess/PAs2880: No such file or directory
  ```

<hr style="height:1pt; visibility:hidden;" />

::: callout-note
#### Case-sensitivity: Everything in the shell (and in coding in general) is **case-sensitive**, including commands and file names --- hence the error above.
:::

### Path shortcuts

A number of "shortcuts" exist for paths:

| Symbol/shortcut | Represents... |
|---|---------|
| **`~`** (a tilde) | Your Home directory.
| **`.`** (a single period) | The current working directory (we'll see why this is useful later)
| **`..`** (two periods) | The directory "one level up" from your working dir, i.e. towards the computer's root dir. 

: {.striped .hover}

<hr style="height:1pt; visibility:hidden;" />

Some examples of `..`:

- Use `..` to go up one level in the dir hierarchy:

  ```bash
  # Start by reminding yourself of where you are:
  pwd
  ```
  ```bash-out
  /fs/ess/PAS2880
  ```
  ```bash
  # Move one level up:
  cd ..
  
  # Check where you are now:
  pwd
  ```
  ``` bash-out
  /fs/ess/
  ```

- You can "continue" a path like usual after `..`, e.g.:

  ```bash
  cd ../scratch/PAS2880
  ```

- Therefore, you can also move up multiple levels at once, e.g.:

  ``` bash
  # Move up to levels
  cd ../..
  
  pwd
  ```
  ``` bash-out
  /fs
  ```

<hr style="height:1pt; visibility:hidden;" />

::: callout-tip
#### These path shortcuts work with many commands
These are *general shell shortcuts* that work with **any** command that accepts
a path/file name, and not just with `cd`.
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: navigation

1. Use a relative path to move back to your personal dir 
   `/fs/ess/PAS2880/users/$USER`

   <details><summary>*Click to see the solution*</summary>
   
   Since you are in `/fs`:
   
   ``` bash
   cd ess/PAS2880/users/$USER
   ```
   </details>

2. From there, use another relative path to move into the
   `/fs/ess/PAS2880/share` dir.

   <details><summary>*Click to see the solution*</summary>
   
   Since you are in `/fs/ess/PAS2880/users/$USER`,
   you will first need to go up two levels (to `/fs/ess/PAS2880`),
   and then into `share`:
   
   ``` bash
   cd ../../share
   ```
   </details>
:::

## Keyboard shortcuts

Using keyboard shortcuts help you work much more efficiently in the shell.
Here are some of the most useful ones:

- **Command history** ---
  `Up` / `Down` arrow keys to cycle through your command history.

- **Tab completion** ---
  The shell will auto-complete partial commands or file paths when you press <kbd>Tab</kbd>.

- **Cancel/stop/abort** --- If your prompt is "missing", the shell is still
  busy executing your command, *or* you typed an incomplete command. To abort,
  press <kbd>Ctrl</kbd>+<kbd>C</kbd> and you will get your prompt back.

::: exercise
#### {{< fa user-edit >}} Exercise: Tab completion & command history

- Type **`/f`** and press <kbd>Tab</kbd> (will autocomplete to */fs/*)

- Add **`e`** (*/fs/e*) and press <kbd>Tab</kbd> (will autocomplete to */fs/ess/*).

- Add **`PAS`** (*/fs/ess/PAS*) and press <kbd>Tab</kbd>. Nothing should
  happen: there are multiple (many!) options.

- Press <kbd>Tab</kbd> <kbd>Tab</kbd> (i.e., twice in quick succession) and it should say:

  ``` bash-out
  Display all 619 possibilities? (y or n)
  ```

- Type `n` to answer no: we don't need to see all the dirs starting with `PAS`.

- Add **`288`** (*/fs/ess/PAS288*) and press <kbd>Tab</kbd>
  **twice in quick succession** (a single Tab won't do anything):
  you should see at least four dirs that start with `PAS288`.

- Add `0` so your line reads `/fs/ess/PAS2880`. Press <kbd>Enter</kbd>.
  You will get the following output, which is an error.
  Can you think of any reason why this you may have gotten an error here?

  ```bash-out-solo
  bash: /fs/ess/PAS2880/: Is a directory
  ```

<details><summary>*Click to see the solution*</summary>
Basically, everything you type in the shell should start with a command.
Just typing a path will not make the shell print some info about, or the contents of,
this dir or file.
Instead, since a path is not a command, you will get an error.
</details>

- Press **<kbd>⇧</kbd>** to get the previous "command" back on the prompt.

- Press **<kbd>Ctrl</kbd>+<kbd>A</kbd>** to move to the beginning of the line at once.

- Add `cd` and a space in front of the dir, and press <kbd>Enter</kbd> again.

  ```bash
  cd /fs/ess/PAS2880/
  ```
  
:::callout-tip  
#### Your **cursor** can be anywhere on a line (not just at the end) when you press <kbd>Enter</kbd> to execute a command!
:::
:::

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: canceling

To simulate a long-running command that you may want to abort,
we'll use the `sleep` command,
which makes the computer wait for a specified amount of time before it gives your
prompt back (or, e.g. moves to the next command in the context of a script).

Run the below command and instead of waiting for the full 60 seconds,
**press <kbd>Ctrl</kbd> + <kbd>C</kbd>** to get your prompt back sooner!

``` bash
sleep 60s
```

As another example of a situation where you might have to use
<kbd>Ctrl</kbd> + <kbd>C</kbd>,
simply type an opening parenthesis `(` and press <kbd>Enter</kbd>:

``` bash
(
```

When you do this, nothing is executed and you are not getting your prompt back:
you should see a `>` on the next line.
This is the shell wanting you to "complete" you command. Why would that be?

<details><summary>*Click to see the solution*</summary>
This is an incomplete command by definition because any opening parenthesis
should have a matching closing parenthesis.
</details>

Press <kbd>Ctrl</kbd> + <kbd>C</kbd> to get your regular prompt back.
:::

::: {.callout-note collapse="true"}
#### Table with useful keyboard shortcuts _(Click to expand)_

_(Note that even on Macs, you should use <kbd>Ctrl</kbd> instead of switching them_
_out for <kbd>Cmd</kbd> as you may be used to doing --_
_though in some cases, like copy/paste, both keys work)._

| Shortcut | Function |
|-----|------------|
| <kbd>Tab</kbd> | Tab completion |
| <kbd>⇧</kbd> / <kbd>⇩</kbd> | Cycle through previously issued commands | |
| <kbd>Ctrl</kbd>+<kbd>C</kbd> | Copy selected text | |
| <kbd>Ctrl</kbd>+<kbd>V</kbd> | Paste text from clipboard |
| <kbd>Ctrl</kbd>+<kbd>A</kbd> / <kbd>Ctrl</kbd>+<kbd>E</kbd> | Go to beginning/end of line |
| <kbd>Ctrl</kbd>+<kbd>U</kbd> /<kbd>Ctrl</kbd>+<kbd>K</kbd> | Cut from cursor to beginning / end of line |
| <kbd>Ctrl</kbd>+<kbd>W</kbd> | Cut word before before cursor |
| <kbd>Ctrl</kbd>+<kbd>Y</kbd> | Paste ("yank") text that was cut with one of the shortcuts above |
| <kbd>Alt</kbd>+<kbd>.</kbd> / <kbd>Esc</kbd>+<kbd>.</kbd>  | Retrieve last argument of previous command (very useful!) (<kbd>Esc</kbd>+<kbd>.</kbd> for Mac) |
| <kbd>Ctrl</kbd>+<kbd>R</kbd> | Search history: press <kbd>Ctrl</kbd>+<kbd>R</kbd> again to cycle through matches, <kbd>Enter</kbd> to put command in prompt. |
| <kbd>Ctrl</kbd>+<kbd>C</kbd> | Cancel (kill/stop/abort) currently active command |
| <kbd>Ctrl</kbd>+<kbd>D</kbd> | Exit (a program or the shell, depending on the context) (same as `exit` command) |
| <kbd>Ctrl</kbd>+<kbd>L</kbd> | Clear the screen (same as `clear` command) |

: {.striped .hover}

:::
