<details>

<summary>2 - `#SBATCH` options</summary>

``` bash
#SBATCH --account=PAS2880
#SBATCH --cpus-per-task=8
#SBATCH --output=slurm-trimgalore-%j.out
#SBATCH --mail-type=FAIL
```

</details>

<details>

<summary>3 - Make TrimGalore use the reserved 8 cores</summary>

Simply add `--cores 8` to your TrimGalore command.

</details>

<details>

<summary>4 - Submit the script once, then clean up</summary>

``` bash
fastq_file=../../garrigos-data/fastq/ERR10802863_R1.fastq.gz
sbatch scripts/trimgalore.sh "$fastq_file" results/trimgalore
```

To check that everything went well, look at the Slurm log files and the TrimGalore output files in `results/trimgalore`.

To remove the outputs from this test:

``` bash
rm slurm-trimgalore*
rm results/trimgalore/*
```

-   `--two-color` option??

</details>

<details>

<summary>5 - Submit the script for all samples</summary>

``` bash
for fastq_R1 in ../../garrigos-data/fastq/*R1.fastq.gz; do
   sbatch scripts/trimgalore.sh "$fastq_R1" results/trimgalore
done
```

To check that everything went well, check your email and look at the TrimGalore output files in `results/trimgalore`. You can also run `tail slurm-trimgalore*` to check the last lines of each Slurm log file.

</details>

<details>

<summary>6 - Move the Slurm log files</summary>

``` bash
mkdir results/trimgalore/logs
mv slurm-trimgalore* results/trimgalore/logs
```

</details>

### Renaming the output files

<details>

<summary>Solution *(Click to expand)*</summary>

The full script:

``` bash
#!/bin/bash
set -euo pipefail

# Load TrimGalore
module load miniconda3
source activate /fs/ess/PAS0471/jelmer/conda/trimgalore

# Copy the placeholder variables
R1_in=$1
outdir=$2

# Check that the output dir isn't the same as the input dir
# This is because we will let the output files have the same name as the input files
indir=$(dirname "$R1_in")
if [[ "$indir" == "$outdir" ]]; then
    echo "ERROR: Input dir is the same as the output dir ($outdir)" 
    exit 1
fi

# Infer the R2 FASTQ file name
R2_in=${R1_in/_R1/_R2}

# Report
echo "# Starting script trimgalore.sh"
date
echo "# Input R1 FASTQ file:      $R1_in"
echo "# Input R2 FASTQ file:      $R2_in"
echo "# Output dir:               $outdir"
echo

# Create the output dir
mkdir -p "$outdir"

# Run TrimGalore
trim_galore \
    --paired \
    --output_dir "$outdir" \
    --fastqc \
    "$R1_in" \
    "$R2_in"

# Rename output files
echo
echo "# Renaming the output files:"
sample_id=$(basename "$R1_in" _R1.fastq.gz)
R1_out_init="$outdir"/"$sample_id"_R1_val_1.fq.gz
R2_out_init="$outdir"/"$sample_id"_R2_val_2.fq.gz
R1_out_final="$outdir"/"$sample_id"_R1.fastq.gz
R2_out_final="$outdir"/"$sample_id"_R2.fastq.gz
mv -v "$R1_out_init" "$R1_out_final"
mv -v "$R2_out_init" "$R2_out_final"

# Report
echo
echo "# Done with script trimgalore.sh"
date
```

Run the script with a different output dir:

``` bash
R1=garrigos-data/fastq/ERR10802863_R1.fastq.gz
bash scripts/trimgalore.sh "$R1" results/trimgalore_rename
```

Let's check the output files to see they were successfully renamed:

``` bash
ls -lh results/trimgalore_rename
```

``` bash-out
total 42M
-rw-rw----+ 1 jelmer PAS0471  20M Mar 28 10:40 ERR10802863_R1.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 2.4K Mar 28 10:39 ERR10802863_R1.fastq.gz_trimming_report.txt
-rw-rw----+ 1 jelmer PAS0471 674K Mar 28 10:40 ERR10802863_R1_val_1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 349K Mar 28 10:40 ERR10802863_R1_val_1_fastqc.zip
-rw-rw----+ 1 jelmer PAS0471  21M Mar 28 10:40 ERR10802863_R2.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 2.3K Mar 28 10:40 ERR10802863_R2.fastq.gz_trimming_report.txt
-rw-rw----+ 1 jelmer PAS0471 676K Mar 28 10:40 ERR10802863_R2_val_2_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 341K Mar 28 10:40 ERR10802863_R2_val_2_fastqc.zip
```

Looks good --- though note that we only renamed the FASTQ files, not the other files.

</details>

The full script:

``` bash
#!/bin/bash
set -euo pipefail

# Load TrimGalore
module load miniconda3
source activate /fs/ess/PAS0471/jelmer/conda/trimgalore

# Copy the placeholder variables
R1_in=$1
outdir=$2

# Check that the output dir isn't the same as the input dir
# This is because we will let the output files have the same name as the input files
indir=$(dirname "$R1_in")
if [[ "$indir" == "$outdir" ]]; then
    echo "ERROR: Input dir is the same as the output dir ($outdir)" 
    exit 1
fi

# Infer the R2 FASTQ file name
R2_in=${R1_in/_R1/_R2}

# Report
echo "# Starting script trimgalore.sh"
date
echo "# Input R1 FASTQ file:      $R1_in"
echo "# Input R2 FASTQ file:      $R2_in"
echo "# Output dir:               $outdir"
echo

# Create the output dir
mkdir -p "$outdir"

# Run TrimGalore
trim_galore \
    --paired \
    --output_dir "$outdir" \
    --fastqc \
    "$R1_in" \
    "$R2_in"

# Rename output files
echo
echo "# Renaming the output files:"
sample_id=$(basename "$R1_in" _R1.fastq.gz)
R1_out_init="$outdir"/"$sample_id"_R1_val_1.fq.gz
R2_out_init="$outdir"/"$sample_id"_R2_val_2.fq.gz
R1_out_final="$outdir"/"$sample_id"_R1.fastq.gz
R2_out_final="$outdir"/"$sample_id"_R2.fastq.gz
mv -v "$R1_out_init" "$R1_out_final"
mv -v "$R2_out_init" "$R2_out_final"

# Report
echo
echo "# Done with script trimgalore.sh"
date
```

Run the script with a different output dir:

``` bash
R1=garrigos-data/fastq/ERR10802863_R1.fastq.gz
bash scripts/trimgalore.sh "$R1" results/trimgalore_rename
```

Let's check the output files to see they were successfully renamed:

``` bash
ls -lh results/trimgalore_rename
```

``` bash-out
total 42M
-rw-rw----+ 1 jelmer PAS0471  20M Mar 28 10:40 ERR10802863_R1.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 2.4K Mar 28 10:39 ERR10802863_R1.fastq.gz_trimming_report.txt
-rw-rw----+ 1 jelmer PAS0471 674K Mar 28 10:40 ERR10802863_R1_val_1_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 349K Mar 28 10:40 ERR10802863_R1_val_1_fastqc.zip
-rw-rw----+ 1 jelmer PAS0471  21M Mar 28 10:40 ERR10802863_R2.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 2.3K Mar 28 10:40 ERR10802863_R2.fastq.gz_trimming_report.txt
-rw-rw----+ 1 jelmer PAS0471 676K Mar 28 10:40 ERR10802863_R2_val_2_fastqc.html
-rw-rw----+ 1 jelmer PAS0471 341K Mar 28 10:40 ERR10802863_R2_val_2_fastqc.zip
```

Looks good --- though note that we only renamed the FASTQ files, not the other files.
