---
title: "Week 10: Using generative AI"
pagetitle: "Week 10 overview"
date: 2025-10-28
date-modified: 2025-10-31
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "w10a: Using generative AI"
    icon: bookmarks
    href: w10a_genAI.html
  - text: "w10b: GenAI with GitHub Copilot"
    icon: bookmarks
    href: w10b_copilot.html
  - text: "Week 10 graded assignment"
    icon: pencil
    href: w10_ga.html
bibliography: ../references.bib
---

------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, you will learn about using generative AI (genAI) tools to help you with tasks in omics data analysis, especially coding talks.

## Learning goals

This week you will learn:

#### Lecture A: [Using generative AI when coding and beyond](./w10a_genAI.qmd)

-   Basic background of generative AI (genAI) and large language models (LLMs)
-   What GenAI applications exist in bioinformatics and omics data analysis
-   About Ohio State's genAI adoption and approved tools
-   What options you have for using genAI tools, including for coding
-   Example prompts and outputs relevant to this course
-   Tips and pitfalls when using genAI tools, especially for coding

#### Lecture B: [GenAI with GitHub Copilot](./w10a_genAI.qmd)

-   Using your local VS Code installation at OSC
-   Enabling and configuring GitHub Copilot within VS Code
-   Using GitHub Copilot within VS Code to help you with coding tasks

## Readings

-   @lubiana2023: [Ten quick tips for harnessing the power of ChatGPT in computational biology](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011319)
-   @pearson2025: [Universities are embracing AI: will students get smarter or stop thinking?](https://www.nature.com/articles/d41586-025-03340-w)

## Exercises & assignments

-   **Graded assignment 5**: [Using GenAI when coding](w10_ga.qmd) [*(Due 11/03)*]{style="color:#bb0000"}

## Further resources

-   @rahman2023: [How Much Can ChatGPT Really Help Computational Biologists in Programming?](https://doi.org/10.48550/arXiv.2309.09126)
-   @helmy2025: [Ten simple rules for optimal and careful use of generative AI in science](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1013588) [*(Added 10/31)*]{style="color:darkorange"}
-   @guest2025: [Against the Uncritical Adoption of 'AI' Technologies in Academia](https://zenodo.org/records/17065099)
