---
title: "Graded Assignment II: Version control"
subtitle: "Week 4 -- due Monday Sept 22 at 10:00 pm"
pagetitle: "PRACS25: GA1"
date: 2025-09-15
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
number-sections: false
other-links:
  - text: "w4-1: Version control with Git"
    icon: bookmarks
    href: w4_1_git.html
  - text: "w4-2: Remotes with GitHub"
    icon: bookmarks
    href: w4_2_github.html
  - text: "Week 4: Ungraded assignment: GitHub account"
    icon: pencil
    href: w4_ua_github-account.html
  - text: "Bonus: Advanced Git"
    icon: book
    href: ../bonus/git.html
---

------

<br>

### Introduction

In this graded assignment (maximum score: 10 points),
you will primarily be practicing your Git skills.

The **deadline** is Monday Sept 22 at 10:00 pm.
You will submit your assignment by tagging the instructor in an Issue in your
GitHub as per the last exercise below. 

_A general tips to keep in mind is to keep checking the status of your repository (repo)_
_with **`git status`** before and after nearly all other Git commands that you issue._
_This will help prevent mistakes, and will also help you understand Git better._

<hr style="height:1pt; visibility:hidden;" />

## Part I: Local Git workflow

1. **Create a new directory at OSC for this assignment, and move there.**\
   Use the following path for the new dir: `/fs/ess/PAS2880/users/$USER/week04/assignment`.

2. **Initialize a local Git repository** inside your new directory.

3. **Create a README file in Markdown format.**\
   The file should be named `README.md`, and for now,
   just contain a *header* that states this is a repo for your assignment.
   
4. **Stage and then commit the README file** with an appropriate commit message.

5. **Create a second Markdown file with some more contents.**\
   Name it as you like. In it,
   describe the basic Git workflow and commands with bullet points and headers.
     
6. **Create at least two commits while you work on the Markdown file.**\
   Try to break your progress up into logical units that can be
   summarized with a descriptive commit message.
   
7. **Update the `README.md` file**.\
   Briefly describe the current contents of your repo now that you actually
   have some contents.

8. **Stage and commit the updated README file.**\

9. **Create a `results` directory with an empty file and make Git ignore this directory.**\
   Also, commit your `.gitignore` file.

<hr style="height:1pt; visibility:hidden;" />

## Part II: Create and sync an online version of the repo

Phew, you made several commits! Time to share all this work with the world.

10. **Create a GitHub repository.**\
    Go to <https://github.com>, sign in, and create a new repository.
    Name the repo "PRACS25_w04-assignment"^[
    This is not the same name as your dir on OSC, which is OK.].
    Like in class, create a completely *empty* GitHub repository,
    because you will upload all the contents from your local repo.
    
11. **Push your local repo to the online counterpart you just created.**\
    When you're done, click the `Code` button, and
    admire the nicely rendered README on the front page of your GitHub repo.

12. **Open a GitHub Issue**\
    Open an Issue for your repo: in the Issues tab, click "New Issue",
    and in the box where you can type your issue, tag the instructor.
    For example:
    
    ```markdown
    Hey @jelmerp, can you please take a look at my repo?
    ```
