---
title: "Week 4: Git & GitHub"
pagetitle: "PRACS25: Week 4 overview"
number-sections: false
date: 2025-09-15
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "w4-1: Version control with Git"
    icon: bookmarks
    href: w4a_git.html
  - text: "w4-2: Remotes with GitHub"
    icon: bookmarks
    href: w4b_github.html
  - text: "Week 4: Ungraded assignment: GitHub account"
    icon: pencil
    href: w4_ua_github-account.html
  - text: "Week 4 graded assignment"
    icon: pencil
    href: w4_ga_git.html
  - text: "Bonus: Advanced Git"
    icon: book
    href: ../bonus/git.html
---

---------

<br>

## Learning goals

This week, you will learn about the why and how of using Git version control for
your projects, and sharing your code on GitHub.
Some of the things you will learn this week:

#### [Version control with Git](./w4a_git.qmd) _(Tuesday)_

- Understand why you should use a formal Version Control System (VCS) for research projects.
- Learn the basics of the most widely used VCS: Git.

#### [Remotes on GitHub](./w4b_github.qmd) _(Thursday)_

- Learn how to put your local repositories online at GitHub,
  and how to keep local and online ("remote") repositories in sync.
- Learn about single-user and multi-user workflows with Git and GitHub.

_Be aware that Git is a challenging topic, so make sure you practice outside of class._
_A good way to get used to Git is to make dummy repositories where you're just_
_editing one or a few simple text files with dummy lines of text._
_That way, you can get used to the basic workflow,_
_and freely experiment also with commands to undo things and move back in time._
_We'll do this in class and I recommend you do it outside of there, too._

<hr style="height:1pt; visibility:hidden;" />

## Assignments and exercises

- **Ungraded assignment**: [Create a GitHub account](./w4_ua_github-account.qmd) [_(Do this before Thursday's class!)_]{style="color:#bb0000"}
- **Graded assignment**: [Git and GitHub](./w4_ga_git.qmd) [_(Due 9/22)_]{style="color:#bb0000"}

<hr style="height:1pt; visibility:hidden;" />

## Readings

### Required readings

- (Re)read the lecture pages,
  including any content, like callout boxes, we may have skipped in class.

### Optional readings

- Optional self-study content: [_Branching, collaborating, and undoing_](../bonus/git.qmd)
  - Learn how to use Git branches to safely make experimental changes.
  - Learn how to undo things and "travel back in time" for your project using Git.
  
- [CSB](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085456156508507)
  Chapter 2: "_Version Control_"
  
- [Buffalo](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507)
  Chapter 5: "_Git for Scientists_"
  
### Further resources

- GitHub has a
  [nice little overview](https://guides.github.com/activities/hello-world/)
  of some Git and GitHub functionality including branching and Pull Requests,
  and how to do these things in your browser at GitHub. 

- For some more background on why to use version control,
  and another perspective on some Git basics,
  I recommend the article
  "[Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159)"
  by Jenny Bryan.

- [Git-it](https://github.com/jlord/git-it-electron#git-it)
  is a small application to learn and practice Git and GitHub basics.
  
- If you want to try some online exercises with Git with helpful visuals of what
  Git commands do, try <https://learngitbranching.js.org/>.
  (But be aware that this does fairly quickly move to fairly advanced topics,
  including several that we will not touch on in the course.)

- Especially if you already work with R a lot, I would recommend checking out
  [Happy Git and GitHub for the useR](https://happygitwithr.com/),
  also by Jenny Bryan. This is a very accessible introduction to Git.
  
- [A good list of even more Git resources...](https://gist.github.com/jaseemabid/1321592)
