---
title: "Final Project 3: Oral presentation"
pagetitle: "Final Project presentation"
date: 2025-10-11
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "FP: general info"
    icon: bookmarks
    href: FP_info.html
  - text: "FP 1: proposal"
    icon: pencil
    href: FP1_proposal.html
  - text: "FP 2: progress report"
    icon: pencil
    href: FP2_draft.html
  - text: "FP 4: final submission"
    icon: pencil
    href: FP4_submission.html
number-sections: false
editor_options: 
  chunk_output_type: console
bibliography: ../references.bib
---

--------------------------------------------------------------------------------

<hr style="height:1pt; visibility:hidden;" />

## Overview

The third Final Project checkpoint is a short oral presentation about your Final
Project, given during the course's last Zoom session on December 9^th^.
You can earn 10 points with this presentation.

## Directions and grading

### Submission expectations

- You will be presenting your Final Project as a live oral presentation
  on December 9^th^.
  _You must notify the instructors well in advance if you would like to request an_
  _alternative arrangement._

### Rubric

You can earn a total of 10 points across the following aspects:

:::: columns
::: {.column width="30%"}
:::
::: {.column width="40%"}

| Aspect | Points |
|--------|:-------:|
| Technical content | 3 |
| Delivery and clarity | 2 |
| Project contextualization | 2 |
| Answers to questions | 2 |
| Questions for other students | 1 |

: {.striped}

:::
::: {.column width="30%"}
:::
::::

### Detailed instructions

- Aim for the presentation itself to take about 6 minutes
  (allowing 3 minutes for Q&A: next item)

- Afterwards, be prepared to answer questions from your peers and the instructor
  
- At least some of your presentation should be given using slides.
  Optionally, you could switch to VS Code, RStudio, and/or GitHub for part of your
  presentation to show or even demo parts of your final project.

- Start with general background about the data / research project,
  and an overview of the goals of your final project

- It is up to you if you would like to show some of your code line-by-line,
  or stick to a more high-level overview of what you've done

- You are not expected to have finished your project,
  but you are expected to have made significant progress since you submitted
  your draft (checkpoint 2)

- At the end of the presentation, mention what you still want to do before your
  final submission.
  If you've used your own data in your final project, then you may also want to
  mention what additional things you'll want to do after the course ends.

- As you can see in the rubric above, you are also expected and will be graded on
  asking other students questions about their presentations
