---
title: "SSH connections and other OSC file transfer options"
subtitle: "Optional self-study content for week 5"
pagetitle: "file transfer"
date: 2025-08-15
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
---

------

<br>

:::callout-caution
#### THIS PAGE IS STILL UNDER CONSTRUCTION
:::

<br>

## SSH connections

### Introduction

This part will first go through the basics of connecting to OSC with SSH,
using the `ssh` command.
If you use `ssh` frequently, or plan to do so,
the two sections after that will show you two useful tricks:

- [Avoid being prompted for your OSC password](#avoid-being-prompted-for-your-osc-password)
- [Set up a shortcut for your SSH connection name](#use-a-shorter-name-for-your-ssh-connection).

Finally, there is a section on 
[SSH-tunneling a local VS Code installation to OSC](#set-up-your-local-vs-code-to-ssh-tunnel-into-osc)
(this is incredibly useful!).

::: {.callout-caution collapse="true"}
#### SSH and Unix shells on Windows _(Click to expand)_
If you have a Windows computer, you can't use SSH in a shell like on Mac or Linux,
but you can instead use a GUI-based SSH client like [`PuTTY`](https://www.putty.org/).

Alternatively, for an experience more similar to those one Unix-based operating
systems, you can install one of the following,
which will enable you to get a terminal program that runs a Unix shell:

- [**Windows Subsystem for Linux (WSL)**](https://learn.microsoft.com/en-us/windows/wsl/install)
  --- the more involved option, this will basically run a Linux Virtual Machine on your computer.
- **Git for Windows**,
  which comes with a Unix (Bash) shell &mdash; "Git Bash".
  To install this, [download it from this page](https://git-scm.com/download/win) and 
  install it using all the default settings for the installation, except:
  - In "*Adjusting Your PATH Environment*", select "*Use Git from Git Bash Only*".
  - In the prompt "*Configuring the Line Ending Conversions*",
    choose "*Checkout as-is, commit as-is*".
:::

<hr style="height:1pt; visibility:hidden;" />

### Basic SSH connection in a terminal

To connect to OSC or other remote computers without using a web portal like
OnDemand, you can use SSH.
You can do so via the **`ssh` command** if you have a Linux or a Mac computer,
since these two operating systems are both Unix-based and have built-in terminals
with Unix shells.

Here, I'll briefly demonstrate how to use the `ssh` command.
On your own computer,
open a terminal application and input the command `ssh <user>@<host>`, where:

  - `<user>` should be replaced by your OSC username, and
  - `<host>` should be replaced by the name of the computer you want to connect to:
    - `pitzer.osc.edu` to connect to the Pitzer cluster
    - `owens.osc.edu` to connect to the Owens cluster

For example, if I (username `jelmer`) wanted to log in to the Pitzer cluster,
I would use:

```bash
ssh jelmer@pitzer.osc.edu
```

``` {.bash-out}
The authenticity of host 'pitzer.osc.edu' can't be established.
RSA key fingerprint is 2a:b6:f6:8d:9d:c2:f8:2b:8c:c5:03:06:a0:f8:59:12.
Are you sure you want to continue connecting (yes/no)?
```

If this is the first time you are connecting to Pitzer via SSH, 
you’ll encounter a message similar to the one above.
While the phrase _"The authenticity of host 'pitzer.osc.edu' can't be established."_
sounds ominous, you will always get this warning when you attempt to connect to a
remote computer for the first time, and you should type `yes` to proceed
(you then won't see this message again).

You should now be prompted for your password.
Type it in carefully because no characters or even *s will appear on the screen,
and then press <kbd>Enter</kbd>.

```bash-out-solo
jelmer@pitzer.osc.edu's password:
``` 

If you entered your password correctly,
your shell is now connected to OSC rather than operating on your own computer.
That is, you'll have shell access very much in the same way as when using the
"Pitzer Shell Access" button on OSC OnDemand.
(The key difference between SSH-ing in this way rather than using OnDemand
is that the terminal is not running inside your browser, which can be convenient.)

::: {.callout-tip}
#### SSH shortcuts!
If you use SSH a lot to connect to OSC,
typing `ssh <username>@pitzer.osc.edu` every time and then providing your password
can get pretty tedious.
The next two sections will show you how to make this go faster.
:::

<hr style="height:1pt; visibility:hidden;" />

### Avoid being prompted for your OSC password

If you take the following steps, you will not be prompted for your OSC password
every time you log in using SSH.
Both steps should be done in a terminal *on your local machine*:

1.  **Generate a public-private SSH key-pair:**

    ``` {.bash}
    ssh-keygen -t rsa
    ```

    You'll get some output and will then be asked several questions,
    but in each case, you can just press <kbd>Enter</kbd> to select the default answer.

2.  **Transfer the public key to OSC's Pitzer cluster:**

::: {.panel-tabset}
### Windows

```bash
cat ~/.ssh/id_rsa.pub | ssh <user>@pitzer.osc.edu 'mkdir -p .ssh && cat >> .ssh/authorized_keys'
```

### Mac
```bash
# Replace <user> by your username, e.g. "ssh-copy-id jelmer@pitzer.osc.edu"
ssh-copy-id <user>@pitzer.osc.edu
```
:::

All done! Test if it works by running:

```bash
# Try connecting to Pitzer (once again, replace '<user>' by your username):
ssh <user>@pitzer.osc.edu
```

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-tip}
#### The same commands work for Owens, just replace `pitzer` with `owens` in the commands above.
:::

::: {.callout-note}
#### Additional instructions: See this [Tecmint post](https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/) in case you're struggling to get this to work.
:::

<hr style="height:1pt; visibility:hidden;" />

### Use a shorter name for your SSH connection

You can easily set up alternative ways of referring to you SSH connection (i.e., "aliases"),
such as shortening `jelmer@pitzer.osc.edu` to `jp`,
by saving these aliases in a text file `~/.ssh/config`, as shown below.

These two steps should both be done *on your local machine*:

1. **Create a file called `~/.ssh/config`:**

   ```bash
   touch ~/.ssh/config
   ```

2. **Open the file in a text editor and add your alias(es) in the following format:**

   ```bash-out-solo
   Host <arbitrary-alias-name>    
      HostName <remote-address>
      User <username>
   ```

   For instance, my file contains the following so as to connect to Pizer with
   `jp` and to Owens with `jo`:

   ```bash-out-solo
   Host jp
      HostName pitzer.osc.edu
      User jelmer

   Host jo
      HostName owens.osc.edu
      User jelmer
  ```

Now, you just need to use your, preferably very short, alias to log in ---
and if you did the previous no-password setup,
you won't even be prompted for your password!

```bash
ssh jp
```

<hr style="height:1pt; visibility:hidden;" />

::: callout-note
#### These shortcuts also work with `scp` and `rsync`!
For example:

```bash
rsync ~/scripts op:/fs/scratch/PAS0471
```
:::

<hr style="height:1pt; visibility:hidden;" />

### Set up your local VS Code to SSH tunnel into OSC

If you want to use VS Code to write code, have a shell, and interact with files
at OSC directly,
you don't necessarily need to use the VS Code (Code Server) in OSC OnDemand.
You can also make your local VS Code installation "**SSH tunnel**" into OSC.

This is a more convenient way of working because it's quicker to start,
will never run out of alotted time,
and because you are not working inside a browser,
you have more screen space and no keyboard shortcut interferences.

The set-up is pretty simple
(see also [these instructions](https://code.visualstudio.com/docs/remote/ssh) if you get stuck),
and should also work on Windows:

1. If necessary, install VS Code
   (instructions for [Windows](https://code.visualstudio.com/docs/setup/windows) /
   [Mac](https://code.visualstudio.com/docs/setup/mac) /
   [Linux](https://code.visualstudio.com/docs/setup/linux))
   on your computer, and open it.

2. Install the VS Code ["Remote Development extension pack"](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack):
   open the Extensions side bar (click the icon with the four squares in the far left),
   and in that side bar, search for "_Remote Development extension pack_".
   That extension should appear with an `Install` button next to it: click that.

3. Open the Command Palette (<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd><kbd>P</kbd>)
   and start typing "_Remote SSH_".
    
   Then, select `Remote-SSH: Add New SSH Host…` and specify your SSH connection:
   for Pitzer, this is `ssh <osc-username>@pitzer.osc.edu`, e.g. `ssh jelmer@pitzer.osc.edu`
   (you'll have to do this separately for Owens if you want to be able to connect to both this way).

   In the "Select SSH configuration file to update" dialog, just select the first (top) option that shows up.

4. You'll get a "Host Added!" pop-up in the bottom-right of your screen:
   in that pop-up, click `Connect`.

5. If you did the [no-password setup described above](#avoid-being-prompted-for-your-osc-password)
   (recommended!),
   you shouldn't be prompted for a password and VS Code will connect to OSC!
    
   - If you're asked about the operating system of the host, **select Linux**,
     which is the operating system of the OSC clusters.
   - If you're asked whether you "Trust the Authors" of such-and-such directory,
     click Yes.
   - If there is a pop-up in the bottom-right asking you to update Git,
     click No and check "Don't show again".

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-warning}
#### You are now on a login node!
Just be aware that you'll now be on a Login node
(and not on a Compute node like when you use VS Code through OnDemand),
so avoid running analyses directly in the terminal, and so on. 
:::

<br>

## More on file transfer to and from OSC

### Remote transfer commands

For small transfers, an alternative to the OnDemand Files menu is using
**remote transfer commands** like `scp`, `rsync`, or `rclone`.
These commands can be more convenient than OnDemand especially if you want to keep
certain directories synced between OSC and your computer.

Because at OSC, these transfers will happen using a login node,
these commands are unfortunately not recommended for large transfers^[
This may be different at other supercomputer centers: there are no inherent transfer
size limitations to these commands.].

#### `scp`

One option is `scp` (secure copy), which works much like the regular `cp` command,
including the need for the `-r` option for recursive transfers.
The key difference is that we have to somehow refer to a path on a remote computer,
and we do so by starting with the remote computer's address,
followed by `:`, and then the path:

```bash-out-solo
# Copy from remote (OSC) to local (your computer):
scp <user>@pitzer.osc.edu:<remote-path> <local-path>

# Copy from local (your computer) to remote (OSC)
scp <local-path> <user>@pitzer.osc.edu:<remote-path>
```

Here are two examples of copying from OSC to your local computer:

```bash
# Copy a file from OSC to a local computer - namely, to your current working dir ('.'):
scp jelmer@pitzer.osc.edu:/fs/ess/PAS0471/jelmer/mcic-scripts/misc/fastqc.sh .

# Copy a directory from OSC to a local computer - namely, to your home dir ('~'):
scp -r jelmer@pitzer.osc.edu:/fs/ess/PAS0471/jelmer/mcic-scripts ~
```

And two examples of copying from your local computer to OSC:

```bash
# Copy a file from your computer to OSC --
# namely, a file in from your current working dir to your home dir at OSC:
scp fastqc.sh jelmer@pitzer.osc.edu:~

# Copy a file from my local computer's Desktop to the Scratch dir for PAS0471:
scp /Users/poelstra.1/Desktop/fastqc.sh jelmer@pitzer.osc.edu:/fs/scratch/PAS0471
```

Some nuances for remote copying:

- For both transfer directions (remote-to-local and local-to-remote),
  you **issue the copying commands from your local computer.**
- The path for the remote computer (OSC) should always be absolute but that
  for your local computer can be relative or absolute.
- Since all files are accessed at the same paths at Pitzer and at other clusters,
  it doesn't matter whether you use `@pitzer.osc.edu` or e.g.
  `@cardinal.osc.edu` in the `scp` command.
 
::: {.callout-note collapse="true"}
#### Transferring directly to and from OneDrive _(Click to expand)_

If your OneDrive is mounted on or synced to your local computer
(i.e., if you can see it in your computer's file brower),
you can also transfer directly between OSC and OneDrive.
For example, the path to my OneDrive files on my laptop is:  
`/Users/poelstra.1/Library/CloudStorage/OneDrive-TheOhioStateUniversity`.  
So if I had a file called `fastqc.sh` in my top-level OneDrive dir,
I could transfer it to my Home dir at OSC as follows:

```bash
scp /Users/poelstra.1/Library/CloudStorage/OneDrive-TheOhioStateUniversity jelmer@pitzer.osc.edu:~
```
:::

<hr style="height:1pt; visibility:hidden;" />

#### `rsync`

Another option, which I can recommend, is the `rsync` command,
especially when you have directories that you repeatedly want to sync:
`rsync` won't copy any files that are identical in source and destination.

A useful combination of options is `-avz --progress`:

- `-a` enables archival mode (among other things, this makes it work recursively).
- `-v` increases verbosity &mdash; tells you what is being copied.
- `-z` enables compressed file transfer (=> generally faster).
- `--progress` to show transfer progress for individual files.

The way to refer to remote paths is the same as with `scp`.
For example, I could copy a `dir_with_results` in my local Home dir to my
OSC Home dir as follows:

```bash
rsync -avz --progress ~/dir_with_results jelmer@pitzer.osc.edu:~
```

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-warning collapse="true"}
#### Trailing slashes in `rsync` _(Click to expand)_

One tricky aspect of using `rsync` is that the presence/absence of a
**trailing slash for source directories** makes a difference for its behavior.
The following commands work as intended &mdash;
to create a backup copy of a `scripts` dir inside a dir called `backup`[^2]:

[^2]: For simplicity, these commands are copying between local dirs,
      which is also possible with `rsync`.

```bash
# With trailing slash: copy the *contents* of source "scripts" into target "scripts":
rsync -avz scripts/ backup/scripts

# Without trailing slash: copy the source dir "scripts" into target dir "backup"
rsync -avz scripts backup
```

But these commands don't:

```bash
# This would result in a dir 'backup/scripts/scripts':
rsync -avz scripts backup/scripts

# This would copy the files in "scripts" straight into "backup":
rsync -avz scripts/ backup
```
:::

<hr style="height:1pt; visibility:hidden;" />

### Command-line SFTP

The first of two options for larger transfers is **SFTP**.
You can use the **`sftp` command** when you have access to a Unix shell on your computer,
and this what I'll cover below.

#### Logging in

To log in to OSC's SFTP server, issue the following command in your local
computer's terminal,
substituting `<user>` by your OSC username:

```bash
sftp <user>@sftp.osc.edu   # E.g., 'jelmer@sftp.osc.edu'
```

``` {.bash-out}
The authenticity of host 'sftp.osc.edu (192.148.247.136)' can't be established.
ED25519 key fingerprint is SHA256:kMeb1PVZ1XVDEe2QiSumbM33w0SkvBJ4xeD18a/L0eQ.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

If this is your first time connecting to OSC SFTP server,
you'll get a message like the one shown above:
you should type `yes` to confirm.

Then, you may be asked for your OSC password, and after that,
you should see a "welcome" message like this:

``` {.bash-out}
******************************************************************************

This system is for the use of authorized users only.  Individuals using
this computer system without authority, or in excess of their authority,
are subject to having all of their activities on this system monitored
and recorded by system personnel.  In the course of monitoring individuals
improperly using this system, or in the course of system maintenance,
the activities of authorized users may also be monitored.  Anyone using
this system expressly consents to such monitoring and is advised that if
such monitoring reveals possible evidence of criminal activity, system
personnel may provide the evidence of such monitoring to law enforcement
officials.

******************************************************************************
Connected to sftp.osc.edu.
```

Now, you will have an `sftp` prompt (`sftp>`) instead of a regular shell prompt.

Familiar commands like `ls`, `cd`, and `pwd` will operate on the remote computer
(OSC, in this case),
and there are **local counterparts for them: `lls`, `lcd`, `lpwd`** &mdash;
for example:

```bash
# NOTE: I am prefacing sftp commands with the 'sftp>' prompt to make it explicit
#       these should be issued in an sftp session; but don't type that part.
sftp> pwd
```

``` {.bash-out}
Remote working directory: /users/PAS0471/jelmer
```

```bash
sftp> lpwd
```

``` {.bash-out}
Local working directory: /Users/poelstra.1/Desktop
```

<hr style="height:1pt; visibility:hidden;" />

#### Uploading files to OSC

To upload files to OSC, use `sftp`'s **`put` command**.

The syntax is `put <local-path> <remote-path>`,
and unlike with `scp` etc., you don't need to include the address to the remote
(because in an `stfp` session, you are simultaneously connected to both computers).
But like with `cp` and `scp`, you'll need the `-r` flag for recursive transfers,
i.e. transferring a directory and its contents.

```bash
# Upload fastqc.sh in a dir 'scripts' on your local computer to the PAS0471 Scratch dir:
sftp> put scripts/fastqc.sh /fs/scratch/PAS0471/sandbox

# Use -r to transfer directories:
sftp> put -r scripts /fs/scratch/PAS0471/sandbox

# You can use wildcards to upload multiple files:
sftp> put scripts/*sh /fs/scratch/PAS0471/sandbox
```

::: {.callout-warning}
#### `sftp` is rather primitive
The `~` shortcut to your Home directory does not work in `sftp`!
`sftp` is generally quite primitive and you also cannot use, for example,
tab completion or the recalling of previous commands with the up arrow.
:::

<hr style="height:1pt; visibility:hidden;" />

#### Downloading files from OSC

To download files from OSC, use the `get` command,
which has the syntax `get <remote-path> <local-path>`
(this is the other way around from `put` in that the remote path comes first,
but the same in that both use the order `<source> <target>`, like `cp` and so on).

For example:

```bash
sftp> get /fs/scratch/PAS0471/mcic-scripts/misc/fastqc.sh .

sftp> get -r /fs/scratch/PAS0471/sandbox/ .
```

#### Closing the SFTP connection 

When you're done, you can type `exit` or press <kbd>Ctrl</kbd>+<kbd>D</kbd>
to exit the `sftp` prompt.

<hr style="height:1pt; visibility:hidden;" />

### Globus

The second option for large transfers is **Globus**,
which has a browser-based GUI,
and is especially your best bet for very large transfers.
Some advantages of using Globus are that:

- It checks whether all files were transferred correctly and completely
- It can pause and resume automatically when you e.g. turn off your computer for a while
- It can be used to share files from OSC directly with collaborators even at
  different institutions.

Globus does need some setup,
including the installation of a piece of software that will run in the
background on your computer.

- Globus installation and configuration instructions:
  [Windows](https://docs.globus.org/how-to/globus-connect-personal-windows) /
  [Mac](https://docs.globus.org/how-to/globus-connect-personal-mac) /
  [Linux](https://docs.globus.org/how-to/globus-connect-personal-linux)
- [Globus transfer instructions](https://docs.globus.org/how-to/get-started/)
- [OSC's page on Globus](https://www.osc.edu/resources/getting_started/howto/howto_use_globus_overview)
