---
title: "Slurm batch jobs -- part II"
subtitle: "Week 7 -- Lecture B"
pagetitle: "w7b: Batch jobs 2"
date: 2025-10-03
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 7 overview"
    icon: book
    href: w7_overview.html
  - text: "w7a: Batch jobs I"
    icon: bookmarks
    href: w7a_slurm1.html
  - text: "Week 7 exercises"
    icon: pencil
    href: w7_exercises.html
engine: knitr
execute:
  eval: false
bibliography: ../references.bib
---

----------------------------------------------------------------------------------------------------

<br>

## Introduction

### Overview

TBA

### Learning goals

TBA

### Setting up

TBA

## Common Slurm options

Here, we'll go through the most commonly used Slurm options
(except `--account`, which we covered in the previous lecture).
As pointed out above, each of these can either be:

- Passed on the command line: `sbatch --account=PAS2880 myscript.sh` _(has precedence over the next)_
- Added at the top of the script you're submitting: `#SBATCH --account=PAS2880`.

Also, note that many Slurm options have a corresponding long
(e.g. `--account=`) and short format (e.g `-A`).
For clarity, we'll stick to long format options here.

### `--time`: Time limit ("wall time")

If you suspect or know that the default time limit of 1 hour may not be enough
for your job, use the `--time` option to request more time.
Note that your job will be **killed** (stopped) as soon as it hits the
time limit!

OSC bills you for **the time your job actually used**, not what you reserved.
But before you decide to start asking for 168 hours for every job,
note that jobs that request more time are likely to wait in the queue longer
before they start.

For single-node jobs, up to 168 hours (7 days) can be requested.
If that's not enough, you can request access to the `longserial` queue
for jobs of up to 14 days.
  
:::callout-tip
### What does "**wall time**" mean?
This is simply the actual amount of time that passes on the ("wall") clock.
This term is used to contrast it with "_core hours_":
if a job runs for 2 hour and used 8 cores,
the wall time is 2 hours while the number of core hours is 2 x 8 = 16.
:::

Accepted time formats include:

- `minutes` (e.g. `60` => 60 minutes)
- `hours:minutes:seconds` (e.g. `1:00:00` => 60 minutes)
- `days-hours` (e.g. `2-12` => two-and-a-half days)

An example, requesting 2 hours in the "minute-format":

```bash
#!/bin/bash
#SBATCH --time=120
```

Or 12 hours in the "hour-format":

```bash
#!/bin/bash
#SBATCH --time=12:00:00
```

:::{.callout-important}
## When in doubt, request more time!
It is common to be uncertain about how much time your job will take
(i.e., how long it will take for your script to finish).
Whenever this happens, ask for more, perhaps much more, time than what you
think/guesstimate you will need.

It is really annoying to have a job run out of time after several hours,
while the increase in queueing time for jobs that request more time is often
quite minimal at OSC.
:::

::: exercise
#### {{< fa user-edit >}} Exercise: exceed the time limit

Modify the `sleep.sh` script to reserve only 1 minute for the job,
while making the script run for longer than that by increasing the sleeping time
to at least 100 seconds.

If you succeed in exceeding the time limit, an error message will be printed.
Where do you think this error message will be printed: to the screen, in the Slurm log
file, or in `sleep.txt`?

After waiting for the job to be killed after 60 seconds,
check if you were correct and what the error message is.

<details><summary>Click for the solution</summary>

We request 1 minute of wall-time while we let the script sleep for 100 seconds:

```bash
#!/bin/bash
#SBATCH --account=PAS2880
#SBATCH --time=1

echo "I will sleep for 100 seconds" > sleep.txt
sleep 100s
echo "I'm awake! Done with script sleep.sh"
```

Submit it as usual:

```bash
sbatch scripts/sleep.sh
```
```bash-out
Submitted batch job 23641567
```

This would result in the following type of error,
which will be printed in the Slurm log file:

```bash-out-solo
slurmstepd: error: *** JOB 23641567 ON p0133 CANCELLED AT 2025-04-04T14:55:24 DUE TO TIME LIMIT ***
```
</details>
:::

### Cores

First, note that Slurm mostly uses the terms "core" and "CPU" interchangeably[^3].
More generally with bioinformatics tools,
"thread" is also commonly used interchangeably with core/CPU[^4].
Therefore, for our purposes, you can
**think of core, CPU, and thread as synonyms** that all refer to the
same sub-parts/components of a node that you can reserve and use separately.

[^3]: Even though technically, one CPU often contains multiple cores.
[^4]: Even though technically, one core often contains multiple threads.

Running a bioinformatics program with multiple threads/cores/CPUs ("multi-threading")
is very common, and this can make the running time of such programs much shorter.
While the specifics depend on the program,
using **8-12 cores** is often a sweet spot,
whereas asking for even more cores can lead to rapidly *diminishing returns*. 

While there are multiple related Slurm options (see the box below),
I recommend that you specify the number of threads/cores/CPUs with
**`--cpus-per-task`** (`-c`).

Typically, you will also want to inform the program that your script runs 
about the number of available cores ---
most have an option like `--cores` or `--threads`.
**You should set this to the same value `n` as the `--cpus-per-task`.**
An example, where we ask for 8 CPUs/cores/threads:

```bash
#!/bin/bash
#SBATCH --cpus-per-task=8

# And we tell a fictional program about that number of cores:
trimming_program.py --cores 8 sampleA_R1.fastq.gz
```

:::{.callout-note collapse="true"}
## What about nodes and tasks? _(Click to expand)_

**TBA FINISH**

You may have noticed that the long form of the above option is 
`--cpus-per-task` instead of just, say, `--cpus`. EXPAND

- Running multiple processes (tasks) or needing multiple nodes
  in a single batch job is _not_ common.

- Don't use options to change the number of _tasks_ or _nodes_,
  thereby keeping them to their defaults of 1
  (in which case the above `-c` option simply specifies the number of cores).
  
- You can specify the number of nodes with `--nodes` and the number of tasks
  with `--ntasks` and/or `--ntasks-per-node`; all have defaults of 1
  (see the table below).
  
- Only ask for **more than one node** when a program is parallelized with
  e.g. "MPI", which is rare in bioinformatics.

- For jobs with multiple processes (tasks),
  you can use `--ntasks=n` or `--ntasks-per-node=n` --- this is also quite rare!
  However, note in practice, specifying the number of tasks `n` with one of these
  options is equivalent to using `--cpus-per-task=n`,
  in the sense that both ask for `n` cores that can subsequently be used by a program
  in your script.
  Therefore, some people use `tasks` as opposed to `cpus` for multi-threading,
  and you may run across this in the OSC documentation too.
  Yes, this is confusing!

Here is an overview of the options related to cores, tasks, and nodes:

| Resource/use                  | short    | long                    | default
|-------------------------------|----------|-------------------------|:--------:| 
| Nr. of cores/CPUs/threads (per task)    | `-c 1`   | `--cpus-per-task=1`     | 1
| Nr. of "tasks" (processes) | `-n 1`   | `--ntasks=1`            | 1
| Nr. of tasks per node      | -        | `--ntasks-per-node=1`   | 1
| Nr. of nodes               | `-N 1`   | `--nodes=1`             | 1

: {.striped .hover}

:::

### `--mem`: RAM memory

The `--mem` option specifies the maximum amount of RAM
(Random Access Memory) available to your job.

The **default** amount of memory will depend on how many cores you reserved.
Standard cores have 4 GB of memory "on it", and therefore,
the default amount of memory you will get is 4 GB is per reserved core.
For example, if you specify `--cpus-per-task=4`, you will have 16 GB of memory.
And the default number of cores is 1, which gives you 4 GB.

Like with the time limit, your job gets **canceled** by Slurm when it hits
the memory limit (see the box below).

Because it is common to ask for multiple cores and due to the above-mentioned
adjustment of the memory based on the number of cores,
you will often end up having enough memory automatically,
and won't need to use the `--mem` option.

The maximum amount of memory you can request on regular Pitzer compute nodes
is 178 GB.
If you need more than that,
you will need one of the specialized `largemem` or `hugemem` nodes ---
switching to such a node generally happens automatically based on your requested amount^[
Though there are unfortunately "gaps" between the maximum and minimum amounts
of RAM on different nodes...
] --- see
[this OSC page for details on node types and associated memory on Pitzer](https://www.osc.edu/resources/technical_support/supercomputers/pitzer/batch_limit_rules).

The default `--mem` unit is MB (MegaBytes); append `G` for GB
(i.e. `100` means 100 MB, `10G` means 10 GB).
For example, to request 20 GB of RAM:

```sh
#!/bin/bash
#SBATCH --mem=20G
```

::: {.callout-warning collapse="true"}
#### It is not always clear what happened when your job ran out of memory _(Click to expand)_
Whereas you get a very clear Slurm error message when you hit the time limit
(as seen in the exercise above), hitting the memory limit can result in a variety of errors.

But look for keywords such as "Killed", "Out of Memory" / "OOM",
and "Core Dumped", as well as actual "dumped cores" in your working dir
(large files with names like `core.<number>`, these can be deleted).

If you see these or otherwise suspect that your job ran out of memory,
resubmit it with an increased requested amount of memory.
:::

::: exercise
#### {{< fa user-edit >}} Exercise: Adjusting cores and memory

Think about submitting a shell script that runs a bioinformatics tool like FastQC
as a batch job, in the following two scenarios:

1. The program has an option `--cores`, and you want to set that to 12.
   The program also says you'll need 60 GB of memory.
   What `#SBATCH` options will you use?

<details><summary>Click for the solution</summary>

Here, it will make sense to ask for `--mem` separately.

```bash
#SBATCH --cpus-per-task=12
#SBATCH --mem=60G
```

Alternatively, you could ask for 15 cores, but then instruct the program to use
only 12. Or you could reason that since you'll need 15 cores anyway due to the
amount of memory you'll need, you might as well instruct the program to use all
15, since this may well speed things up a little more.
</details>

1. The program has an option `--threads`, and you want to set that to 8.
   The program also says you'll need 25 GB of memory.
   What `#SBATCH` options related to this will you use?

<details><summary>Click for the solution</summary>

You should only need the following, since this will give you 8 * 4 = 32 GB of memory.
There is no point in "downgrading" the amount of memory.

```bash
#SBATCH --cpus-per-task=8
```

</details>
:::

### `--output`: Slurm log files

As you saw above, output from a script that would normally be printed to screen
will end up in a Slurm log file when it is submitted as a batch job.
By default, this file is created in the directory from which you submitted the script,
and is called `slurm-<job-number>.out`, e.g. `slurm-12431942.out`.

But it is possible to change the name of this file.
For instance, it can be useful to include the **name of the bioinformatics program**
that the script runs (or another kind of keyword describing the function of the script),
so that it's easier to recognize this file later.
You can do this with the `--output` option,
e.g. `--output=slurm-fastqc.out` if you were running FastQC.

But you'll generally want to keep the batch job number in the file name too[^6].
Since you won't know the batch job number in advance, you need a trick here --
and that is to use **`%j`**, which represents the batch job number:

```bash
#!/bin/bash
#SBATCH --output=slurm-fastqc-%j.out
```

[^6]: For instance, we might be running the FastQC script multiple times,
      and otherwise those Slurm log files would all have the same name and be overwritten!

**TBA - talk about outputting to a different dir?**

:::{.callout-note collapse="true"}
## The output streams `stdout` and `stderr`, and separating them _(Click to expand)_

By default, two different output streams from commands and programs are printed
to screen.
These are called "standard output" (`stdout`) for regular output and
"standard error" (`stderr`) for errors and sometimes warnings.
Both of these streams by default also end up in the same Slurm log file,
but it is possible to separate them into different files.

Because `stderr` often contains error messages,
it could be useful to have those in a separate file.
For example: an empty error-related files would mean that there were no errors.
You can make that happen with the `--error` option,
e.g. `--error=slurm-fastqc-%j.err`.

However, reality is more messy:
some programs print their main output not to a file but to standard out,
and their logging output, errors and regular messages alike, to standard error.
Yet other programs use `stdout` or `stderr` for _all_ messages.

**I therefore usually only specify `--output`,**
**such that both streams end up in that file.**
:::

### `--mail-type`: Receive emails

You can use the `--mail-type` option so you will receive emails when
a job begins, completes successfully, or fails.
You don't have to specify your email address:
you'll be automatically emailed on the address linked to your OSC account. 
I would recommend that for:

- **Shorter-running jobs** (roughly up to a few hours):
  only have Slurm send emails if they fail (`--mail-type=FAIL`).
  Especially when you submit many jobs at a time,
  you may otherwise overlook failure for some jobs.
  
  ```bash
  #!/bin/bash
  #SBATCH --mail-type=FAIL
  ```

- **Longer-running jobs**,
  have Slurm send emails both for failed and successfully completed jobs
  (`--mail-type=END,FAIL`).
  This is helpful because you don't want to have to keep checking in on jobs
  that run for many hours^[
  I would avoid having Slurm send you emails upon regular completion for shorter jobs,
  because you may get inundated with emails and then quickly start ignoring them
  altogether.].

  ```bash
  #!/bin/bash
  #SBATCH --mail-type=END,FAIL
  ```

::: {.callout-tip collapse="true"}
#### Get warned when your job is close to its time limit _(Click to expand)_
You may also find the `--mail-type` values `TIME_LIMIT_90`, `TIME_LIMIT_80`,
and `TIME_LIMIT_50` useful for very long-running jobs,
which will warn you when the job is at 90/80/50% of the time limit.
For example, it is possible to email OSC to ask for an extension on individual jobs.
You shouldn't do this often, but if you have a job that ran for 6 days and it
looks like it may time out, this may well be worth it.
:::

### Table with `sbatch` options

Here are the main options we discussed above:

| Resource/use        | short      | long                 | default
|---------------|---------|------------------|:---------:|
| Project to be billed          | `-A PAS2880` | `--account=PAS2880`    | _N/A_
| Time limit                    | `-t 4:00:00` | `--time=4:00:00`      | 1:00:00
| Nr of nodes                   | `-N 1`       | `--nodes=1`            | 1
| Nr of cores                   | `-c 1`       | `--cpus-per-task=1`    | 1
| Memory limit per node         | -          | `--mem=4G`             | *(4G)*
| Log output file               | `-o`       |  `--output=slurm-fastqc-%j.out`
| Get email when job ends<br>/ ends or fails | -        | `--mail-type=END` <br> `--mail-type=END,FAIL`

: {.striped .hover}

<hr style="height:1pt; visibility:hidden;" />

And some additional ones:

| Resource/use            | long option example
|-----------|------------|
| Job name (will e.g. be displayed in `squeue` output)    | `--job-name=fastqc`
| Partition (=queue type)                      | `--partition=longserial` <br> `--partition=hugemem`
| Only allow job to begin after a specific time | `--begin=2025-04-05T12:00:00`
| Only allow job to begin after another job has finished | `--dependency=afterany:123456`
| Nr of "tasks" (processes)     | `--ntasks=1`
| Nr of tasks per node          | `--ntasks-per-node=1`
| Put error output (*stderr*) from into a separate file. When using this option, only standard (non-error, *stdout*) output will now be put into the file specified with `--output`. | `--error=slurm-fastqc-%j.err` |

: {.striped .hover}

## Batch job examples with FastQC

Last week, we used a `for` loop to run FastQC interactively for every FASTQ file.
This was rather quick, but keep in mind that our practice FASTQ files are only 5%
of their original sizes.
Additionally, other bioinformatics programs may take much longer.
The best way to speed things up is by submitting a batch job for each sample/file,
because they may all run simultaneously^[
But keep in mind that batch jobs are sometimes queued/waiting for a while,
especially if you submit large amounts of jobs.].
So let's practice with submitting a batch job for each FastQC run.

We'll start with submitting one for a single file, and then loop over all files.
First, get the script:

```bash
cp -v ../week05/scripts/fastqc.sh scripts/
```

::: {.callout-note collapse="true"}
### ...Or create a new script and copy this code into it _(Click to expand)_
```bash
#!/bin/bash
set -euo pipefail

# Load the OSC module for FastQC
module load fastqc/0.12.1

# Copy the placeholder variables
fastq="$1"
outdir="$2"

# Initial logging
echo "# Starting script fastqc.sh"
date
echo "# Input FASTQ file:   $fastq"
echo "# Output dir:         $outdir"
echo

# Create the output dir if needed
mkdir -p "$outdir"

# Run FastQC
fastqc --outdir "$outdir" "$fastq"

# Final logging
echo "# Used FastQC version:"
fastqc --version
echo
echo "# Successfully finished script fastqc.sh"
date
```
:::

### Modify the script for usage with Slurm

Next, add Slurm options with the following `#SBATCH` lines in the script --
note that you'll be asking for 4 cores:

```bash
#!/bin/bash
#SBATCH --account=PAS2880
#SBATCH --cpus-per-task=4
#SBATCH --mail-type=FAIL
#SBATCH --name=slurm-fastqc-%j.out
```

When you have multiple cores at your disposal in a batch job,
you should almost always **explicitly tell the program you're running about this**.
Some programs default to using 1 core while others try to auto-detect the number of cores,
but any auto-detection tends to be inappropriate:
the program would detect the total number of cores on the OSC node rather than the
number that we have reserved.

::: exercise
#### Exercise: Let FastQC use multiple core

Change the FastQC command in the script so that FastQC will use all 8 reserved cores.
(Run `fastqc --help` to find the relevant option.)

<details><summary>_Click to see the solution_</summary>

Let FastQC know how many cores you have reserved by _editing the command_
to include `--threads 8`:

```bash
# [Other FastQC options not shown - same as before]
fastqc \
    --threads 8 \
```

</details>

:::


### Submit a single test batch job

Now, you're ready to submit the script.
Let's test it for _one sample_ first:

```bash
fastq_file=../garrigos-data/fastq/ERR10802863_R1.fastq.gz
sbatch scripts/fastqc.sh "$fastq_file" results/fastqc
```
```bash-out
submitted batch job TBA
```

#### Monitoring the batch job

Next, monitor your job by checking its status in the Slurm queue:

```bash
squeue -u $USER -l
```
```bash-out
TBA
```

After a while:

- You will know that your job has stopped running
  (either due to failure or because it finished succesfully)
  when it is no longer listed in the `squeue` output
- If you _additionally_ didn't receive an email from Slurm,
  this implies the job succeeded --
  you should have gotten an email if the job failed due to the
  `#SBATCH --mail-type=FAIL` line
  
#### Checking the output files

But either way, don't forget to look at the output files:

- **Slurm log file**:
  The combination of having strict bash `set` settings and the "_Succesfully finished_"
  `echo` line at the end of the script
  means that if you see that line printed, the script encountered no errors.
  Nevertheless, you should also look at the rest of this file,
  because a program's "logging statements" may have useful information,
  including output summaries but also warnings.

- **The program's main output files**:
  As discussed, most bioinformatics tools don't just print "logging" information
  that ends up in the Slurm log file, but will also have output files
  (in the case of of FastQC, and HTML and a Zip file).
  Therefore, always check the output dir for the presence of output files

Checking the Slurm log file:

- Make sure it's there:

  ```bash
  ls
  ```
  ```bash-out
  slurm-fastqc-TBA.out
  ```

- Quick check that the "marker" line that indicates a successful run is printed:

  ```bash
  tail slurm-fastqc*.out
  ```
  ```bash-out
  TBA
  ```

- Take a closer look at the file:

  ```bash
  less slurm-fastqc*
  ```

Checking for the presence of the main FastQC output files:

```bash
ls -lh results/fastqc
```
```bash-out
TBA
```

::: callout-tip
#### Pay attention to file sizes
especially if you're not going to opem the output files right aways,
always pay attention to the file sizes.
Sometimes programs produce 0-byte (or way-too-small) output files when they fail.
:::

#### Cleaning up

Because this was a test-run and you will now run a loop to analyze each sample,
remove all outputs:

```bash
rm -r results/fastqc slurm-fastqc*
```

### Submitting a job for each file

Now, loop over all FASTQ files to submit a job for each file: 

```bash
for fastq_file in garrigos-data/fastq/*_R1.fastq.gz; do
    sbatch scripts/fastqc.sh "$fastq_file" results/fastqc
done
```
```bash-out
Submitted batch job TBA
Submitted batch job TBA
Submitted batch job TBA
Submitted batch job TBA
# [...output truncated...]
```

As you saw, all these jobs were submitted in very quick succession, ...

Check the queue:

```bash
squeue -u $USER -l
```

Once all jobs have finished (are no longer listed in `squeue` output), let's:

```bash-out
results                    slurm-fastqc-27902531.out  slurm-fastqc-27902543.out  slurm-fastqc-27902555.out
run                        slurm-fastqc-27902532.out  slurm-fastqc-27902544.out  slurm-fastqc-27902556.out
scripts                    slurm-fastqc-27902533.out  slurm-fastqc-27902545.out  slurm-fastqc-27902557.out
slurm-fastqc-27902522.out  slurm-fastqc-27902534.out  slurm-fastqc-27902546.out  slurm-fastqc-27902558.out
slurm-fastqc-27902523.out  slurm-fastqc-27902535.out  slurm-fastqc-27902547.out  slurm-fastqc-27902559.out
slurm-fastqc-27902524.out  slurm-fastqc-27902536.out  slurm-fastqc-27902548.out  slurm-fastqc-27902560.out
slurm-fastqc-27902525.out  slurm-fastqc-27902537.out  slurm-fastqc-27902549.out  slurm-fastqc-27902561.out
slurm-fastqc-27902526.out  slurm-fastqc-27902538.out  slurm-fastqc-27902550.out  slurm-fastqc-27902562.out
slurm-fastqc-27902527.out  slurm-fastqc-27902539.out  slurm-fastqc-27902551.out  slurm-fastqc-27902563.out
slurm-fastqc-27902528.out  slurm-fastqc-27902540.out  slurm-fastqc-27902552.out  slurm-fastqc-27902564.out
slurm-fastqc-27902529.out  slurm-fastqc-27902541.out  slurm-fastqc-27902553.out  slurm-fastqc-27902565.out
slurm-fastqc-27902530.out  slurm-fastqc-27902542.out  slurm-fastqc-27902554.out
```

You now arguably have too many Slurm log files to go through, so what to do next?

- Take a close look at (at least) one Slurm log file:

  ```bash
  less slurm-fastqc-*
  ```

- Check the last few lines of all of them:

  ```bash
  tail slurm-fastqc-*
  ```

```bash
tail slurm-fastqc*
```
```bash-out
==> slurm-fastqc-27902563.out <==
Approx 80% complete for ERR10802885_R2.fastq.gz
Approx 85% complete for ERR10802885_R2.fastq.gz
Approx 90% complete for ERR10802885_R2.fastq.gz
Approx 95% complete for ERR10802885_R2.fastq.gz
Approx 100% complete for ERR10802885_R2.fastq.gz
Analysis complete for ERR10802885_R2.fastq.gz

# Successfully finished script fastqc.sh
Sun Mar 31 16:30:54 EDT 2024

==> slurm-fastqc-27902564.out <==
Approx 80% complete for ERR10802886_R1.fastq.gz
Approx 85% complete for ERR10802886_R1.fastq.gz
Approx 90% complete for ERR10802886_R1.fastq.gz
Approx 95% complete for ERR10802886_R1.fastq.gz
Approx 100% complete for ERR10802886_R1.fastq.gz
Analysis complete for ERR10802886_R1.fastq.gz

# Successfully finished script fastqc.sh
Sun Mar 31 16:30:54 EDT 2024

==> slurm-fastqc-27902565.out <==
Approx 80% complete for ERR10802886_R2.fastq.gz
Approx 85% complete for ERR10802886_R2.fastq.gz
Approx 90% complete for ERR10802886_R2.fastq.gz
Approx 95% complete for ERR10802886_R2.fastq.gz
Approx 100% complete for ERR10802886_R2.fastq.gz
Analysis complete for ERR10802886_R2.fastq.gz

# Successfully finished script fastqc.sh
Sun Mar 31 16:30:54 EDT 2024

# [...output truncated...]
```

Finally, to check the FastQC output files:

```bash
ls -lh results/fastqc
```
```bash-out
total 48M
-rw-rw----+ 1 poelstra PAS0471 718K Mar 31 16:29 ERR10802863_R1_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 364K Mar 31 16:29 ERR10802863_R1_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 688K Mar 31 16:29 ERR10802863_R2_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 363K Mar 31 16:29 ERR10802863_R2_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 714K Mar 31 16:29 ERR10802864_R1_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 366K Mar 31 16:29 ERR10802864_R1_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 695K Mar 31 16:29 ERR10802864_R2_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 351K Mar 31 16:29 ERR10802864_R2_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 713K Mar 31 16:29 ERR10802865_R1_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 367K Mar 31 16:29 ERR10802865_R1_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 698K Mar 31 16:29 ERR10802865_R2_fastqc.html
-rw-rw----+ 1 poelstra PAS0471 358K Mar 31 16:29 ERR10802865_R2_fastqc.zip
-rw-rw----+ 1 poelstra PAS0471 718K Mar 31 16:29 ERR10802866_R1_fastqc.html
# [...output truncated...]
```

If everything looks good,
and we are convinced that all these jobs have succesfully finished,
all that is left is cleaning up the Slurm log files.
In this case, it makes sense to **keep these files**,
as they will contain information ... TBA.

But we do want to move them out of the working dir.
It often makes sense to store them in a subdir of the program's outdir, e.g.:

```bash
mkdir results/fastqc/logs
mv slurm-fastqc-* logs/
```

### Recap: Making sure your jobs ran successfully

To recap, here is an overview of basic strategies to monitor your batch jobs:

- To see whether your job(s) have started,
  check the queue (with `squeue`) or check for the appearance of Slurm log files
  (with `ls`).
  
- Once the jobs are no longer listed in the queue,
  they will have finished: either successfully or because of an error.

- When you've submitted many jobs that run the same script for different samples/files:
  - For at least 1 one of the jobs,
    carefully read the full Slurm log file, and check other output files,
  - Check whether no jobs have failed: via email when using `--mail-type=END`,
    or by checking the `tail` of each log for messages like
    "Successfully finished script".
  - Check that you have the expected number of output files and that no files
    have size zero (run `ls -lh`).

::: callout-tip
#### TBA Refer to `scontrol` etc for detailed stats
:::

::: callout-tip
#### Job monitoring tip: See output added to the Slurm log file in real time
Text will be added to the Slurm log file in real time as the running script
(or the program ran by the script) outputs it.
However, the output that commands like `cat` and `less` print are static.

Therefore, if you find yourself opening/printing the contents of the Slurm log
file again and again to keep track of progress,
then instead **use `tail -f`**, which will "follow" the file and _will_ print new
text as it's added to the Slurm log file:

```bash
# See the last lines of the file, with new contents added in real time
tail -f slurm-12520046.out
```

To exit the `tail -f` livestream, press <kbd>Ctrl</kbd>+<kbd>C</kbd>.
:::
