---
title: "Conda exercises"
---


## Exercise 1: Create a FastQC Conda environment

The version of FastQC on OSC (0.11.8) is not the latest one (0.12.1).
Let's assume that you really need the latest version for your analysis:

1. Create a Conda environment for FastQC and install FastQC version 0.12.1 into it.
2. Activate the environment and check that you have the correct version of FastQC.

## Exercise 5: Create a Nextflow Conda environment

Next week, we'll work with Nextflow and the affiliated community project nf-core.
Create a single Conda environment with both Nextflow and the nf-core tools.

## Solutions

### Exercise 1

<details><summary>1 - Create a FastQC Conda environment</summary>

When you don't specify the version, the latest one should be installed ---
at least when you're using a "fresh" environment (there could be complicating
factors if you already had other software in the same environment):

```bash
module load miniconda3/24.1.2-py310
conda create -y -n fastqc -c bioconda fastqc
```

But to be more explicit, you could replace the `fastqc` at the end of the line
with `fastqc=0.12.1`.

</details>

<details><summary>2 - Activate the environment and check the version</summary>
```bash
conda activate fastqc
fastqc --version
```
```bash-out
FastQC v0.12.1
```
</details>


### Exercise 5

<details><summary>Create a Nextflow + nf-core Conda environment</summary>

```bash
module load miniconda3/24.1.2-py310
conda create -y -n nextflow-23.10 -c bioconda nextflow=23.10.1 nf-core=2.13.1
```

Check that it works:

```bash
conda activate nextflow-23.10
nextflow -v
```
```bash-out
nextflow version 23.10.1.5891
```
```bash
nf-core --version
```
```bash-out
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.13.1 - https://nf-co.re

nf-core, version 2.13.1
```

</details>

<br>

