---
title: "Course Glossary"
author: Jelmer Poelstra
date: 2025-08-25
---

- Git	 Software for version control
- GitHub	 A website that hosts git projects, which are known as repositories
- Markdown	 A simple text markup language (think LaTeX or HTML but much simpler)
- OSC	 The Ohio Supercomputer Center
- shell	 The Unix shell is a command-line interface to your operating system that runs within a terminal.
- Bash There are several shell flavors, and in this course, we will be working with the bash shell.
- Nextflow
- SLURM	 The compute job scheduling system used at the Ohio Supercomputer Center
- Unix	 A family of operating systems that includes Mac and Linux, but not Windows
- CLI	 Command-line Interface -- a software interface with which one interacts by typing commands (cf. GUI)
- dir	 Directory, which is Unix-speak for a folder on your computer
- GUI	 Graphical User Interface -- a visual software interface with which one interacts by clicking
- Hard-coding

The analysis of large biological datasets, especially omics-related data,
is often referred to as "bioinformatics".
Within the field of bioinformatics, we may loosely distinguish between:

- The **development** of bioinformatics methods
  (say: an algorithm to align DNA sequences)
  and of software that implements these methods

- The **application** of abovementioned methods and software to analyze data

With that distinction in mind, this course will teach you the latter:
**applied bioinformatics**.
