---
title: "Solutions"
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Solutions

<details><summary>**1.** Create a new directory at OSC for these exercises, and move there.</summary>
For example:

```bash
mkdir /fs/ess/PAS2880/users/$USER/week03/exercises
cd /fs/ess/PAS2880/users/$USER/week03/exercises
```
</details>

<details><summary>**2.** Initialize a local Git repository inside your new directory.</summary>

```bash
git init
```
</details>

<details><summary>**3.** Create a README file in Markdown format.</summary>

```bash
echo "# This dir is for the week3 exercises on Git" > README.md
```
</details>

<details><summary>**4.** Stage and then commit the README file with an appropriate commit message.</summary>

```bash
git add README.md
git commit -m "Added a README file"
```
</details>

<details><summary>**5.** Create a second Markdown file with some more contents.</summary>

Create a new empty file:

```bash
touch git_notes.md
```

Then, open the file in the VS Code editor and describe the Git workflow in your own words. 
</details>

<details><summary>**6.** Create at least two commits while you work on the Markdown file.</summary>

- First commit, after adding a first batch of content to the Markdown file:

```bash
git add git_notes.md
git commit -m "Started a document with notes on Git"
```

- Make additional changes to `git_notes.md`, and commit again:

```bash   
git add git_notes.md
git commit -m "Descriptive commit message #2"
```
</details>

<details><summary>**8.** Update the `README.md` file.</summary>

```bash
echo "Added a file with notes on Git" >> README.md
```
</details>

<details><summary>**8.** Stage and commit the updated README file.</summary>

```bash
git add README.md
git commit -m "Added a description of the repo's contents to the README"
```
</details>

<details><summary>**9.** Create a `results` dir and file, and make Git ignore this directory.</summary>

- Create the dir and file that should be ignored:
    
```bash
mkdir results
touch results/results.txt
```

- Create a gitignore file with instructions to ignore the `results` dir:

```bash
echo "results/" > .gitignore
```
    
- Add and commit the `.gitignore` file:

```bash
git add .gitignore
git commit -m "Added a gitignore file"
```
</details>


