---
title: "Untitled"
---

## FASTQ

7. **_Bonus_**: Can you find out, with a single command,
   what the total number of reads across all R1 files is?

   <details><summary>_Click here for a hint_</summary>
   Use `zcat` with a globbing (file selection) pattern with a `*` to operate on
   all R1 files at once -- then pipe that into the familiar line counting command.
   </details>

### GTF

9. For a gene of interest,
   you may wonder how many exons and other annotated features it has.
   GTF files have an implicit hierarchical structure,
   where e.g. each exon row contains a reference to the gene that the exon is a
   part of (i.e., its "parent") in the final column.
   With that in mind: for gene `LOC120427725`, print a count table of its feature types.
   _(You can assume that this gene's name does not occur in any lines_
   _describing features that are not part of the gene.)_

10. **_Bonus_**: Produce a 3-column table with the sequence name, start position,
    and end position of each _distinct_ start codon in the GTF file.
    Store that table in a file `start_codons.tsv`.
    _(You can assume that the string `start_codon` occurs only in the third column,_
    _so that all lines with that string contain start codon features.)_

11. **_Bonus_**: In this genome, which sequence (chromosome/scaffold/contig)
    appears to be the largest one?

    <details><summary>_Click here for a hint_</summary>
    This information is not directly contained in this GTF file,
    but if you are able find the highest number in the (start or) end coordinate
    column, and check which sequence that is on, you should get the correct answer.
    
    To do this, you need to first `cut` the relevant columns, and then `sort`
    specifically by the coordinate column (using the `-k` option).
    </details>
    
12. **_Bonus_**: Count the number of small nuclear RNAs (`snRNA`) in the annotation.
    You'll want a "gene"-level count
    (i.e. a count of the number of `gene` features annotated as `snRNA`),
    but because the word "snRNA" also occurs for other features,
    the search pattern `snRNA` would not work.
    An initial `grep` search would help to find a good final search pattern ---
    to spare you that trouble, it should be: `gene_biotype "snRNA"`.
    But this poses another challenge: the pattern contains double quotes (`"`),
    which we've been using to indicate where the search pattern begins and ends.

    <details><summary>_Click here for a hint_</summary>
    Use single quotes (`'`) instead of double quotes around the entire pattern.
    </details>

### Git

9. **Create a `results` directory with an empty file and make Git ignore this directory.**\
   Also, commit your `.gitignore` file.

### Part II: Create and sync an online version of the repo

Phew, you made several commits! Time to share all this work with the world.

10. **Create a GitHub repository.**\
    Go to <https://github.com>, sign in, and create a new repository.
    Name the repo "PRACS25_w04-assignment"^[
    This is not the same name as your dir on OSC, which is OK.].
    Like in class, create a completely *empty* GitHub repository,
    because you will upload all the contents from your local repo.
    
11. **Push your local repo to the online counterpart you just created.**\
    When you're done, click the `Code` button, and
    admire the nicely rendered README on the front page of your GitHub repo.

12. **Open a GitHub Issue**\
    Open an Issue for your repo: in the Issues tab, click "New Issue",
    and in the box where you can type your issue, tag the instructor.
    For example:
    
    ```markdown
    Hey @jelmerp, can you please take a look at my repo?
    ```
