---
title: "Untitled"
---

### Exercise 1

<details><summary>**C)** solution _(click to expand)_</summary>
Yes, you can run these two steps at the same time:
both use the raw FASTQ files as the input, so the steps don't depend on each other. 
</details>

<details><summary>**D)** solution 1: check the queue _(click to expand)_</summary>

- Check the Slurm queue:
  
  ```bash
  squeue -u $USER -l
  # [Output not shown]
  ```
</details>

<details><summary>**D)** solution 2: Check the FastQC output _(click to expand)_</summary>

```bash
# Take a close look at 1 or 2 log files with 'less':
less slurm-fastqc*
# [Showing one output file by means of example]
```
```bash-out
# Starting script fastqc.ch
Fri Apr 12 09:34:40 EDT 2024
# Input FASTQ file:   ../../garrigos-data/fastq/ERR10802863_R1.fastq.gz
# Output dir:         results/fastqc

application/gzip
Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
Approx 20% complete for ERR10802863_R1.fastq.gz
Approx 25% complete for ERR10802863_R1.fastq.gz
Approx 30% complete for ERR10802863_R1.fastq.gz
Approx 35% complete for ERR10802863_R1.fastq.gz
Approx 40% complete for ERR10802863_R1.fastq.gz
Approx 45% complete for ERR10802863_R1.fastq.gz
Approx 50% complete for ERR10802863_R1.fastq.gz
Approx 55% complete for ERR10802863_R1.fastq.gz
Approx 60% complete for ERR10802863_R1.fastq.gz
Approx 65% complete for ERR10802863_R1.fastq.gz
Approx 70% complete for ERR10802863_R1.fastq.gz
Approx 75% complete for ERR10802863_R1.fastq.gz
Approx 80% complete for ERR10802863_R1.fastq.gz
Approx 85% complete for ERR10802863_R1.fastq.gz
Approx 90% complete for ERR10802863_R1.fastq.gz
Approx 95% complete for ERR10802863_R1.fastq.gz
Approx 100% complete for ERR10802863_R1.fastq.gz
Analysis complete for ERR10802863_R1.fastq.gz
  
# Used FastQC version:
FastQC v0.12.1
# Successfully finished script fastqc.sh
Fri Apr 12 09:34:47 EDT 2024
```

```bash
# Optional: check the last lines of each Slurm log file
# (And/or check your email for failed job messages)
tail slurm-fastqc*
# [Output not shown, each file should end with "Successfully finished script" line and the date]
```

```bash
# Move the Slurm log files to an output dir:
mv slurm-fastqc* results/fastqc/logs/
```

```bash
# Check the main FastQC output files:
ls -lh results/fastqc
```
```bash-out
total 48M
-rw-r--r-- 1 jelmer PAS0471 718K Apr 12 09:34 ERR10802863_R1_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 364K Apr 12 09:34 ERR10802863_R1_fastqc.zip
-rw-r--r-- 1 jelmer PAS0471 688K Apr 12 09:34 ERR10802863_R2_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 363K Apr 12 09:34 ERR10802863_R2_fastqc.zip
-rw-r--r-- 1 jelmer PAS0471 714K Apr 12 09:34 ERR10802864_R1_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 366K Apr 12 09:34 ERR10802864_R1_fastqc.zip
-rw-r--r-- 1 jelmer PAS0471 695K Apr 12 09:34 ERR10802864_R2_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 351K Apr 12 09:34 ERR10802864_R2_fastqc.zip
-rw-r--r-- 1 jelmer PAS0471 713K Apr 12 09:34 ERR10802865_R1_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 367K Apr 12 09:34 ERR10802865_R1_fastqc.zip
# [...output truncated...]
```
</details>

<details><summary>**D)** solution 3: Check the TrimGalore output _(click to expand)_</summary>

```bash
# Take a close look at 1 or 2 log files with 'less':
less slurm-trimgalore*
# [Showing the top of one output file by means of example]
```
```bash-out
# Starting script trimgalore.sh
Fri Apr 12 09:35:18 EDT 2024
# Input R1 FASTQ file:      ../../garrigos-data/fastq/ERR10802863_R1.fastq.gz
# Input R2 FASTQ file:      ../../garrigos-data/fastq/ERR10802863_R2.fastq.gz
# Output dir:               results/trimgalore

Path to Cutadapt set as: 'cutadapt' (default)
# [...output truncated...]
```

```bash
# Check the main TrimGalore output files:
ls -lh results/trimgalore
```
```bash-out
total 951M
-rw-r--r-- 1 jelmer PAS0471  20M Apr 12 09:35 ERR10802863_R1.fastq.gz
-rw-r--r-- 1 jelmer PAS0471 2.4K Apr 12 09:35 ERR10802863_R1.fastq.gz_trimming_report.txt
-rw-r--r-- 1 jelmer PAS0471 674K Apr 12 09:35 ERR10802863_R1_val_1_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 349K Apr 12 09:35 ERR10802863_R1_val_1_fastqc.zip
-rw-r--r-- 1 jelmer PAS0471  21M Apr 12 09:35 ERR10802863_R2.fastq.gz
-rw-r--r-- 1 jelmer PAS0471 2.4K Apr 12 09:35 ERR10802863_R2.fastq.gz_trimming_report.txt
-rw-r--r-- 1 jelmer PAS0471 676K Apr 12 09:35 ERR10802863_R2_val_2_fastqc.html
-rw-r--r-- 1 jelmer PAS0471 341K Apr 12 09:35 ERR10802863_R2_val_2_fastqc.zip
# [...output truncated...]
```

</details>

<hr style="height:1pt; visibility:hidden;" />

### Exercise 2

<details><summary> Runner script solution: index _(click to expand)_</summary>
```bash
# Step 3: Align the reads with STAR
# A) Index the reference genomes
sbatch scripts/star_index.sh "$fasta" "$gtf" results/star/index
```
</details>

<details><summary> Runner script solution: align _(click to expand)_</summary>
```bash
# B) Align the reads to the index
for R1 in results/trimgalore/*R1.fastq.gz; do
    sbatch scripts/star_align.sh "$R1" results/star/index "$gtf" results/star
done
```
</details>

<details><summary> Indexing Slurm log _(click to expand)_</summary>
```bash-out-solo
# Starting script star_index.sh
Fri Apr 12 10:37:44 EDT 2024
# Input assembly FASTA:           ../../garrigos-data/ref/GCF_016801865.2.fna
# Input annotation GTF:           ../../garrigos-data/ref/GCF_016801865.2.gtf
# Output dir:                     results/star/index
# Number of threads:              16

        /fs/ess/PAS0471/jelmer/conda/star/bin/STAR-avx2 --runMode genomeGenerate --genomeFastaFiles ../../garrigos-data/ref/GCF_016801865.2.fna --sjdbGTFfile ../../garrigos-data/ref/GCF_016801865.2.gtf --genomeDir results/star/index --runThreadN 16
        STAR version: 2.7.11b   compiled: 2024-03-19T08:38:59+0000 :/opt/conda/conda-bld/star_1710837244939/work/source
Apr 12 10:37:44 ..... started STAR run
Apr 12 10:37:44 ... starting to generate Genome files
Apr 12 10:37:51 ..... processing annotations GTF
!!!!! WARNING: --genomeSAindexNbases 14 is too large for the genome size=566354144, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 13
Apr 12 10:37:55 ... starting to sort Suffix Array. This may take a long time...
Apr 12 10:37:58 ... sorting Suffix Array chunks and saving them to disk...
Apr 12 10:39:06 ... loading chunks from disk, packing SA...
Apr 12 10:39:16 ... finished generating suffix array
Apr 12 10:39:16 ... generating Suffix Array index
Apr 12 10:40:36 ... completed Suffix Array index
Apr 12 10:40:36 ..... inserting junctions into the genome indices
Apr 12 10:41:05 ... writing Genome to disk ...
Apr 12 10:41:06 ... writing Suffix Array to disk ...
Apr 12 10:41:07 ... writing SAindex to disk
Apr 12 10:41:08 ..... finished successfully

# Used STAR version:
2.7.11b
# Successfully finished script star_index.sh
Fri Apr 12 10:41:08 EDT 2024
```
</details>

<details><summary> Example alignment Slurm log _(click to expand)_</summary>
```bash-out-solo
# Starting script star_align.sh
Fri Apr 12 10:41:45 EDT 2024
# Input R1 FASTQ file:            results/trimgalore/ERR10802863_R1.fastq.gz
# Input R2 FASTQ file:            results/trimgalore/ERR10802863_R2.fastq.gz
# Input genome index:             results/star/index
# Input annotation GTF:           ../../garrigos-data/ref/GCF_016801865.2.gtf
# Output dir:                     results/star
# Number of threads:              8

        /fs/ess/PAS0471/jelmer/conda/star/bin/STAR-avx2 --readFilesIn results/trimgalore/ERR10802863_R1.fastq.gz results/trimgalore/ERR10802863_R2.fastq.gz --genomeDir results/star/index --sjdbGTFfile ../../garrigos-data/ref/GCF_016801865.2.gtf --runThreadN 8 --readFilesCommand zcat --outFileNamePrefix results/star/ERR10802863_ --outSAMtype BAM SortedByCoordinate
        STAR version: 2.7.11b   compiled: 2024-03-19T08:38:59+0000 :/opt/conda/conda-bld/star_1710837244939/work/source
Apr 12 10:41:45 ..... started STAR run
Apr 12 10:41:45 ..... loading genome
Apr 12 10:41:48 ..... processing annotations GTF
Apr 12 10:41:50 ..... inserting junctions into the genome indices
Apr 12 10:42:06 ..... started mapping
Apr 12 10:42:21 ..... finished mapping
Apr 12 10:42:21 ..... started sorting BAM
Apr 12 10:42:22 ..... finished successfully

# Used STAR version:
2.7.11b
# Successfully finished script star_align.sh
Fri Apr 12 10:42:22 EDT 2024
```
</details>

<hr style="height:1pt; visibility:hidden;" />

### Exercise 3

<details><summary>Runner script solution _(click to expand)_</summary>
```bash
# Step 4: Create a gene count table with featureCounts
sbatch scripts/featurecounts.sh results/star "$gtf" "$strandedness" "$count_table"
```
</details>

<details><summary> featureCounts Slurm log _(click to expand)_</summary>
```bash-out-solo
# Starting script featurecounts.sh
Fri Apr 12 10:45:05 EDT 2024
# Input dir:                      results/star
# Input annotation GTF:           ../../garrigos-data/ref/GCF_016801865.2.gtf
# Strandedness:                   1
# Output file:                    results/featurecounts/counts.tsv
# Number of threads:              8


        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 22 BAM files                                     ||
||                                                                            ||
||                           ERR10802863_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802864_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802865_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802866_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802867_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802868_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802869_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802870_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802871_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802874_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802875_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802876_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802877_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802878_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802879_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802880_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802881_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802882_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802883_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802884_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802885_Aligned.sortedByCoord.out.bam        ||
||                           ERR10802886_Aligned.sortedByCoord.out.bam        ||
||                                                                            ||
||             Output file : counts.tsv                                       ||
||                 Summary : counts.tsv.summary                               ||
||              Paired-end : yes                                              ||
||        Count read pairs : yes                                              ||
||              Annotation : GCF_016801865.2.gtf (GTF)                        ||
||      Dir for temp files : results/featurecounts                            ||
||                                                                            ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : counted                                          ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file GCF_016801865.2.gtf ...                               ||
||    Features : 166177                                                       ||
||    Meta-features : 18855                                                   ||
||    Chromosomes/contigs : 162                                               ||
||                                                                            ||
|| Process BAM file ERR10802863_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 434318                                               ||
||    Successfully assigned alignments : 401890 (92.5%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802864_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 453285                                               ||
||    Successfully assigned alignments : 420396 (92.7%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802865_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 450789                                               ||
||    Successfully assigned alignments : 409131 (90.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802866_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 453068                                               ||
||    Successfully assigned alignments : 420634 (92.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802867_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 469293                                               ||
||    Successfully assigned alignments : 438336 (93.4%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802868_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 453389                                               ||
||    Successfully assigned alignments : 410776 (90.6%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802869_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 446533                                               ||
||    Successfully assigned alignments : 413794 (92.7%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802870_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 456614                                               ||
||    Successfully assigned alignments : 423864 (92.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802871_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 442307                                               ||
||    Successfully assigned alignments : 403651 (91.3%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802874_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 441439                                               ||
||    Successfully assigned alignments : 396114 (89.7%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802875_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 397679                                               ||
||    Successfully assigned alignments : 372151 (93.6%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802876_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 445342                                               ||
||    Successfully assigned alignments : 414676 (93.1%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802877_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 356283                                               ||
||    Successfully assigned alignments : 332904 (93.4%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802878_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 403889                                               ||
||    Successfully assigned alignments : 379018 (93.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802879_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 399408                                               ||
||    Successfully assigned alignments : 373530 (93.5%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802880_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 447356                                               ||
||    Successfully assigned alignments : 413845 (92.5%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802881_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 388963                                               ||
||    Successfully assigned alignments : 364413 (93.7%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802882_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 432376                                               ||
||    Successfully assigned alignments : 397751 (92.0%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802883_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 431581                                               ||
||    Successfully assigned alignments : 392518 (90.9%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802884_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 396408                                               ||
||    Successfully assigned alignments : 371702 (93.8%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802885_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 411164                                               ||
||    Successfully assigned alignments : 378424 (92.0%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Process BAM file ERR10802886_Aligned.sortedByCoord.out.bam...              ||
||    Strand specific : stranded                                              ||
||    Paired-end reads are included.                                          ||
||    Total alignments : 444531                                               ||
||    Successfully assigned alignments : 416370 (93.7%)                       ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "results/featurecounts/c  ||
|| ounts.tsv.summary"                                                         ||
||                                                                            ||
\\============================================================================//


# Used featureCounts/Subread version:

featureCounts v2.0.6

# Successfully finished script featurecounts.sh
Fri Apr 12 10:45:21 EDT 2024
```
</details>

<hr style="height:1pt; visibility:hidden;" />

### Exercise 4

<details><summary>Runner script solution _(click to expand)_</summary>
```bash
# Step 5: QC summaries with MultiQC
sbatch scripts/multiqc.sh results results/multiqc
```
</details>

<details><summary>MultiQC Slurm log file _(click to expand)_</summary>
```bash-out-solo
# Starting script multiqc.sh
Fri Apr 12 11:43:45 EDT 2024
# Input dir:                      results
# Output file:                    results/multiqc


  /// MultiQC 🔍 | v1.17

|           multiqc | Search path : /fs/ess/PAS0471/jelmer/teach/courses/pracs-sp24/week6/exercises/results
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 635/635  
|    feature_counts | Found 22 reports
|              star | Found 22 reports
|          cutadapt | Found 44 reports
|            fastqc | Found 88 reports
|           multiqc | Report      : results/multiqc/multiqc_report.html
|           multiqc | Data        : results/multiqc/multiqc_data
|           multiqc | MultiQC complete

# Used MultiQC version:
multiqc, version 1.17
# Successfully finished script multiqc.sh
Fri Apr 12 11:44:30 EDT 2024
```
</details>

[Here is a copy of the MultiQC report that I got](misc/multiqc_report.html).

<hr style="height:1pt; visibility:hidden;" />

### Complete final runner script

<details><summary>Complete final runner script _(click to expand)_</summary>
```bash
#!/bin/bash

# 2024-04-12, Jelmer Poelstra
# - A runner script to run a simple RNA-seq analysis, creating a gene count table
#   from RNA-seq reads and a reference genome assembly and annotation.
# - The steps are read QC and trimming, alignment, and quantification.
# - The working dir is /fs/ess/PAS2880/users/jelmer/week06/exercises.
# - I am working on the OSC Pitzer cluster.

# Step 0: setting up
# A) Define the inputs
fastq_dir=../../garrigos-data/fastq
fasta=../../garrigos-data/ref/GCF_016801865.2.fna
gtf=../../garrigos-data/ref/GCF_016801865.2.gtf
# B) Define settings
strandedness=1
# C) Define the outputs
count_table=results/featurecounts/counts.tsv

# Step 1: QC the reads with FastQC
for fastq_file in "$fastq_dir"/*fastq.gz; do
    sbatch scripts/fastqc.sh "$fastq_file" results/fastqc
done
  
# Step 2: Trim the reads with TrimGalore
for R1 in "$fastq_dir"/*_R1.fastq.gz; do
    sbatch scripts/trimgalore.sh "$R1" results/trimgalore
done

# Step 3: Align the reads with STAR
# A) Index the reference genomes
sbatch scripts/star_index.sh "$fasta" "$gtf" results/star/index
# B) Align the reads to the index
for R1 in results/trimgalore/*R1.fastq.gz; do
    sbatch scripts/star_align.sh "$R1" results/star/index "$gtf" results/star
done

# Step 4: Create a gene count table with featureCounts
sbatch scripts/featurecounts.sh results/star "$gtf" "$strandedness" "$count_table"

# Step 5: QC summaries with MultiQC
sbatch scripts/multiqc.sh results results/multiqc
```
</details>
<br><br>


<details><summary>**9.** Change file permissions</summary>

Before we start, let's check the current file permissions:

```bash
ls -lh data/fastq
```
```bash-out
ls -lh data/fastq/ | head
total 0
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample001_F.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample001_R.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample002_F.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample002_R.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample003_F.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample003_R.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample004_F.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample004_R.fastq.gz
-rw-rw----+ 1 jelmer PAS0471 0 Mar 18 10:19 sample005_F.fastq.gz
```

The file "owner"/"user" (you) and the "group" (in this case, PAS0471, likely a different group for you)
have read and write permissions, and "others" have no permissions at all.

There are several different ways to change permissions with the `chmod` command.
Here are some examples which would ensure that no-one has write permission for the raw data:

- Set read(-only) permissions for all:

  ```sh
  # a=r => all=read
  chmod a=r data/fastq/*
  ```

- Take away write permissions for all:

  ```bash
  # a-w => all minus write
  chmod a-w data/fastq/*
  ```

- You can also use the "numeric" syntax:

  ```bash
  chmod 444 data/fastq/*
  ```

Whereas after running the second option, others won't have read-access,
the first and third option should give this result:

```bash
ls -lh data/fastq
```
```bash-out
ls -lh data/fastq/ | head
total 0
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample001_F.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample001_R.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample002_F.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample002_R.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample003_F.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample003_R.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample004_F.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample004_R.fastq.gz
-r--r--r--+ 1 jelmer PAS0471 0 Mar 18 10:19 sample005_F.fastq.gz
```

</details>
