---
title: "Running command-line software with shell scripts"
subtitle: "Week 6 -- part II"
pagetitle: "PRACS25: shell scripts II"
date: 2025-09-25
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu
other-links:
  - text: "Week 6 overview"
    icon: book
    href: w6_overview.html
  - text: "Week 6 graded assignment"
    icon: pencil
    href: w6_ga_shell-scripts.html
  - text: "w6-1: Shell scripting I"
    icon: bookmarks
    href: w3_1_shellfiles.html
  - text: "Optional reading: Advanced shell scripting and looping"
    icon: book
    href: ../ref/while-arrays.html
editor_options: 
  chunk_output_type: console
---

----------------------------------------------------------------------------------------------------

<br>

## Introduction

### Learning goals

This session focuses on using programs, like various bioinformatics tools,
with command-line interfaces (CLIs), and on running these **using shell scripts**.

Recall from the previous session's learning goals that this is one step in being
able to run your analyses highly efficiently by submitting scripts as
-potentially large numbers of- "batch jobs" using HPC resources like those at OSC.

More specifically, the strategy you'll learn is
**writing scripts that run a single program a single time**.
This will be true even if you need to run the program many times, so you will:

- loop over files/samples _outside_ of that script and run/submit the script
  possibly many times;
  
- need to make these scripts flexible:
  instead of "hard-coding" file paths and potentially other settings,
  you will pass arguments to scripts like you learned in the previous session.
  
When your scripts are flexible and you commonly loop over them,
this means that
**you'll also type lots of important code outside of these scripts**.
You will need to store this code,
as it will provide a record of what you did and can easily be reorganized into
a reproducible protocol of your workflow.
_We will continue to a use Markdown files for purpose. _

We'll start with a quick intro to FASTQ files and the FastQC program,
which will be our first example of a CLI tool.

### Getting ready


<br>

## Running FastQC with a shell script

Instead of running FastQC interactively, we'll want to write a script that runs it.
Specifically, our script will deliberately run FastQC on **only one FASTQ file**.

In bioinformatics, you commonly need to run a CLI tool many times,
because many tools can or have to be run separately run for each file or sample.
And even if they can run on many files at once (like FastQC can),
given that we have access to OSC's clusters,
it will save running time -potentially _a lot of_ it-
when we **submit a separate batch job for each FASTQ file**.

This is why we will write a script such that runs only one file,
and then we'll run that script many times using a loop _outside_ of the script.

For now, we'll practice with writing scripts this way, and running them interactively.
Next week, we will take the next step and submit each run of the script as a batch job.

<hr style="height:1pt; visibility:hidden;" />

### Arguments to the script

Our approach of running the script for one FASTQ file at a time means that
our script needs to **accept a FASTQ file name as an argument**.
Additionally, we will have an output dir argument too,
so we can also keep that flexible.

With code to copy the placeholder variables that contain the command-line arguments,
that part of the script would then look as follows:

```bash
# [Don't copy or run this]
# Copy the placeholder variables
fastq=$1
outdir=$2

# Run FastQC
fastqc --outdir "$outdir" "$fastq"
```

And such a script would be run for a single file as follows:

```bash
# [Don't copy or run this]
# Syntax: 'bash <script-path> <argument1> <argument2>'
bash scripts/fastqc.sh garrigos-data/fastq/ERR10802863_R2.fastq.gz results/fastqc
```

Let's dive into this and create a complete script and run it ---
first for one file like above, and then for all files with a loop.

<hr style="height:1pt; visibility:hidden;" />

### Creating an initial script

We saw some code to run FastQC inside a script,
to which we should add some "boilerplate" but important code:

- The shebang line and strict Bash settings:

  ```bash
  #!/bin/bash
  set -euo pipefail
  ```

- A line to load the relevant OSC software module:

  ```bash
  module load fastqc/0.12.1
  ```
  
- A line to create the output directory if it doesn't yet exist:

  ```bash
  mkdir -p "$outdir"
  ```

:::{.callout-tip collapse="true"}
#### More about the `-p` option to `mkdir` _(Click to expand)_

Using the `-p` option does two things at once,
and both are necessary for a foolproof inclusion of this command in a script:

- It will enable `mkdir` to create multiple levels of directories at once
  (i.e., to act _recursively_):
  by default, `mkdir` errors out if the parent directory/ies of the
  specified directory don't yet exist.

  ```bash
  mkdir newdir1/newdir2
  ```
  ```{.bash-out}
  mkdir: cannot create directory ‘newdir1/newdir2’: No such file or directory
  ```

  ```bash
  # This successfully creates both directories:
  mkdir -p newdir1/newdir2
  ```

- If the directory already exists, with `-p`,
  `mkdir` won't do anything and won't return an error.
  Without this option, `mkdir` would return an error in this case,
  which would in turn lead the script to abort (given our `set` settings):
  
  ```bash
  mkdir newdir1/newdir2
  ```
  ```{.bash-out}
  mkdir: cannot create directory ‘newdir1/newdir2’: File exists
  ```

  ```bash
  # This does nothing since the dirs already exist
  mkdir -p newdir1/newdir2
  ```
:::

With those additions, our partial script would look like this:

```bash
# [Don't copy or run this - we'll add to it later]

#!/bin/bash
set -euo pipefail

# Load the OSC module for FastQC
module load fastqc/0.12.1

# Copy the placeholder variables
fastq=$1
outdir=$2

# Create the output dir if needed
mkdir -p "$outdir"

# Run FastQC
fastqc --outdir "$outdir" "$fastq"
```

Notice that this script to run a CLI tool is very similar to our "toy scripts"
from the previous sessions: mostly standard ("boilerplate") code with
**just a single command to run our program of interest.**
Therefore, you can adopt this script as a template for scripts that run other
command-line programs, and will generally only need minor modifications!

<hr style="height:1pt; visibility:hidden;" />

### Add some "logging" statements

It is often useful to have your scripts "report" or "log" what is going on.
For instance:

- At what date and time did we run this script. 
- Which arguments were passed to the script.
- What are the designated output dirs/files.
- Perhaps even summaries of the output (we won't do this here).

This information can help with troubleshooting and record-keeping.
One thing to keep in mind here is that later,
when you submit scripts as batch jobs (as you'll learn to do next week),
such logging output will _not_ be printed to screen but will end up in text files.
_You can store those text files along with other output files to keep detailed_
_information about what you did!_

Let's try adding some logging information to our FastQC script:

```bash
#!/bin/bash
set -euo pipefail

# Load the OSC module for FastQC
module load fastqc/0.12.1

# Copy the placeholder variables
fastq=$1
outdir=$2

# Initial logging
echo "# Starting script fastqc.sh"
date
echo "# Input FASTQ file:   $fastq"
echo "# Output dir:         $outdir"
echo

# Create the output dir if needed
mkdir -p "$outdir"

# Run FastQC
fastqc --outdir "$outdir" "$fastq"

# Final logging
echo "# Used FastQC version:"
fastqc --version
echo
echo "# Successfully finished script fastqc.sh"
date
```

A couple of notes about the lines that were added to the script above:

- We printed a "marker line" `Successfully finished script` that indicates the
  end of the script was reached.
  This is useful because of our `set` settings:
  **seeing this line printed means that no errors were encountered**.
- Running `date` at the beginning and end of the script is one way to check
  how long the script took to run.
- Printing the input files can be particularly useful for troubleshooting.
- The lines that only have `echo` will simply print a blank line,
  basically as a separator between sections.
- For scripts that run bioinformatics tools,
  it's a good idea **include a line to print the program version**.

{{< fa user-edit >}} Create a script to run FastQC:

```bash
touch scripts/fastqc.sh
```

Open it and paste in the code in the box above.

<hr style="height:1pt; visibility:hidden;" />

### Running your FastQC script for 1 file

Run your FastQC script for one FASTQ file:

```bash
bash scripts/fastqc.sh garrigos-data/fastq/ERR10802863_R1.fastq.gz results/fastqc
```
```bash-out
# Starting script fastqc.sh
Wed Mar 27 21:53:13 EDT 2024
# Input FASTQ file:   garrigos-data/fastq/ERR10802863_R1.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
Approx 10% complete for ERR10802863_R1.fastq.gz
Approx 15% complete for ERR10802863_R1.fastq.gz
Approx 20% complete for ERR10802863_R1.fastq.gz
Approx 25% complete for ERR10802863_R1.fastq.gz
Approx 30% complete for ERR10802863_R1.fastq.gz
Approx 35% complete for ERR10802863_R1.fastq.gz
Approx 40% complete for ERR10802863_R1.fastq.gz
Approx 45% complete for ERR10802863_R1.fastq.gz
Approx 50% complete for ERR10802863_R1.fastq.gz
Approx 55% complete for ERR10802863_R1.fastq.gz
Approx 60% complete for ERR10802863_R1.fastq.gz
Approx 65% complete for ERR10802863_R1.fastq.gz
Approx 70% complete for ERR10802863_R1.fastq.gz
Approx 75% complete for ERR10802863_R1.fastq.gz
Approx 80% complete for ERR10802863_R1.fastq.gz
Approx 85% complete for ERR10802863_R1.fastq.gz
Approx 90% complete for ERR10802863_R1.fastq.gz
Approx 95% complete for ERR10802863_R1.fastq.gz
Approx 100% complete for ERR10802863_R1.fastq.gz
Analysis complete for ERR10802863_R1.fastq.gz

# Succesfully finished script fastqc.sh
Wed Mar 27 21:53:19 EDT 2024
```

However, as discussed above,
we'll eventually want to run the script for each FASTQ file.
We will write the loop to do so in an accompanying Markdown document.

<br>

## A "Protocol" Markdown file

The abovementioned loop code _could_ be directly typed in the terminal,
but we need to keep a record of and/or build a protocol of our analysis steps,
so we will save this in a Markdown file.

For small projects,
a simple protocol of steps could be added to your main `README.md`,
which is what we'll do here:

```bash
touch README.md
```

Open that file in the VS Code editor, and add the following to it:

````markdown
# RNA-Seq data analysis

## General information

- Author: Jelmer Poelstra
- Date: 2025-10-02
- Environment: Pitzer cluster at OSC via VS Code
- Working dir: `/fs/ess/PAS2880/users/<username>/week05`

## Project background

This project is ...

## Protocol
````

::: callout-tip
#### [Next week](../week07/w7_2_protocol.qmd), we will discuss how you can organize this for larger projects.
:::

<br>

## For loops

Loops are another universal element of programming languages,
and are used to **repeat operations**.
Here, we'll only cover the most common type of loop: the `for` loop.

A `for` loop _iterates_ over a collection, such as a list of files,
and allows you to perform one or more actions for each element in the collection.
In the example below,
our "collection" is just a short list of numbers (`1`, `2`, and `3`):

```bash
for a_number in 1 2 3; do
    echo "In this iteration of the loop, the number is $a_number"
    echo "--------"
done
```
```bash-out
In this iteration of the loop, the number is 1
--------
In this iteration of the loop, the number is 2
--------
In this iteration of the loop, the number is 3
--------
```

The **indented lines** between `do` and `done` contain the code that is being executed
_as many times as there are items in the collection_:
in this case 3 times, as you can tell from the output above.

What was actually run under the hood is the following:

```bash
# (Don't run this)
a_number=1
echo "In this iteration of the loop, the number is $a_number"
echo "--------"

a_number=2
echo "In this iteration of the loop, the number is $a_number"
echo "--------"

a_number=3
echo "In this iteration of the loop, the number is $a_number"
echo "--------"
```

Here are **two key things to understand about `for` loops**:

- In each iteration of the loop, one element in the collection
  **is being assigned to the variable** specified after `for`.
  In the example above, we used `a_number` as the variable name,
  so that variable contained `1` when the loop ran for the first time,
  `2` when it ran for the second time,
  and `3` when it ran for the third and last time.

- The loop runs sequentially for each item in the collection,
  and will run exactly as many times as there are items in the collection.

::: {.callout-note}
#### A further explanation of `for` loop syntax

On the first and last, unindented lines,
`for` loops contain the following mandatory keywords:

| Keyword | Purpose	                            |
|---------|-------------------------------------|
| `for`	  | After `for`, we set the **variable name** (an arbitrary name; above we used `a_number`)
| `in`	  | After `in`, we specify the **collection** (list of items) we are looping over	
| `do`	  | After `do`, we have one ore more lines specifying what to do with each item	
| `done`  | Tells the shell we are done with the loop 

:::

<hr style="height:1pt; visibility:hidden;" />

#### Combining loops and globbing

A very useful strategy is to loop over files with globbing, for example:

```bash
for fastq_file in *fastq; do
    echo "Running an analysis for file $fastq_file"...
    # [This is where you would put additional commands to process each FASTQ file]
done
```
```bash-out
Running an analysis for file sample1_R1.fastq...
Running an analysis for file sample1_R2.fastq...
Running an analysis for file sample2_R1.fastq...
Running an analysis for file sample2_R2.fastq...
Running an analysis for file sample3_R1.fastq...
Running an analysis for file sample3_R2.fastq...
```

:::{.exercise}
#### {{< fa user-edit >}} **Exercise**: A simple loop

Modify the loop in our previous example to count and then print the number of
lines that each FASTQ file contains:

```bash-out
sample1_R1.fastq contains 0 lines
sample1_R2.fastq contains 0 lines
# etc.
```

_To be clear, the number of lines that the loop reports should result from_
_an actual count with `wc -l` and you should not just type `0`._

<details><summary>Click for the solution</summary>

```bash
for fastq_file in *fastq; do
    n_lines=$(wc -l fastq)
    echo "$fastq_file contains $n_lines lines"
done
```
```bash-out
sample1_R1.fastq contains 0 lines
sample1_R2.fastq contains 0 lines
sample2_R1.fastq contains 0 lines
sample2_R2.fastq contains 0 lines
sample3_R1.fastq contains 0 lines
sample3_R2.fastq contains 0 lines
```
</details>

<hr style="height:1pt; visibility:hidden;" />
:::

<br>

## Running a script many times with a loop

We will now loop over all FASTQ files in the `garrigos-data/fastq` dir,
and run our `fastqc.sh` script for each file.

Add the following to your `README.md` file,
and then run the code inside the code block:

````markdown
- Step 1 - Run FastQC for each FASTQ file:

```bash
for fastq in garrigos-data/fastq/*fastq.gz; do
    bash scripts/fastqc.sh "$fastq" results/fastqc
done
```
````

```bash-out
# Starting script fastqc.sh
Thu Mar 21 10:06:46 EDT 2024
# Input FASTQ file:   garrigos-data/fastq/ERR10802863_R1.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R1.fastq.gz
Approx 5% complete for ERR10802863_R1.fastq.gz
# [...output truncated...]

# Successfully finished script fastqc.sh
Thu Mar 21 10:06:51 EDT 2024

# Starting script fastqc.sh
Thu Mar 21 10:06:51 EDT 2024
# Input FASTQ file:   garrigos-data/fastq/ERR10802863_R2.fastq.gz
# Output dir:         results/fastqc

Started analysis of ERR10802863_R2.fastq.gz
Approx 5% complete for ERR10802863_R2.fastq.gz
# [...output truncated...]
```

Wow, that's a lot of output!
You can hopefully see that this looping approach is quite powerful and can allow
you to easily run a script many times.
However, note that this runs the `fastqc.sh` script _sequentially_:
after it was run for the first FASTQ file, it will run for the second file,
and so on.
If these had been full-size FASTQ files,
it may have still taken hours for this to finish.

Next week, you'll learn about submitting scripts like this as batch jobs
which means you can run a script _simultaneously_ (in parallel) many times,
which can be a huge time-saver.

<hr style="height:1pt; visibility:hidden;" />

## Looping over samples rather than files 

In some cases, we can't simply loop over all files like we have done so far.
For example, in many tools that process paired-end FASTQ files,
the corresponding R1 and R2 files for each sample must be processed together.
That is, we don't run the tool separately for each FASTQ file,
but for each sample (i.e. each _pair_ of FASTQ files).

How can we loop over pairs of FASTQ files instead? There are two main ways:

- Create a list of **sample IDs**,
  loop over these IDs, and find the pair of FASTQ files with matching names.
- Loop over the **R1 files only** and then infer the name of the corresponding
  R2 file within the loop. This is generally straightforward because the file names
  should be identical other than the read-direction identifier (`R1`/`R2`).

Below, we will use the second method ---
but first, we need to learn about parameter expansion.

### Parameter expansion

You can use so-called "parameter expansion",
where parameter is basically another word for variable,
to search-and-replace text in your variable's values.
For example:

- Assign a short DNA sequence to a variable:

  ```bash
  dna_seq="AAGTTCAT"
  echo "$dna_seq"
  ```
  ```bash-out
  AAGTTCAT
  ```

- Use parameter expansion to replace all `T`s with `U` to convert the DNA to RNA:

  ```bash
  echo "${dna_seq//T/U}"
  ```
  ```bash-out
  AAGUUCAT
  ```

- You can also assign the result of the parameter expansion back to a variable:

  ```bash
  rna_seq="${dna_seq//T/U}"
  echo "$rna_seq"
  ```
  ```bash-out
  AAGUUCAT
  ```

So, the syntax for this type of parameter expansion is `{var_name//<search>/replace}` ---
let's deconstruct that:

1. Reference the variable, using the full notation, with braces (`${var_name}`)
2. After the first two forward slashes, enter the search pattern: (`T`)
3. After another forward slash, enter the replacement: (`U`).

If you needed to replace at most one of the search patterns, a single backslash
after the variable name would suffice: `{var_name/<search>/replace}`.

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Exercise: Get the R2 file name with parameter expansion
File names of corresponding R1 and R2 FASTQ files should be identical other than
the marker indicating the read direction,
which is typically `_R1`/`_R2` (and in some cases just `_1` / `_2`).

After assigning the file name `garrigos-data/fastq/ERR10802863_R1.fastq.gz` to a variable,
as shown below,
add the parameter expansion needed to obtain the name of the corresponding R2 file
by completing the second line:

```bash
fastq_R1=garrigos-data/fastq/ERR10802863_R1.fastq.gz
fastq_R2=
```

<details><summary>Solutions</summary>

```bash
fastq_R1=garrigos-data/fastq/ERR10802863_R1.fastq.gz
fastq_R2=${fastq_R1/_R1/_R2}
```

Test that it worked:

```bash
echo "$fastq_R2"
```
```bash-out
garrigos-data/fastq/ERR10802863_R2.fastq.gz
```
</details>
:::

<hr style="height:1pt; visibility:hidden;" />

### A per-sample loop

Now, we can create a loop that iterates over R1 FASTQ files only,
and then infers the corresponding R2 file name ---
for example, with an imaginary `trim.sh` script:

```bash
# [Don't run this]
for R1 in garrigos-data/fastq/*_R1.fastq.gz; do
  R2=${R1/_R1/_R2}
  bash scripts/trim.sh "$R1" "$R2" results/trim
done
```

<hr style="height:1pt; visibility:hidden;" />

::: exercise
#### {{< fa user-edit >}} Bonus exercise: Run a script with a per-sample loop

**A)** Write a script that accepts three arguments:
an R1 FASTQ file, an R2 FASTQ file, and an output dir.
This script should mock-run the fictional `trimmer` program as follows:

```bash
# Mock-run the tool: by prefacing the command with 'echo' it will only be printed
echo trimmer --in1 "$R1" --in2 "$R2" --outdir "$outdir"
```

(You can use your `fastqc.sh` script as a template -- e.g. copy that script and
then modify the copy.)

<details><summary>Solution</summary>
```bash
#!/bin/bash
set -euo pipefail

# Copy the placeholder variables
R1=$1
R2=$2
outdir=$3

# Create the output dir if needed
mkdir -p "$outdir"

# Initial reporting
echo "# Starting script trim_mock.sh"
date
echo "# Input R1 file:       $R1"
echo "# Input R2 file:       $R2"
echo "# Output dir:          $outdir"
echo

# Mock-run the tool: I preface the command with 'echo',
# so it will just print the commands (instead of trying to run a non-existing program)
echo trimmer --in1 "$R1" --in2 "$R2" --outdir "$outdir"

# Final reporting
echo
echo "# Succesfully finished script trim_mock.sh"
date
```
</details>

**B)** Add an entry to your `README.md` file to loop over all R1 FASTQ files and
run the `trim_mock.sh` script for each sample.

<details><summary>Solution</summary>

````markdown
- Step 2: run the trim_mock.sh script for each _sample_.
  We will loop over R1 files only, and infer the R2 file name:

```bash
for R1 in garrigos-data/fastq/*_R1.fastq.gz; do
    R2=${R1/_R1/_R2}
    bash scripts/trim_mock.sh "$R1" "$R2" results/trim_mock
done
```
````

```bash-out
# Starting script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024
# Input R1 file:       garrigos-data/fastq/ERR10802863_R1.fastq.gz
# Input R2 file:       garrigos-data/fastq/ERR10802863_R2.fastq.gz
# Output dir:          results/trim_mock

trimmer --in1 garrigos-data/fastq/ERR10802863_R1.fastq.gz --in2 garrigos-data/fastq/ERR10802863_R2.fastq.gz --outdir results/trim_mock

# Succesfully finished script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024

# Starting script trim_mock.sh
Thu Mar 21 10:12:17 EDT 2024
# Input R1 file:       garrigos-data/fastq/ERR10802864_R1.fastq.gz
# [...output truncated...]
```
</details>

:::

<br>

## Your final protocol Markdown file

Your final protocol Markdown file for this (dummy) project should look like this:

````markdown
# RNA-Seq data analysis

## General information

- Author: Jelmer Poelstra
- Date: 2025-10-02
- Environment: Pitzer cluster at OSC via VS Code
- Working dir: `/fs/ess/PAS2880/users/<username>/week05`

## Project background

This project is ...

## Protocol

- Step 1 - Run FastQC for each FASTQ file:

```bash
for fastq in garrigos-data/fastq/*fastq.gz; do
    bash scripts/fastqc.sh "$fastq" results/fastqc
done
```

- Step 2 - run the trim_mock.sh script for each _sample_.
  We will loop over R1 files only, and infer the R2 file name:

```bash
for R1 in garrigos-data/fastq/*_R1.fastq.gz; do
    R2=${R1/_R1/_R2}
    bash scripts/trim_mock.sh "$R1" "$R2" results/trim_mock
done
```

````

<br>

:::callout-note
#### Hard-coding settings

We've been writing shell scripts that accept arguments,
instead of including variable things like inputs and outputs in the scripts themselves.
The latter method can be referred to as "hard-coding" these items.
  
You can also use arguments for _settings_ like bioinformatics program options
you may want to vary among different runs of the script,
or relatedly, for information about your data like read length or RNA-seq library
strandedness (as you did in last week's exercises).
If you don't hard-code these options in your script but have arguments for them,
it will be easier to re-use your script in different contexts.

But there is balance to be struck here, and you can also "hobble" your script
with a confusing array of arguably too many arguments.

When you do hard-code potentially variable things in your script,
it can be a good idea to define them clearly **at the top of your script**.
For example:
  
```bash
#!/bin/bash
set -euo pipefail
  
# Settings and constants
MIN_QUAL=30
```

Such variables can be referred to as "constants",
since they are hard-coded in the script,
and in shell code, ALL-CAPS is regularly used for them^[
But this is far from universal. It is also fairly common to use all-caps
for all shell variables, but this is not what we've been doing.].

**TBA expand**
:::

<br>

## At-home reading: A script that defines output _files_

### `basename` and `dirname` to extract parts of paths

In loops and other contexts where you are working with file names programmatically,
you often have a path to a file and need to extract just the file name part from it.

For example, we can think of the path `data/fastq/sample1_R1.fastq` as consisting
of a directory part (`data/fastq/`) and a filename part (`sample1_R1.fastq`).

Running the `basename` command on a file path will strip any directories and
just return the file name:
  
```sh
basename garrigos-data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
ERR10802863_R1.fastq.gz
```

You can also provide a *suffix to also strip* from the file name:

```sh
basename garrigos-data/fastq/ERR10802863_R1.fastq.gz .fastq.gz
```
```bash-out
ERR10802863_R1
```

If you instead want the _directory_ part of a path, use the `dirname` command:

```sh
dirname garrigos-data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
garrigos-data/fastq
```

<hr style="height:1pt; visibility:hidden;" />

### A script variant that defines output _files_

In previous shell script examples, we only defined and used an output dir.
But some programs allow or require you to define the output file names.

Here is an example of doing that inside a script:

```bash
#!/bin/bash
set -euo pipefail

# Copy the placeholder variables
R1_in=$1
R2_in=$2
outdir=$3

# Define the output file names
R1_out="$outdir"/$(basename "$R1_in")
R2_out="$outdir"/$(basename "$R2_in")

# Run a fictional program
trimmer2 --in1 "$R1_in" --in2 "$R2_in" --out1 "$R1_out" --out2 "$R2_out"
```
