---
title: "Week 6: Shell scripting & CLI tools"
pagetitle: "Week 6 overview"
date: 2025-09-26
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "w6a: Shell scripting basics"
    icon: bookmarks
    href: w6a_scripts.html
  - text: "w6b: Shell scripting - CLI tools"
    icon: bookmarks
    href: w6b_cli-tools.html
  - text: "w6c: Shell tips and tricks"
    icon: bookmarks
    href: w6c_tricks.html
  - text: "Week 6 graded assignment"
    icon: pencil
    href: w6_ga.html
bibliography: ../references.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Overview

This week, you will learn how to write shell scripts and use them to run programs
with command-line interfaces (CLIs), like various bioinformatics tools.

The end goal is to be able to submit shell scripts as "batch jobs" at OSC,
which e.g. allows you to run them simultaneously up to hundreds of times!
To get there, you need to learn about the following topics:

1. The basics of shell scripts _(this week)_
2. Running command-line programs using shell scripts _(this week)_
3. Submitting batch jobs with Slurm _(next week)_

## Learning goals

#### [Shell scripting basics](./w6a_scripts.qmd)

- Why it is useful to collect your commands into shell scripts that can be rerun easily
- The basics of shell scripts including hell script header lines
- Why and how to adorn scripts with tests and `echo` statements
- More on shell variables and how to use them
- Using command-line arguments with your own scripts

#### [Running command-line software with shell scripts](./w6b_cli-tools.qmd)

- Running command-line programs (we focus on bioinformatics tools),
  and running them using shell scripts
- How `for` loops work
- How to use a `for` loop to loop over files and run a shell script many times

#### [Unix shell tips & tricks](./w6c_tricks.qmd)

- Parameter expansion -- and using this in the context of looping over samples
  (pairs of FASTQ files) rather than individual files
- Command substitution to save the output of commands
- `basename` and `dirname` to extract parts of file paths

## Exercises & assignments

- **Graded assignment**: [Software and shell scripts](w6_ga.qmd) [_(Due 10/05)_]{style="color:#bb0000"}

## Further resources

- @buffalo2015 ([OSU libray link](https://search.library.osu.edu/permalink/01OHIOLINK_OSU/1oqfg3i/alma991085518416808507))
  -- Chapter 12: "Bioinformatics Shell Scripting, Writing Pipelines, and Parallelizing Tasks"
  
  The latter part of this chapter is about using `find`, `xargs`, and Makefiles.
  These are somewhat tangential to the week's topic of scripts,
  and we will not talk about them in class.
  As for Makefiles specifically,
  you will learn an alternative approach to workflow management later in this course,
  so I would recommend to only skim that part.
