---
title: "Advanced shell scripting"
subtitle: "Week 6 -- Lecture C"
pagetitle: "Advanced shell scripting"
date: 2025-09-26
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
other-links:
  - text: "Week 6 overview"
    icon: book
    href: w6_overview.html
  - text: "w6a: Shell scripting I"
    icon: bookmarks
    href: w6a_scripts.html
  - text: "w6b: Shell scripting - CLI tools"
    icon: bookmarks
    href: w6b_cli-tools.html
  - text: "Week 6 graded assignment"
    icon: pencil
    href: w6_ga.html
---

-------

<br>

## Command substitution

Command substitution allows you to **store the output of a command in a variable**.
This is especially useful in scripts and loops.

Let's see an example.
As you know, the `date` command will print the current date and time:

```bash
date
```
```bash-out
Thu Sep 11 14:52:22 EDT 2025
```

If we try to _store the date in a variable_ directly, it doesn't work:
the literal string "date" is stored instead:

```bash
today=date
echo "$today"
```
```bash-out
date
```

That's why we need command substitution, which we can use by wrapping the command 
inside **`$()`**:

```bash
today=$(date)
echo "$today"
```
```bash-out
Thu Sep 11 14:54:11 EDT 2025
```

One practical example of using command substitution is when you want to
**automatically include the current date in a file name**
(with "automatic" meaning that you can use the same command regardless of the date,
and that you could use it in a script that you could run at any point).
First, note that we can use `date +%F` to get `YYYY-MM-DD` format without the time:

```bash
date +%F
```
```bash-out
2025-09-07
```

Let's use that in a command substitution:

```bash
today=$(date +%F)
touch README_"$today".txt

ls
```
```{.bash-out}
README_2025-09-07.txt
```

::: callout-note
#### Or insert the command substitution on the fly
It is even possible to do this all in one go,
by using the command substitution `$(date +%F)` _directly_ in our
`touch` command, rather than first assigning it to a variable:

```bash
touch README_"$(date +%F)".txt
```
:::

:::{.exercise}
#### {{< fa user-edit >}} Exercise: Command substitution

Say we wanted to count and report the number of FASTQ files in a directory
in a generalized, programmatic way. To do the counting, we can run:

```bash
ls *fastq | wc -l
```
```{.bash-out}
6
```

Now, use command substitution to store the output of the last command in a variable,
and then use an `echo` command to print the following:

```bash-out-solo
The dir has 6 files
```

_To be clear, `6` (or whatever the number of files ends up being) should be contained_
_in a variable and you should not be typing that character yourself!_

<details><summary>Click for a hint</summary>

Your final `echo` command should look something like this:

```bash
echo "The dir has $n_files files"
```

Now, you try to store the number of files in the variable `$n_files`.
</details>

<details><summary>Click for the solution</summary>

```bash
n_files=$(ls *fastq | wc -l)

echo "The dir has $n_files files"
```
```{.bash-out}
The dir has 6 files
```

**Note:**
You don't have to quote variables _inside_ a quoted `echo` call,
since it's, well, already quoted.
If you _also_ quote the variables, you will in fact _unquote_ it,
although that shouldn't pose a problem inside `echo` statements.

</details>
:::


## A script that defines output _files_

### `basename` and `dirname` to extract parts of paths

In loops and other contexts where you are working with file names programmatically,
you often have a path to a file and need to extract just the file name part from it.

For example, we can think of the path `data/fastq/sample1_R1.fastq` as consisting
of a directory part (`data/fastq/`) and a filename part (`sample1_R1.fastq`).

Running the `basename` command on a file path will strip any directories and
just return the file name:
  
```sh
basename garrigos-data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
ERR10802863_R1.fastq.gz
```

You can also provide a *suffix to also strip* from the file name:

```sh
basename garrigos-data/fastq/ERR10802863_R1.fastq.gz .fastq.gz
```
```bash-out
ERR10802863_R1
```

If you instead want the _directory_ part of a path, use the `dirname` command:

```sh
dirname garrigos-data/fastq/ERR10802863_R1.fastq.gz
```
```bash-out
garrigos-data/fastq
```

### A script variant that defines output _files_

In previous shell script examples, we only defined and used an output dir.
But some programs allow or require you to define the output file names.

Here is an example of doing that inside a script:

```bash
#!/bin/bash
set -euo pipefail

# Copy the placeholder variables
R1_in=$1
R2_in=$2
outdir=$3

# Define the output file names
R1_out="$outdir"/$(basename "$R1_in")
R2_out="$outdir"/$(basename "$R2_in")

# Run a fictional program
trimmer2 --in1 "$R1_in" --in2 "$R2_in" --out1 "$R1_out" --out2 "$R2_out"
```

## Conditionals

With conditionals like `if` statements, we can
**run one or more commands only if some condition is true**.
We can also run a different set of commands if the condition is _not_ true.

These features are especially useful in shell scripts because we may,
for instance, check that all the inputs are correct,
and exit with an informative error if that's not the case.

While this does add some complexity to your shell scripts,
it can be worth it because:

- The sooner you stop a script from running when there are such problems,
  the better.
- If we instead pass erroneous input to the program that our script runs,
  we sometimes get confusing errors or even worse, no clear errors at all.
 
### Basic syntax

This is the basic syntax of an `if` statement in Bash:

```sh
if <test>; then
    # Command(s) to run if the condition is true
fi
```

We'll have to add an `else` clause to run alternative command(s) if the condition
is false:

```sh
if <test>; then
    # Command(s) to run if the condition is true
else
    # Commands(s) to run if the condition is false
fi
```

<hr style="height:1pt; visibility:hidden;" />

In this first example of an `if` statement
we check the file type of an input file,
and exit the script if it's not of the correct type:

```sh
# [Hypothetical example - don't run this]
# Say we have a variable $filetype that contains a file's type
if [[ "$filetype" == "fastq" ]]; then
    echo "Processing FASTQ file..."
    # [Commands to process the FASTQ file...]
else
    echo "Error: unknown filetype!"
    exit 1
fi
```

In the code above, note that:

- The double square brackets `[[ ]]` represent a *test statement*^[
  You can also use single square brackets `[ ]` but the double brackets have more functionality
  and I would recommend to always use these.].
- The spaces bordering the brackets on the inside are necessary:
  `[["$filetype" == "fastq"]]` would fail!
- Double equals signs (`==`) are common in programming to _test for equality_ ---
  this is to contrast it with a single `=`, which is used for variable assignment.
- When used inside a script, the `exit` command will stop the execution of the script.
  With `exit 1`, the *exit status* of our script is 1:
  an exit status of 0 means success --- any other integer, including 1, means failure.  

### String comparisons

The above test, `"$filetype" == "fastq"`, was an example of a string comparison,
where "string" is basically another term for "text" that is common in programming contexts,
and mostly serves to distinguish this from numeric data.

The two main string comparisons are:

| String comparison            | Evaluates to true if
|-------|----------------|
| `str1 == str2` | Strings `str1` and `str2` are identical^[A single `=` also works but `==` is clearer.]
| `str1 != str2` | Strings `str1` and `str2` are different

: {.striped .hover}

<hr style="height:1pt; visibility:hidden;" />

### Integer (number) comparisons

It can be a good idea to test at the beginning of a script whether the correct
number of arguments were passed to it, and simply exit if that's not the case.

The `$#` variable will automatically contain the number of arguments that were
passed to a script:

```bash
# [Hypothetical example - don't run this]

if [[ ! "$#" -eq 2 ]]; then
    echo "Error: wrong number of arguments"
    echo "You provided $# arguments, while 2 are required."
    echo "Usage: printname.sh <first-name> <last-name>"
    exit 1
fi
```

<hr style="height:1pt; visibility:hidden;" />

| Integer comparisons           | Evaluates to true if
|-------|----------------|
| `int1 -eq int2`   | Integers `int1` and `int2` are equal
| `int1 -ne int2`   | Integers `int1` and `int2` are not equal
| `int1 -lt int2`   | Integer `int1` is less than `int2` (`-le` for less than or equal to)
| `int1 -gt int2`   | Integer `int1` is greater than `int2` (`-ge` for greater than or equal to)

: {.striped .hover}

::: {.callout-tip collapse="true"}
#### Another integer comparison example _(Click to expand)_
Say that we want to run a program with options that depend on our number of samples.
With the number of samples determined from the number of lines in a hypothetical file `samples.txt`
and stored in a variable `$n_samples`, we can test if the number is greater than 9
with `"$n_samples" -gt 9`, where `gt` stands for "greater than":

```sh
# [Hypothetical example - don't run this]

# Store the number of samples in variable $n_samples:
n_samples=$(cat samples.txt | wc -l)

# With '-gt 9', the if statement tests whether the number of samples is greater than 9:
if [[ "$n_samples" -gt 9 ]]; then
    # Commands to run if nr of samples >9:
    echo "Processing files with algorithm A"
else
    # Commands to run if nr of samples is <=9:
    echo "Processing files with algorithm B..."
fi
```
:::

### File tests

We can also test whether files or dirs exist:

| File/dir test | Evaluates to true if |
|---------|---------------------|
| `-f file`       | `file` exists and is a regular file (not a dir or link) |
| `-d dir`        | `dir` exists and is a directory &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |

: {.striped .hover}

<hr style="height:1pt; visibility:hidden;" />

For example,
the code below tests whether an input file exists using the file test **`-f`**
and if it does _not_ (hence the **`!`**), it will stop the execution of the script:

```sh
# [Hypothetical example - don't run this]
# '-f' is true if the file exists, so '! -f' is true if the file doesn't exist
if [[ ! -f "$fastq_file" ]]; then
    echo "Error: Input file $fastq_file not found!"
    exit 1
fi
```

::: {.callout-note collapse="true"}
#### Combining expressions with `&&` and `||` _(Click to expand)_
To test for multiple conditions at once,
use the `&&` ("and") and `||` ("or") shell operators --- for example:

- If the number of samples is less than 100 **and** at least 50 (i.e. 50-99):

  ```sh
  if [[ "$n_samples" -lt 100 && "$n_samples" -ge 50 ]]; then
      # Commands to run if the number of samples is 50-99
  fi
  ```
  
- If either one of two FASTQ files don't exist:

  ```sh
  if [[ ! -f "$fastq_R1" || ! -f "$fastq_R2" ]]; then
      # Commands to run if either file doesn't exist - probably report error & exit
  fi
  ```
:::

::: exercise
#### {{< fa user-edit >}} Exercise: Number of arguments

In your `printname.sh` script,
add the `if` statement from above that tests whether the correct number of arguments
were passed to the script.
Then, try running the script consecutively with 1, 2, and 3 arguments. 

<details><summary>Start with this `printname.sh` script we wrote above.</summary>
```bash
#!/bin/bash
set -euo pipefail

first_name=$1
last_name=$2

echo "This script will print a first and a last name"
echo "First name: $first_name"
echo "Last name: $last_name"
```
</details>

<details><summary>Click for the solution</summary>

Note that the `if` statement should come before you copy the variables to
`first_name` and `last_name`,
otherwise you get the "unbound variable error" before your descriptive custom error,
when you pass 0 or 1 arguments to the script.

The final script:

```bash
#!/bin/bash
set -euo pipefail

if [[ ! "$#" -eq 2 ]]; then
    echo "Error: wrong number of arguments"
    echo "You provided $# arguments, while 2 are required."
    echo "Usage: printname.sh <first-name> <last-name>"
    exit 1
fi

first_name=$1
last_name=$2

echo "This script will print a first and a last name"
echo "First name: $first_name"
echo "Last name: $last_name"
```

Run it with different numbers of arguments:

```bash
bash scripts/printname.sh Jelmer
```
```bash-out
Error: wrong number of arguments
You provided 1 arguments, while 2 are required.
Usage: printname.sh <first-name> <last-name>
```
```bash
bash scripts/printname.sh Jelmer Poelstra
```
```bash-out
First name: Jelmer
Last name: Poelstra
```
```bash
bash scripts/printname.sh Jelmer Wijtze Poelstra
```
```bash-out
Error: wrong number of arguments
You provided 3 arguments, while 2 are required.
Usage: printname.sh <first-name> <last-name>
```

</details>
:::

::: exercise
#### {{< fa user-edit >}} Exercise: Conditionals II

In your Markdown notes file,
write an `if` statement that tests whether the script `scripts/printname.sh` exists
and is a regular file, and:

- If it is (`then` block), report the outcome with `echo` (e.g. "The file is found").
- If it is not (`else` block), also report that outcome with `echo` (e.g. "The file is not found").

Then:

1. Run your `if` statement --- it should report that the file is found. 
2. Introduce a typo in the file name in the `if` statement, and run it again,
   to check that the file is not indeed not found.

<details><summary>Click for the solution</summary>
```sh
# Note: you need single quotes when using exclamation marks with echo!
if [[ -f scripts/printname.sh ]]; then
    echo 'Phew! The file is found.'
else
    echo 'Oh no! The file is not found!'
fi
```
```bash-out
Phew! The file is found.
```

After introducing a typo:

```sh
if [[ -f scripts/printnames.sh ]]; then
    echo 'Phew! The file is found.'
else
    echo 'Oh no! The file is not found!'
fi
```
```bash-out
Oh no! The file is not found!
```
</details>
:::
